libbpf/blazesym

- cbindgen.toml
- examples/addr2ln_sym.rs
- src/lib.rs
For Rust API,
- find_symbol() return a struct intead of a tuple.
- Remove the ProcessKernel variant from SymbolFileCfg.
For C API,
- Change the type of sym_file_cfg::cfg_type to an enum type.
> Change public API according the feedback from the draft.

- examples/addr2ln.rs
Use BlazeSymbolizer instead of DwarfResolver.  DwarfResolver is an
internal API.
> Use BlazeSymbolizer in addr2ln.

- examples/addr2ln.rs
- src/dwarf.rs
- src/elf_cache.rs
- src/lib.rs
This can help to shorten the loading time to 20x faster, loading linux
kernel image.
> Don't load line number information if it is disable.

- README.md
Issue #7 mentioned about link errors about the order of parameters sugguested in the README. libblazesym.a should go first before its dependencies.
> Fix the linking parameters order.

- src/lib.rs
Issue #7 mentioned that the BlazeSym doesn't resolve any address in the kernel space if a kernel image is not given or installed in the system. KernelResolver required both kallsyms and a kernel image to create itself successfully. However, the resolver should at least partially work even with only kallsyms.
> Allow KernelResolver to load only kallsyms or just the kernel image.

- src/dwarf.rs
Issue #8 raises the issue that the debug build will crash for checking the order of CU start addresses.  However, this check is not valid anymore since we sort the list of CUs.  In the future, we will support returning multiple symbols and line numbers.  So, this check is either unnecessary or too strict.
> Remove the order check of CU start addresses.

- src/dwarf.rs
- src/elf.rs
The changes of returning multiple symbols didn't stop properly.  It causes returning additional unwanted symbols.  By checking symbol names, it will stop properly to get a correct list of symbols.
> Fix that ElfResolver returned extra unnecessary symbols.

- src/dwarf.rs
- src/dwarf/debug_info.rs
- src/tools.rs
These code are used by several modules.  They should be moved out of dwarf.rs.
This is a preparation for resuing these functions in the GSYM parser.
> Move decode_*() functions from dwarf.rs to tools.rs.

- Cargo.toml
- src/elf_cache.rs
Currently running `cargo check` on a MacOS produces the following errors:
```
error[E0308]: mismatched types
--> src/elf_cache.rs:93:18
|
93 |             dev: stat.st_dev,
|                  ^^^^^^^^^^^ expected `u64`, found `i32`
error[E0308]: mismatched types
--> src/elf_cache.rs:107:24
|
107 |         stat.st_dev == self.dev
|                        ^^^^^^^^ expected `i32`, found `u64`
|
help: you can convert a `u64` to an `i32` and panic if the converted value doesn't fit
|
107 |         stat.st_dev == self.dev.try_into().unwrap()
|                                ++++++++++++++++++++
For more information about this error, try `rustc --explain E0308`.
error: could not compile `blazesym` due to 2 previous errors
```
This PR fixes them by adding casts and allows for a clean build.
> fix build on MacOS

- src/dwarf.rs
- src/elf.rs
- src/tools.rs
If functionality is only used by tests we should declare it as such. Marking it as dead will cause it to longer around in the code base forever, even if not referenced anywhere.
> Declare test-only functionality as test-only

- Cargo.toml
- src/dwarf.rs
As per the discussion over in
https://github.com/libbpf/blazesym/pull/25, now that we have a benchmark covering the DWARF parsing code path, we can stop relying on the dwarf_perf feature. Remove it.
> Remove dwarf_perf feature

- Cargo.toml
- README.md
- src/ksym.rs
We don't need a feature if we don't want to skip a test based on a runtime condition. We can just make it an ignored one, in which case it can be run with `cargo test -- --ignored`.
Hence, remove the feature and mark the one test using it as ignored instead.
> Remove dont_skip_tests feature

- README.md
- examples/addr2ln.rs
- src/elf_cache.rs
- src/ksym.rs
- src/lib.rs
- src/tools.rs
This change switches the library over to using `PathBuf`/`Path` instead of `String`/`str` for representing paths. Strings are overly strong in their assertions, in that they enforce UTF-8 encoding, which is not necessarily required for paths. It's also the correct thing to do, as it allows us to use native path manipulations. The conversion is fairly straight forward and mechanical. It's also pretty much fully compiler checked (modulo, perhaps, unsafe portions using pointer dances).
> Use `PathBuf`/`Path` instead of `String`/`str` for representing paths

- src/dwarf.rs
In Rust, `unsafe` blocks should be as small as possible in order to help identification of unsafe call sites and auditing upholding of invariants. `parse_debug_line_cu` clubs four `unsafe` calls into an `unsafe` block spanning some thirty lines. Split it up.
> Split unsafe block in `parse_debug_line_cu`

- src/dwarf.rs
- src/dwarf/debug_info.rs
- src/elf.rs
- src/lib.rs
- src/tools.rs
Remove more unused code or declare it test only so that we can eventually remove global allowance of the `dead_code` lint. If we need some of the removed functionality we can always get it back from version control, as discussed in person.
> Remove more unused code or declare it test only

- src/elf_cache.rs
- src/lib.rs
It turns out we have heaps of implicit unsafe operations in unsafe functions. Currently these don't require explicit wrapping in unsafe {}. That has arguably been identified as a wrong design decision of Rust, but it may only be changed in a new edition (if at all), because it would be a breaking change.
The unsafe_block_in_unsafe_fn lint [0] has been devised to fix this behavior, but it has to explicitly be opted in (though it may become the default eventually). Let's deny it, forcing us to make all unsafe blocks explicit. If we want to make any claims about memory safety of our code base (the desire of which basically is one of the reasons why it is being written in Rust), we need to have confidence that our unsafe code is sane. That requires awareness of it first.
A not insignificant …
> Make unsafe blocks explicit

- src/dwarf.rs
- src/dwarf/debug_info.rs
- src/elf.rs
Continuing what 24f74b2ee7bc ("Use PathBuf/Path instead of String/str for representing paths") started, this change converts the `Elf64Parser::filename` member from a `String` to a `PathBuf`. Surrounding infrastructure is adjusted as well in the process.
> Work with proper paths in Elf64Parser

- examples/addr2ln.rs
- examples/addr2ln_pid.rs
- src/dwarf.rs
- src/elf.rs
- src/gsym/parser.rs
- src/lib.rs
- src/tools.rs
With Rust 1.67 clippy warns about us not inlining some variables in format strings in some locations. Follow the suggestions and fix some other issues flagged by newer versions of clippy.
> Fix clippy reported issues

- .github/workflows/ci.yml
- Cargo.toml
- build.rs
- src/lib.rs
The `cbindgen` dependency pulls in a swath of transitive dependencies. Currently, everybody compiling the crate pays the price of compiling all of them, while the dependency is really only used when generating C headers.
With this change we pull in the dependency only when generating C headers, eliminating that work when it is unnecessary.
> Make cbindgen dependency optional

- src/dwarf.rs
- src/elf/parser.rs
- src/gsym/parser.rs
Our pointer casts assume char to signed, which isn't guaranteed:
>    --> src/elf/parser.rs:475:40
>     |
> 475 |                         CStr::from_ptr(&strtab[str2symtab[idx].0] as *const u8 as *const i8)
>     |                         -------------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
>     |                         |
>     |                         arguments to this function are incorrect
>     |
>     = note: expected raw pointer `*const u8`
>                found raw pointer `*const i8`
Fix them.
> Fix pointer casts

- .github/workflows/ci.yml
- Cargo.toml
- build.rs
Cargo build scripts can't distinguish between building the "core" library and building tests. For that reason, we decided to make test file generation opt-out.
It turns out there actually is a way to approximate the desired behavior of building test files when testing very closely and it is outlined in the corresponding upstream feature request:
https://github.com/rust-lang/cargo/issues/2911
Basically, we declare blazesym as a dev-dependency of itself with the feature in question enabled.
With this change we do just that for the newly introduced generate-test-files feature. That means test file generation is now opt-in for regular builds, unless tests or examples are also build, in which case it will default to being enabled. For that reason, we keep the dont-generate-test-files feature …
> Enable test file generation when building tests

- src/c_api.rs
- src/lib.rs
It is bad practiced to accept a Vec object in a function that does not actually need to consume it. Work with slices instead.
> Accept slices instead of vectors

- .rustfmt.toml
- Cargo.toml
- examples/addr2ln.rs
- examples/addr2ln_pid.rs
- src/c_api.rs
- src/dwarf.rs
- src/dwarf/debug_info.rs
- src/elf/cache.rs
- src/elf/parser.rs
- src/elf/resolver.rs
- src/elf/types.rs
- src/gsym/linetab.rs
- src/gsym/parser.rs
- src/gsym/resolver.rs
- src/ksym.rs
- src/lib.rs
- src/util.rs
With these changes, performance as measured with https://github.com/danielocfb/blazesym-benchmarks/tree/main improved as follows:
```
dwarf/lookup_end_to_end time:   [76.340 ms 76.791 ms 77.263 ms]
change: [-29.818% -29.285% -28.736%] (p = 0.00 < 0.02)
Performance has improved.
dwarf/symbolize_end_to_end
time:   [15.305 ms 15.397 ms 15.488 ms]
change: [-13.251% -12.452% -11.686%] (p = 0.00 < 0.02)
Performance has improved.
```
(~29% improvement for symbolization and ~12% improvement for reverse symbolization [lookup]; note that these numbers include the necessary setup, which includes IO and cache population etc., which is really what is modified here)
These results are for a ~700 MiB kernel image with debug information.
On top of that it …
> Use memory mapping and zero-copy parsing

- src/elf/parser.rs
The zeroth ELF section index seems to be reserved and will never contain a valid section. From elf(5):
> A section header table index is a subscript into this array. Some
> section header table indices are reserved: the initial entry and the
> indices between SHN_LORESERVE and SHN_HIRESERVE.  The initial entry
> is used in ELF extensions for e_phnum, e_shnum, and e_shstrndx; in
> other cases, each field in the initial entry is set to zero.
We do not have to check it when trying to find a section by name.
> Start ELF section search at index one

- tests/blazesym.rs
A recent commit added an end-to-end test for symbolizing an address using DWARF debug information. This change introduces another test for the reverse operation: retrieving an address for a symbol.
Note that our GSYM resolver currently does not support such a lookup, which is why we cannot add a test for this format.
> Add end-to-end test for DWARF symbol lookup

- codecov.yml
We are seeing loads of code coverage annotations on pull requests for files that weren't even touched by said PR, e.g., [here][0]. This change introduces a configuration that hopefully [1] disables the feature.
[0]: https://github.com/libbpf/blazesym/pull/75/commits/57522fcd16a27461cd436cce7de5026e7acecd28
[1]: https://docs.codecov.com/docs/github-checks#disabling-github-checks-patch-annotations-via-yaml
> Disable Codecov file annotations

- benches/gsym.rs
- benches/main.rs
- build.rs
This change adds an end-to-end benchmark using the gsym resolver. As for DWARF, we work on data from a vmlinux image.
> Add gsym end-to-end symbolization benchmark

- src/ksym.rs
- src/lib.rs
If we have a constant representing the default path of /proc/kallsyms, we probably should use everywhere the path is needed and not just half the time.
> Use KALLSYMS constant in more places

- src/dwarf/resolver.rs
- src/elf/parser.rs
- src/ksym.rs
- src/lib.rs
It makes no sense whatsoever to implement `Default` for a type that does not have any logical default value, such as `SymbolInfo`. Remove it.
> Remove Default impl for SymbolInfo

- Cargo.toml
- src/elf/cache.rs
Use the lru crate for the LRU cache functionality we currently have in place instead of hand rolling our own.
> Use lru crate for LRU cache functionality

- src/elf/resolver.rs
- src/gsym/resolver.rs
- src/ksym.rs
- src/lib.rs
It makes little sense to have the SymResolver::repr() method when we could equally well just implement Debug/Display, which is Rust's built-in functionality for accomplishing the same. Require the former and remove SymResolver::repr().
> Remove SymResolver::repr() method

- .rustfmt.toml
- examples/addr2ln.rs
- examples/addr2ln_pid.rs
- src/c_api.rs
- src/dwarf/debug_info.rs
- src/dwarf/parser.rs
- src/dwarf/resolver.rs
- src/elf/cache.rs
- src/gsym/parser.rs
- src/gsym/resolver.rs
- src/ksym.rs
- src/lib.rs
- src/util.rs
The
>  use <...>::{XXX, YYY, ZZZ}
style for `use` statements is causing merge conflicts all over the place, making it extremely cumbersome to have multiple pull requests in flight. Switch to a different style that is less prone to such issues.
> Use single line use statements

- Cargo.toml
- src/elf/cache.rs
- src/elf/parser.rs
- src/lib.rs
- src/util.rs
Some of our users are troubled by the number of dependencies we have. This pull requests eliminates the `nix` dependency, replacing it with alternatives from `libc` (around which `nix` is only a thin wrapper anyway, for the most part).
> Eliminate nix dependency

- Cargo.toml
- src/elf/parser.rs
- src/lib.rs
- src/mmap.rs
This change removes the memmap dependency, replacing it with direct usage of libc primitives instead.
> Eliminate memmap dependency

- Cargo.toml
- src/dwarf/parser.rs
- src/dwarf/resolver.rs
We have some limited support for doing DWARF parsing with multiple threads in debug_info_parse_symbols(), but it is not currently used anywhere but tests/benchmarks. I adjusted the resolver to use four instead of only a single thread but performance of our end-to-end test was unaffected:
```
dwarf/dwarf :: lookup_end_to_end
time:   [38.452 ms 38.729 ms 39.055 ms]
change: [+0.4597% +1.5175% +2.5883%] (p = 0.00 < 0.02)
Change within noise threshold.
Found 50 outliers among 500 measurements (10.00%)
24 (4.80%) high mild
26 (5.20%) high severe
dwarf/dwarf :: symbolize_end_to_end
time:   [7.8156 ms 7.8725 ms 7.9420 ms]
change: [-0.7813% +0.0273% +0.9428%] (p = 0.95 > 0.02)
No change in performance detected.
Found 43 outliers among 500 measurements (8.60%)
16 (3.20%) high mild
27 (5.40%) high …
```
> Remove multi-threading support

- src/lib.rs
A bunch of "stack session" logic, supposedly in support of stack unwinding, is currently unused. Remove it until we may or may not need it again.
> Remove unused "stack session" logic

- README.md
- cbindgen.toml
- examples/addr2ln.rs
- examples/addr2ln_pid.rs
- include/blazesym.h
- src/c_api.rs
- src/dwarf/parser.rs
- src/dwarf/resolver.rs
- src/elf/parser.rs
- src/elf/resolver.rs
- src/gsym/linetab.rs
- src/gsym/parser.rs
- src/gsym/resolver.rs
- src/ksym.rs
- src/lib.rs
- src/maps.rs
We mix `u64` and `usize` usage for representing addresses. This change introduces the `Addr` typedef that is to be used moving forward. We define that to map to usize, which is a machine word, which, on all but exotic systems, equals the address size (C additionally has `uintptr_t` for that purpose, but Rust decided not to have that and maps everything to `usize`).
I adjusted all usage that I could identify. Everything I missed can be cleaned up over time.
> Introduce and use Addr typedef

- .gitignore
- Cargo.toml
- build.rs
- src/lib.rs
- src/zip.rs
Introduce zip reading support. We use our own bespoke implementation to keep dependencies low. That's a requirement for one of our consumers.
The final set of APIs is subject to change as we better understand our use cases. For now this is a pretty straight forward translation of the corresponding C logic.
> Add zip reading support

- src/dwarf/resolver.rs
- src/elf/parser.rs
- src/lib.rs
FindAddrOpts is not meant to be used outside of the crate. Stop exporting it.
> Make FindAddrOpts internal

- benches/dwarf.rs
- src/c_api.rs
- src/lib.rs
- tests/blazesym.rs
Similar to what we did earlier for the symbolization paths, this change adjusts `BlazeSymbolizer::find_addresses()` to return a `Result`.
> Make BlazeSymbolizer::find_addresses() return a Result

- .github/workflows/test.yml
This change adds CI jobs for testing with ASAN and LeakSAN enabled. Doing so can help detect various issues.
> Run address and leak sanitizers on tests

- cbindgen.toml
- include/blazesym.h
Before commit 5e8b4edbbe37 ("Remove unnecessary indirection in blazesym C type") the C API type blazesym could be used as `struct blazesym`, but that no longer works, because the underlying typedef changed. By telling cbindgen to export BlazeSymbolizer as blazesym we can restore the original behavior.
> Export BlazeSymbolizer as blazesym in C API

- build.rs
- src/dwarf/debug_info.rs
We currently may end up panicking the calling thread when encountering DWARF v5 unit header debug information, which we currently do not support. This is not great behavior in many production contexts. With this change we ignore DWARF v5 compile units during iteration, rather than panicking. While at it, remove needless recursion from `UnitIter::next`.
> Do not panic when encountering DWARF v5 unit headers

- src/elf/parser.rs
Remove a bunch of unnecessary allocations when looking up addresses for symbols.
> Remove unnecessary allocations

- src/elf/resolver.rs
It's unclear why `ElfResolver::get_parser()` returns an `Option` when all it ever does it return the `Some` variant of it. Remove the `Option` wrapper.
> Make ElfResolver::get_parser() return ElfParser directly

- README.md
- examples/addr2ln.rs
- examples/addr2ln_pid.rs
- src/c_api/symbolize.rs
- src/symbolize.rs
This change converts the SymbolizedResult::path member from a String to a PathBuf.
> Make SymbolizedResult::path member a PathBuf

- include/blazesym.h
- src/c_api/normalize.rs
We missed tagging `blaze_user_addr_meta_binary` and
`blaze_user_addr_meta_unknown` with `repr(C)` and so they didn't get picked up by `cbindgen`. Do that now.
> Expose blaze_user_addr_meta* types in C API

- README.md
- benches/dwarf.rs
- benches/gsym.rs
- examples/addr2ln.rs
- examples/addr2ln_pid.rs
- include/blazesym.h
- src/c_api/symbolize.rs
- src/resolver.rs
- src/symbolize.rs
- tests/blazesym.rs
- tests/c_api.rs
There is not much of a point in passing a set of symbol sources/configurations to a symbolize call. Rather, it only complicates a bunch of things, from the API to the various internals. For one, now we need to create this "resolver map" in order to find the "correct" resolver to use. That in turn requires each resolver to know the range it covers -- which it otherwise would not have to. It also means that users are asked to provide a base address for sources such as gsym or ELF.
With this change we only accept a single symbol source/configuration and adjust all APIs accordingly.
> Make symbolize call only take a single symbol source/configuration

- tests/blazesym.rs
This change introduces a test for the process symbolization functionality. The test symbolizes two addresses in the current process.
> Add test for process symbolization

- benches/main.rs
- benches/symbolize.rs
This change introduces a benchmark for the process symbolization functionality. The benchmark measures end-to-end times for the symbolization of five addresses inside the current process.
```
> Benchmarking main/symbolize :: symbolize_process: Collecting 500 samples in estimated 5.
> main/symbolize :: symbolize_process
>     time:   [970.41 µs 970.62 µs 970.89 µs]
```
> Add benchmark for process symbolization

- benches/normalize.rs
- include/blazesym.h
- src/c_api/normalize.rs
- src/normalize/mod.rs
- src/normalize/normalize.rs
- tests/blazesym.rs
- tests/c_api.rs
> Add suport for unsorted normalization of addresses

- .github/workflows/test.yml
We do not currently have a suppression file and so if we were to have a leak in our code, LSAN would attempt to open the non-existent lsan-suppressions.txt file and fail. Remove this option.
> Remove suppression file usage from LSAN CI run

- src/lib.rs
The debug macro currently shows up in the user facing documentation. It is meant to be an implementation detail. Make it so.
> Remove logging macros from documentation

- src/c_api/normalize.rs
Code coverage numbers are still pretty bad. They are also extremely wrong, reporting entire functions as uncovered, that absolutely have test coverage (including tests dedicated solely to them!). Some conversions, however, are not covered explicitly (though they may be exercised implicitly). But just to be certain, add tests.
> Add a few trivial tests to increase code coverage

- .github/workflows/test.yml
We missed explicitly installing the most recent Rust for the coverage job. That resulted in us using the Ubuntu default Rust toolchain. Especially for code coverage, it can pay off to use the most recent Rust version, which uses more up-to-date LLVM toolchains, which in turn may provide better coverage instrumentation. In fact, code coverage still works best on nightly, so switch to using a nightly toolchain for this job.
> Use nightly Rust for code coverage job

- src/maps.rs
Add two more assertions to our tests in order to gain to more lines of code coverage.
> Add assertions to cover two more lines

- src/maps.rs
This change adds another test for the proc maps parsing functionality that exercises a couple of error paths, for increased code coverage.
> Add another test to increase code coverage

- benches/dwarf.rs
- benches/gsym.rs
- benches/symbolize.rs
- examples/addr2ln.rs
- examples/addr2ln_pid.rs
- src/c_api/symbolize.rs
- src/lib.rs
- src/resolver.rs
- src/symbolize/source.rs
- src/symbolize/symbolizer.rs
- tests/blazesym.rs
Make sure that potential additions to our symbol source types are not breaking changes by making the structs non-exhaustive.
> Make symbolization source types non-exhaustive

- include/blazesym.h
- src/c_api/symbolize.rs
- src/resolver.rs
- src/symbolize/source.rs
- src/symbolize/symbolizer.rs
- tests/c_api.rs
The "file name" terminology is misleading, we are working with paths.
> Rename symbolize::{Elf,Gsym}::file_name to path

- README.md
Fix the link to the blazesym.h header in the README by using the parentheses instead of square brackets.
> Fix link to blazesym.h header in README

- Cargo.toml
- examples/addr2ln.rs
- examples/addr2ln_pid.rs
The addr2ln* examples currently just unwrap. Let's perform some more graceful error handling there.
> Use more graceful error reporting in addr2ln* examples

- src/c_api/inspect.rs
- src/dwarf/parser.rs
- src/dwarf/resolver.rs
- src/elf/parser.rs
- src/elf/resolver.rs
- src/gsym/resolver.rs
- src/inspect/inspector.rs
- src/inspect/mod.rs
- src/kernel.rs
- src/ksym.rs
- src/normalize/normalizer.rs
- src/resolver.rs
- src/symbolize/symbolizer.rs
Rename Symbol{Info,Type} to Sym{Info,Type}. We use abbreviated addr and sym (the latter also being contained in the moniker of the library), so shorten the type names accordingly.
> Rename Symbol{Info,Type} -> Sym{Info,Type}

- benches/dwarf.rs
- benches/gsym.rs
- benches/symbolize.rs
- examples/addr2ln.rs
- examples/addr2ln_pid.rs
- include/blazesym.h
- src/c_api/inspect.rs
- src/c_api/symbolize.rs
- src/lib.rs
- src/symbolize/mod.rs
- src/symbolize/symbolizer.rs
- tests/blazesym.rs
- tests/c_api.rs
Inspector and Normalizer constructors are infallible. Change Symbolizer ones to mirror that behavior.
> Make Symbolizer constructors infallible

- src/c_api/mod.rs
- src/inspect/mod.rs
- src/lib.rs
- src/normalize/mod.rs
- src/symbolize/mod.rs
- tests/blazesym.rs
This change extends the documentation with an overview of the crate, more examples, and a bunch of explanations of the public modules.
> Extend documentation some more

- Cargo.toml
- README.md
This change bumps the version of the crate to `0.2.0-alpha.0`, marking an early access release for version `0.2.0`. Minor changes in the API are still to be expected before `0.2.0` (particularly to the C API), but in large parts we believe to be there.
> Bump version to 0.2.0-alpha.0

- examples/addr2ln.rs
- examples/addr2ln_pid.rs
Simplify our two examples some more, by using combinators instead of hand-crafted prefix removal logic.
> Simplify examples some more

- include/blazesym.h
- src/c_api/symbolize.rs
- src/dwarf/debug_info.rs
Let's rename the few usages of BlazeSym to blazesym.
> Rename BlazeSym -> blazesym

- Cargo.toml
Replace the 'symbolization' keyword in Cargo.toml with 'stacktrace', as per earlier discussion [0].
[0]: https://github.com/libbpf/blazesym/pull/156#discussion_r1185584238
> Swap 'symbolization' keyword with 'stacktrace'

- CHANGELOG.md
- README.md
- src/c_api/inspect.rs
- src/inspect/mod.rs
This change fixes a wrong allocation size calculation, potentially causing too small a buffer to be allocated, resulting in out-of-bounds writes when looking up symbol information from names using the C API. Thanks @anakryiko for spotting the issue!
> Fix incorrect allocation size calculation

- include/blazesym.h
- src/c_api/symbolize.rs
- src/elf/resolver.rs
- src/gsym/parser.rs
- src/gsym/resolver.rs
- src/inspect/inspector.rs
- src/kernel.rs
- src/ksym.rs
- src/resolver.rs
- src/symbolize/source.rs
- src/symbolize/symbolizer.rs
- tests/blazesym.rs
- tests/c_api.rs
Now that we have removed the Symbolizer::find_addrs functionality with commit c504b0fefc9d ("Remove no longer used functionality"), we no longer use or need the base_address that is still a member of a bunch of types. Remove it, as it was never a sustainable concept to work with.
> Remove concept of base_address

- CHANGELOG.md
This change adds a CHANGELOG entry for the changes made by https://github.com/libbpf/blazesym/pull/165.
> Add CHANGELOG entry for recent changes

- CHANGELOG.md
- benches/inspect.rs
- include/blazesym.h
- src/c_api/inspect.rs
- src/dwarf/parser.rs
- src/dwarf/resolver.rs
- src/elf/parser.rs
- src/inspect/inspector.rs
- src/inspect/mod.rs
- src/ksym.rs
- src/normalize/normalizer.rs
- tests/blazesym.rs
- tests/c_api.rs
Rename the `SymInfo::address` member to `addr`, in pursuit of our aim of
using short hand "addr" throughout the crate eventually.
> Rename SymInfo::address to addr

- .github/workflows/publish.yml
- CHANGELOG.md
- Cargo.toml
- README.md
This change bumps the version of the crate to 0.2.0-alpha.1. As part of the bump, add logic for creating a GitHub release to the publish workflow.
> Bump version to 0.2.0-alpha.1

- .github/workflows/publish.yml
This change adds version detection logic to the publish workflow, which will enable creation of the correct git tag names from said workflow.
> Add version detection logic to publish workflow

- src/elf/parser.rs
- src/normalize/normalizer.rs
The `ElfParser::from_mmap()` constructor can't error out. Remove the theoretical error return path by dropping the `Result` from the return type.
> Make ElfParser::from_mmap() infallible

- .github/workflows/test.yml
Make sure to invoke `cargo-llvm-cov` with the `--all-targets` option to collect code coverage on all eligible targets. Doing so seems to include the running of benchmarks (in "test mode"), which has the potential to bump our coverage numbers, in addition to simply being the right thing to do (tm).
> Invoke `cargo-llvm-cov` with `--all-targets`

- include/blazesym.h
- src/c_api/normalize.rs
The documentation for the `blaze_user_addrs_free` function states that addresses should have been allocated by `blaze_normalized_user_addrs`, but then mentions that for safety they should come from `blaze_normalize_user_addrs_sorted`.
Mention both functions in both contexts for completeness and to avoid unnecessary confusion.
> Fix some confusion in C API documentation

- CHANGELOG.md
- cbindgen.toml
- include/blazesym.h
C++ code is free to use blazesym.h, but currently they need the "usual" `extern "C"` block around the include.
Instruct bindgen to take care of that transparently as part of the header generation, to lift this burden of all C++ users.
> Create C++ compatible header

- CHANGELOG.md
- Cargo.toml
- build.rs
- include/blazesym.h
- src/c_api/normalize.rs
Apparently it is *illegal* to have an empty struct in C. gcc seems to fudge over that with a compiler specific hack [0]. Be that as it may, during integration into a C++ code base we noticed an error showing up:
> empty struct has size 0 in C, size 1 in C++ [-Werror,-Wextern-c-compat]
While we cannot, for the love of it, reproduce that problem in an isolated manner, make sure to add an unused member to the type in questions. Also compile a C++ program, not that it would have caught this issue, but it's probably better than nothing.
[0] https://gcc.gnu.org/onlinedocs/gcc/Empty-Structures.html
> Add unused member to blaze_user_addr_meta_unknown struct

- src/elf/parser.rs
Let's provide some more information when seeing an e_ident mismatch, by including the actual data in the error.
> Print e_ident on mismatch

- CHANGELOG.md
- include/blazesym.h
- src/c_api/inspect.rs
The blaze_inspect_elf_src::path member currently can be mutated by C code. That's not exactly the intention. Because it is mutable it also prevents legitimate assignments of a *const _.
The reason for it being mutable in the first place was mostly because that's what Rust APIs used in the implementation work with. However, we should not expose this property.
To that end, this change adjusts the type from *mut _ to *const _.
> Make blaze_inspect_elf_src::path a *const _

- .gitignore
- CHANGELOG.md
- Cargo.toml
- build.rs
- data/vmlinux-5.17.12-100.fc34.x86_64.xz
Git LFS turned out to be not exactly suitable for our intents and purposes. Most importantly, GitHub's LFS imposes a fixed, non-replenishable bandwidth limit (which includes downloads...) on the uploader. Second, because of the way it works, once installed on the system, by default downloading will happen as part of clone/checkout. Neither "qualities" are particularly appealing to us. With this change we move large binary blobs away from LFS and into a separate repository. Because GitHub has a 100 MiB file size limit, we split files accordingly. Our build script contains the logic for downloading all parts and piecing them back together. All of this is controlled by the generate-bench-files features, unchanged.
> Stop using Git LFS for large benchmark files

- src/normalize/mod.rs
- src/normalize/normalizer.rs
- src/symbolize/symbolizer.rs
- src/util.rs
> Use internal APIs in process symbolization

- CHANGELOG.md
- Cargo.toml
- README.md
This change bumps the version of the crate to `0.2.0-alpha.2`.
> Bump version to `0.2.0-alpha.2`

- Cargo.toml
- src/elf/cache.rs
- src/elf/mod.rs
- src/elf/resolver.rs
- src/inspect/inspector.rs
- src/inspect/mod.rs
- src/lib.rs
With upcoming changes we will use gimli for providing DWARF support, instead of hand rolling DWARF parsing and state machine handling. Some users may not need such support and/or don't want this additional dependency.
Hence, make it optional by introducing the (default enabled) `dwarf` feature.
> Make DWARF support optional

- src/dwarf/parser.rs
- src/dwarf/resolver.rs
The `cond` argument to the debug_info_parse_symbols() function is always `None`. Remove it.
> Remove `cond` argument from debug_info_parse_symbols() function

- Cargo.toml
The debug_info_parse_single_threaded() benchmark requires debug information to be present in the benchmark binary or it won't do much. Make sure to enable it.
> Bench with debug information present

- .github/workflows/test.yml
- build.rs
Our various test and benchmark artifacts are created repeatedly on every build. While not a noticeable slowdown at this point, it's unnecessary work and, over time, the cause of wear for SSDs, for example.
The problem seems to be that the generated files' mtimes are after those of Cargo's output file that they are compared against to determine staleness. This behavior is counter-intuitive: it is the build script that emits those outputs to stdout while also generating those files. Hence, the build script's outputs can only be available completely after said script has run (that is, after the files have been generated as well). Alas, this behavior seems to be fully intentional from the Cargo side [0].
With this change we work around this problem, by adjusting generated files' time stamps …
> Eliminate unnecessary rebuilds in build script

- README.md
We should add support for looking up inlined functions from DWARF. Put that on the roadmap in the README.
> Put inlined function lookup on roadmap

- src/dwarf/parser.rs
- src/dwarf/resolver.rs
- src/elf/parser.rs
- src/util.rs
In the standard library, sort/find *_by functions generally accept a closure that returns an `Ordering` (e.g., [0]). That's not the case for our `find_match_or_lower_bound_by`. Rather, it better mimics the signature of *_by_key variants. Rename it accordingly.
[0] https://doc.rust-lang.org/std/primitive.slice.html#method.binary_search_by
> Rename find_match_or_lower_bound_by to find_match_or_lower_bound_by_key

- src/elf/parser.rs
- src/elf/resolver.rs
- src/gsym/resolver.rs
- src/kernel.rs
- src/ksym.rs
- src/resolver.rs
- src/symbolize/symbolizer.rs
Rename the `SymResolver::find_symbols()` method to `find_syms`, to be more in line with the naming established throughout the crate.
> Rename SymResolver::find_symbols() to find_syms

- src/elf/parser.rs
- src/elf/resolver.rs
Similar to what we did in commit cf14376d6796 ("Adjust return type of ElfParser::find_section()"), adjust the return value of `ElfParser::find_sym` to handle the symbol-not-found case via an `Option` instead of fudging everything with a true error.
> Adjust return type of ElfParser::find_sym()

- build.rs
- data/test-stable-addresses.c
- src/gsym/parser.rs
- src/gsym/resolver.rs
- tests/blazesym.rs
- tests/c_api.rs
This change renames the `data/test.gsym` file to
`test-stable-addresses.gsym`, which is a tad more expressive.
> Rename data/test.gsym -> test-stable-addresses.gsym

- build.rs
- src/dwarf/resolver.rs
- src/elf/parser.rs
- src/elf/resolver.rs
- tests/blazesym.rs
- tests/c_api.rs
Rename more test files to include "stable-addresses" in their name, if they are derived from the corresponding source code file. Also, use "no-dwarf" variants when testing ELF logic specifically.
> Rename more test files

- README.md
Link the issue/task concerned with the addition of support for debuginfod from the roadmap so that it can be discovered more easily.
> Link to task for `debuginfod` work

- .cargo/config
- .cargo/runner.sh
- Cargo.toml
- benches/inspect.rs
- benches/normalize.rs
- benches/symbolize.rs
- src/dwarf/parser.rs
- src/util.rs
Improve benchmarking mechanics a bit by:
1) compiling with LTO enabled and -O3
2) increasing niceness values of benchmarks
3) flushing system caches before running
4) make sure to use std::hint::black_box in the hope that it prevents
too many optimizations specific to the benchmark and not generally
applicable
Note that 2) & 3) require root, but we already require that anyway, so there is no impact.
> Improve benchmark mechanics

- src/elf/parser.rs
- src/util.rs
The `ElfParser::find_sym()` method uses rather convoluted and untested `search_address_opt_key()` function to search for a symbol. We should be able to accomplish the same result by just using our lowest match search to find the first symbol with a given address, and then perform a linear scan to eliminate candidates that don't fit the expected for type.
> Use lowest match search in ElfParser::find_sym()

- src/dwarf/resolver.rs
- src/elf/resolver.rs
- src/gsym/resolver.rs
- src/kernel.rs
- src/ksym.rs
- src/resolver.rs
- src/symbolize/symbolizer.rs
Finding of line information cannot possibly be an infallible operation. Adjust its signature accordingly.
> Adjust SymResolver::find_line_info() to return Result

- src/elf/parser.rs
- src/elf/types.rs
As per review comment [0], introduce and use a helper function for extracting an ELF symbol's type.
[0] https://github.com/libbpf/blazesym/pull/200#discussion_r1220102437,
> Introduce Elf64_Sym::type_() helper

- src/elf/resolver.rs
- src/gsym/resolver.rs
- src/kernel.rs
- src/ksym.rs
- src/resolver.rs
Finding of symbol information for an address cannot in general possibly be an infallible operation. Adjust its signature accordingly.
> Adjust SymResolver::find_addr() to return Result

- src/ksym.rs
The `/proc/kallsyms` virtual file is commonly available. However, depending on kernel configuration all symbols may be reported as `0` for regular users.
Starting with commit 327f2884205d ("Use /proc/[pid]/map_files") we run our tests as root, so this should no longer a limitation that affects us. Hence, enable the main `KSymResolver` test again.
> Un-ignore main KSymResolver test

- src/zip.rs
Using the `Debug` impl on a `zip::Entry` can result in lots of log/terminal spew, because the type contains a slice of the raw data belonging to the entry.
Provide a custom `Debug` impl that only prints the first 32 bytes of the data to circumvent this problem.
> Provide custom `Debug` impl for `zip::Entry`

- src/zip.rs
The newly added custom Debug impl for zip::Entry is showing up as a bunch of uncovered lines. Add a test for it to rectify. And fix it up for small data fields.
> Add test for zip::Entry Debug impl

- tests/blazesym.rs
Use the `Symbolizer::default()` way of constructing a `Symbolizer` object so that we can claim coverage for this path.
> Use Symbolizer::default() constructor

- CHANGELOG.md
- build.rs
- include/blazesym.h
- src/c_api/inspect.rs
- src/c_api/normalize.rs
- src/c_api/symbolize.rs
- src/lib.rs
- src/mmap.rs
- src/normalize/meta.rs
- src/normalize/mod.rs
- src/normalize/normalizer.rs
- src/symbolize/symbolizer.rs
- src/zip.rs
- tests/blazesym.rs
This change renames the Binary meta data variant to Elf. For the time being we decided to err on the side of having more specific variants, which may be easier to extend in a sensible way in the future (e.g., if future supported binary formats don't have a build ID it's more natural to have a new variant as opposed to fudging everything as a "binary" and then having optional fields).
> Rename Binary meta data variant to Elf

- build.rs
On a system that is configured to not emit build IDs by default we fail the `address_normalization_custom_so_in_zip()` test, which assumes build IDs present in both `libtest-so.so` and `libtest-so-no-separate-code.so`. Make sure that the latter also contains a build ID.
> Build libtest-so-no-separate-code.so with build ID

- src/symbolize/source.rs
We may end up including symbolize::Process objects in traces. Right now their Debug representation is very verbose, making said traces unnecessarily hard to read.
This change provides a custom Debug impl that shortens the output reasonably.
Refs: #223
> Provide custom Debug impl for symbolize::Process

- src/elf/resolver.rs
- src/gsym/resolver.rs
- src/kernel.rs
- src/ksym.rs
- src/resolver.rs
- src/symbolize/symbolizer.rs
As the 100th method that just swallows errors when it feels like it, this change converts SymResolver::find_syms() to correctly bubble up errors.
> Make SymResolver::find_syms() return a Result

- src/symbolize/mod.rs
This change updates the example we provide as part of the documentation for the symbolize module to something that can be run properly. Right now it requires root, but we could change that eventually.
> Provide runnable example for symbolize module

- CHANGELOG.md
- README.md
- src/normalize/meta.rs
- src/normalize/mod.rs
- src/normalize/normalizer.rs
- src/symbolize/symbolizer.rs
> Streamline APK ELF build ID retrieval

- src/elf/resolver.rs
- src/gsym/resolver.rs
- src/inspect/inspector.rs
- src/kernel.rs
- src/ksym.rs
- src/resolver.rs
We don't really want to require association of a file name with a resolver. It is entirely reasonable to have a resolver that just works on allocated/mmap'ed data that was just handed to us and for which we don't (and in the general case: cannot) know what file it belongs to.
We don't really need the method. Inside the `Inspector` we can just use the path being provided and used for instantiation of the corresponding resolvers, and elsewhere we just use the file name to spice up the debug representation or similar. Remove it.
> Remove SymResolver::get_obj_file_name() method

- codecov.yml
Codecov coverage reporting is unstable, most likely due to https://github.com/taiki-e/cargo-llvm-cov/issues/276. In any event, we do not want to gate pull requests by changes in coverage. Run it in informational mode [0] instead.
[0]: https://docs.codecov.com/docs/commit-status#informational
> Use codecov in informational mode

- include/blazesym.h
- src/c_api/normalize.rs
C/C++ reserves double underscore identifiers. So what can potentially happen is that `__unused` is really the name of a macro (expanding to `__attribute__((unused))` or similar) and that causes a compile error, because now the variable has no name.
Rename the `blaze_user_addr_meta_unknown::__unused` member to `_unused` to prevent such issues from popping up.
Reported-by: Salvatore Benedetto
> Rename `blaze_user_addr_meta_unknown::__unused` member to `_unused`

- include/blazesym.h
- src/c_api/normalize.rs
The documentation for the normalization APIs of the C bindings mixed up wording for the blaze_normalize_user_addrs and
blaze_normalize_user_addrs_sorted variants. Fix it.
Reported-by: Salvatore Benedetto
> Fix documentation of normalization API in C API

- src/normalize/normalizer.rs
As of commit 06ef89ff67aa ("Make normalize functionality use Pid") the normalize functions no longer accept a u32 process ID, but rather a Pid object.
With this change we adjust the documentation accordingly.
> Reword process ID documentation for normalize functions

- src/normalize/normalizer.rs
When normalizing addresses, we expect to always report as many normalized addresses as we got as input. Check that with an assertion.
> Check that normalized addresses match input addresses

- src/normalize/mod.rs
The documentation of the normalize module contains example code but the way it is written it causes overly long lines in the documentation, requiring people to scroll horizontally. That's not particularly nice. Wrap those long lines earlier to improve the situation.
> Wrap overly long documentation lines in normalize module

- src/c_api/inspect.rs
- src/c_api/normalize.rs
It's conceptually fine for members of struct types exposed via the C API to be private -- bindgen picks them up no matter what and C doesn't care. However, if they are private they don't show up in the documentation, which is not a great experience.
Make all C API struct members public to expose them in the documentation. Unfortunately there does not seem to exist any flag to raise an error on the cbindgen side for non-public members, so I suppose this whack-a-mole is all we can do.
> Publicize a couple of C API struct members

- include/blazesym.h
- src/c_api/normalize.rs
- src/normalize/normalizer.rs
The documentation explains the expectations of the *_sorted normalization function variants, but doesn't really explain the relevance or why one would prefer one over the other. Explain it a bit more.
> Provide rationale for *_sorted normalization APIs

- CHANGELOG.md
Add a CHANGELOG entry for the blaze_user_addr_meta_unknown::__unused member rename, as it could be considered a breaking change.
> Add CHANGELOG entry for blaze_user_addr_meta_unknown::__unused rename

- src/ksym.rs
`/proc/kallsyms` may not be present on some systems. Skip `ksym_resolver_load_find` in that case.
> Skip ksym_resolver_load_find test if `/proc/kallsyms` is not present

- src/normalize/buildid.rs
- src/normalize/mod.rs
- src/normalize/normalizer.rs
Let's move the build ID functionality into a separate module, to improve code organization.
> Move build ID functionality into separate module

- src/normalize/mod.rs
- src/normalize/normalizer.rs
- src/normalize/user.rs
With upcoming changes we will introduce support for normalizing kernel addresses. Given that it's mostly independent of the existing normalization functionality, let's introduce a bit of a split between logic concerned with user address normalization and that for kernel address normalization.
Start by moving most bits pertaining user address normalization into a new sub-module, user.
> Move user address normalization into separate module

- src/c_api/inspect.rs
- src/c_api/normalize.rs
- src/c_api/symbolize.rs
Code coverage is highlighting a bunch of "red" on the #[derive(Debug)] annotations on the various C API symbolize types. Add tests for them.
> Add "test" for Debug representation of various C API symbolize types

- CHANGELOG.md
- src/error.rs
- src/inspect/inspector.rs
- src/lib.rs
- src/maps.rs
- src/normalize/buildid.rs
- src/normalize/normalizer.rs
- src/normalize/user.rs
- src/symbolize/symbolizer.rs
- src/util.rs
- tests/blazesym.rs
So far the crate has used `std::io::Error` as its error type. It is sufficient for the most part, but it's not optimal long-term:
- by not abstracting it we are not very flexible once we need additional "kinds" or variants in the future
- that also applies to features such as capturing of backtraces at time of error
- because it is defined outside of our crate, certain usability limitations may be imposed on us
- io::Error does not lend itself to proper error chaining and that will make it harder to contextualize errors as the code base grows
To fix these issues, this change introduces a new public error type. The type is still very close to `io::Error`, just by virtue of us doing a lot of IO and so it is a natural fit. We certainly mirror several of the `std::io::ErrorKind` variants in …
> Introduce custom Error type

- src/dwarf/resolver.rs
- src/elf/cache.rs
- src/elf/parser.rs
- src/gsym/parser.rs
- src/gsym/resolver.rs
- src/resolver.rs
- src/util.rs
Use the io::Result typedef instead of Result<T, io::Error> throughout the elf::parser module.
> Use io::Result in elf::parser module

- src/dwarf/mod.rs
- src/dwarf/parser.rs
- src/dwarf/reader.rs
This change moves the `R` typedef and associated functionality into the newly introduced `dwarf::reader` module.
> Factor out `R` typedef into `dwarf::reader` module

- CHANGELOG.md
- Cargo.toml
- README.md
This change bumps the version of the crate to `0.2.0-alpha.3`.
> Bump version to `0.2.0-alpha.3`

- Cargo.toml
- benches/inspect.rs
- benches/symbolize.rs
- build.rs
With upcoming changes we would like to use the kernel image that we have used only for benchmarking so far for regression testing as well. As such, the generate-bench-files switch controlling the download of said kernel image and generation of derived files is no longer aptly named. Rename it to generate-large-test-files in anticipation of the new usage.
> Rename generate-bench-files feature to generate-large-test-files

- .github/workflows/test.yml
- Cargo.toml
- benches/main.rs
- build.rs
In the past we used Git LFS for retrieving large benchmark files and we didn't want to waste upload/download bandwidth on every CI run. In addition, we never intended to rely on CI benchmarks, for they are running in a virtualized and generally unreliable (in terms of consistent performance) environment.
Despite that, given that by now we switched to pulling said files from a GitHub hosted Git repository with commit 80f35dada75b ("Stop using Git LFS for large benchmark files"), it is still somewhat interesting to have all benchmarks run in CI, because even if the numbers are not particularly, it could be used to identify trends over time or to notice outrageous regressions more timely.
With this change we enable running of all benchmarks in CI. We cache all Rust build artifacts for this …
> Run all benchmarks in CI

- .github/workflows/test.yml
With this change we include the benchmark results in the CI workflow's summary. In so doing we provide quicker access compared to having to navigate to the benchmark job and then expand the various folds first.
> Include benchmark results in workflow summary

- Cargo.toml
Update the criterion dependency that we rely on to version 0.5, to get the latest and greatest.
> Update criterion dependency to 0.5

- build.rs
Since commit c0c3afb38d67 ("Eliminate unnecessary rebuilds in build script") we started adjusting the mtime of generated files, in an attempt to prevent unnecessary rebuilds from occurring. Since then we have added supported for downloading large test files, but the corresponding code does not sport such an mtime adjustment. Add it, to prevent rebuilds when using the generate-large-test-files feature.
> Adjust mtime of downloaded files

- benches/inspect.rs
- benches/main.rs
- benches/normalize.rs
- benches/symbolize.rs
Unfortunately criterion with the bencher output format does not align benchmark results properly ([0]). As a result it is quite hard to read the summary from a glimpse.
To work around this problem, this change "manually" adjusts the names of our benchmark functions so that the corresponding results in the summary report are aligned properly.
[0]: https://github.com/bheisler/criterion.rs/issues/704
> Properly align benchmark output

- CHANGELOG.md
- benches/inspect.rs
- benches/symbolize.rs
- build.rs
This change adds two more benchmarks to our suite. The first one measures symbolization time using the ELF symbolizer and the second one using the DWARF symbolizer, but without querying line information. Compared to before, we make sure to actually generate an ELF file without DWARF information and a DWARF file without ELF symbols, respectively.
> Add more benchmarks

- .github/workflows/test.yml
- tests/blazesym.rs
In the past (read: before commit 449db8bd00ef ("Add addr2line-based DWARF parsing logic")) we were unable to symbolize the abort_creds in our kernel test image correctly.
With this commit landed, this change adds a test making sure that we do not regress.
> Add DWARF regression test

- examples/backtrace.rs
Commit 52d05139b395 ("Provide runnable example for symbolize module") added a doc test symbolizing a backtrace to the symbolize module, which helps to quickly illustrate API usage.
With this change we add the same example code as a dedicated example inside the examples/ folder, where it can be run via `cargo run`.
> Add an example symbolizing a captured backtrace

- build.rs
- src/lib.rs
- src/normalize/buildid.rs
- src/normalize/mod.rs
Being able to read build IDs from arbitrary ELF files may be necessary in order to better work with the results of the normalization APIs, for example, when attempting to look up a file by the reported build ID. As such, it makes sense to export this functionality publicly. With this change we do just that, inside the newly introduced helper module. While at it, also add a test for md5 build IDs.
> Expose build ID reading functionality publicly

- CHANGELOG.md
- src/maps.rs
As it turns out, when low addresses are reported inside `/proc/[pid]/maps` they may get prefixed with '0' characters in the reported range. However, this range is not actually what can be looked up below `/proc/self/map_files/`: there these leading zeroes are removed instead. So far we deliberately treated the range *as a string* to *not* have to deal with any mismatches, but this turns out to be the wrong approach. Hence, with this change we create the maps file path based on the parsed range, which takes care of removing any leading zeroes.
> Fix maps_file path creation for low addresses

- src/dwarf/resolver.rs
- src/dwarf/units.rs
Replace the usage of `env::args().next()` with `env::current_exec()`, which is more telling and easier to search for.
> Replace env::args().next() with env::current_exec()

- CHANGELOG.md
- src/elf/parser.rs
- src/elf/types.rs
Starting with commit 1b6878918160 ("Use lowest match search in ElfParser::find_sym()") we honored the symbol's size when attempting to symbolize an address based on ELF information. However, it turns out that the size may not actually be reliable information: we have seen cases where a function was reported as much smaller than the actual code that it comprised at runtime (the addresses of which could show up in backtraces). Whether that is due to runtime linker tricks or other shenanigans, we should be able to handle such cases.
With this change we adjust the ELF parser symbol lookup logic to handle such cases more gracefully. Specifically, if an address falls between two symbols such as `0x29d90` in:
```
0000000000029d00 <__libc_init_first>
29d00:       f3 0f 1e fa             endbr64 …
```
> Report ELF symbols with bogus size if only conceivable match

- .github/workflows/test.yml
- src/dwarf/units.rs
Commit cdd5b9c1a057 ("Replace env::args().next() with env::current_exec()") broke the nightly benchmarks and that was not caught because...GitHub Actions uses some more than questionable defaults for the default shell, which supposedly is bash, but it is invoked with fewer error reporting options than if we explicitly asked for it [0]. Make. It. Stop.
Explicitly specify the shell and fix the build.
[0] https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
> Fix nightly benchmark builds

- cli/src/args.rs
- cli/src/main.rs
This change adds support for symbolizing ELF addresses to blazecli.
```
$ cargo run -p blazecli -- symbolize elf --path /tmp/test/libc.so.6 0x29d90
> 0x29d90: __libc_init_first@0x29d00+144 :0
```
> cli: Add support for symbolizing ELF addresses

- CHANGELOG.md
- Cargo.toml
- README.md
- include/blazesym.h
- src/c_api/symbolize.rs
- src/dwarf/resolver.rs
- src/dwarf/unit.rs
- src/dwarf/units.rs
- src/elf/resolver.rs
- src/gsym/resolver.rs
- src/kernel.rs
- src/ksym.rs
- src/lib.rs
- src/resolver.rs
- src/symbolize/symbolizer.rs
- tests/blazesym.rs
- tests/c_api.rs
This PR adds support for transparent demangling of symbols. Demangling is generally runtime configurable (via the previously added Builder flag), but because it involves additional dependencies there is also the option to disable it at compile time. If disabled at compile time, the runtime option becomes a no-op.
Demangling currently happens in a single location inside the Symbolizer type. This has the advantage of concentrating the feature's implementation. However, it means that we need to bubble up the inferred language from all resolvers -- something that the recently added IntSym type helps us with.
> Add support for demangling symbols

- cli/README.md
Add a first version of a README that explains the basics of the `blazecli` program.
> Add a brief README file for blazecli

- .github/workflows/build.yml
Sometimes no suitable build environment is at hand but a binary of the program desired. For such cases it makes sense to have access to a statically linked binary that essentially is able to run on any Linux. This change introduces a workflow that can be used to produce such a binary. It can be triggered on-demand and will produce such a binary and make it available as a downloadable artifact.
> Add workflow for building statically linked binary

- src/symbolize/source.rs
We may end up including symbolize::Elf objects in traces. Right now their Debug representation is very verbose, making said traces unnecessarily hard to read.
This change provides a custom Debug impl that shortens the output reasonably.
Refs: #223
> Provide custom Debug impl for symbolize::Elf

- CHANGELOG.md
- benches/symbolize.rs
- cli/src/main.rs
- examples/addr2ln.rs
- examples/addr2ln_pid.rs
- examples/backtrace.rs
- include/blazesym.h
- src/c_api/symbolize.rs
- src/dwarf/resolver.rs
- src/elf/resolver.rs
- src/gsym/resolver.rs
- src/symbolize/mod.rs
- src/symbolize/symbolizer.rs
- tests/blazesym.rs
The documentation of the `symbolize::Sym::addr` member is wrong: the reported address is pretty much never that of the target process, for the simple reason that there may not be a target process at all (when symbolizing an address inside an ELF file, for example). This change fixes the documentation.
Furthermore, a common use case when symbolizing stack traces, for example, is to include the offset of the instruction included in the trace in the symbolized result. Currently that is done by subtracting the input address from the "symbolized" address. However, this calculation is fundamentally broken most of the time in a process context, because process addresses are not normalized addresses, but our `Symbolizer` reports normalized addresses. Hence, when relocations are or randomizations …
> Introduce symbolize::Sym::offset member

- include/blazesym.h
- src/c_api/symbolize.rs
- tests/blazesym.rs
- tests/c_api.rs
We recently made the path attribute in the Rust symbolize::Sym type optional. For the C API, we mapped a None to an empty string. That is arguably not in line with how optionality is generally encoded in C. Switch to using a NULL pointer instead.
> Make blaze_sym::path member optional

- CHANGELOG.md
- cli/src/main.rs
- examples/addr2ln.rs
- examples/addr2ln_pid.rs
- examples/backtrace.rs
- include/blazesym.h
- src/c_api/symbolize.rs
- src/symbolize/mod.rs
- src/symbolize/symbolizer.rs
- tests/blazesym.rs
- tests/c_api.rs
All our supported formats internally store source code information as a directory path and a file name. Many clients may reasonably expect this split and while we could always do it retroactively, it makes sense to stay as close to the supported formats as possible. Down the line, that could allow us to stop allocating new buffers altogether and just hand out references, in a more zero-copy (and zero-alloc) fashion. With this change we split the symbolize::Sym::path member into dir and file attributes to represent this split in the library.
> Split symbolize::Sym::path member into dir and file

- Cargo.toml
- src/dwarf/units.rs
We don't really need the library to be an rlib from what I gather. We need it to be available as:
- a static library (staticlib)
- a dynamic library (cdynlib)
- and as a Rust library
For the latter, lib is the default [0] (which likely is just an alias for rlib) and I don't think we have any good reason to overwrite this default. Also sneak in a comment fix while at it.
[0]: https://doc.rust-lang.org/reference/linkage.html
> Replace rlib crate-type with lib

- CHANGELOG.md
- Cargo.toml
- README.md
- cli/README.md
This change bumps the version of the crate to 0.2.0-alpha.4.
> Bump version to 0.2.0-alpha.4

- src/gsym/linetab.rs
- src/gsym/parser.rs
- src/gsym/resolver.rs
- src/gsym/types.rs
Co-locate the parse_line_table_header() functionality with the LineTableHeader type it work on by making it a constructor of the same.
> Make `parse_line_table_header()` a `LineTableHeader` constructor

- cli/src/args.rs
- cli/src/main.rs
- examples/addr2ln.rs
- examples/addr2ln_pid.rs
- examples/backtrace.rs
- src/elf/resolver.rs
- src/maps.rs
- src/normalize/mod.rs
- src/normalize/user.rs
- src/symbolize/mod.rs
- src/symbolize/symbolizer.rs
As it turns out, Rust can automatically take care of prefixing hexadecimal numbers with `0x`, as long as we use the alternate format. This has the advantage that it takes effect for all numbers in a structured type, e.g., when we print an array of addresses in hexadecimal format.
With this change we use this alternate format.
> Use alternate format when formatting hex and bin numbers

- CHANGELOG.md
- src/elf/parser.rs
When we search for a symbol by address in ELF, we were missing an additional check that the symbols we iterate over are still within the desired address range. That's necessary because we effectively filter by symbol type and such filtering may advance to symbols that are no longer matching from an address perspective.
This change fixes the problem by adding the necessary address check.
> Fix potentially incorrect reporting of symbols from ELF resolver

- CHANGELOG.md
- Cargo.toml
- README.md
- cli/README.md
This change bumps the version of the crate to `0.2.0-alpha.5`.
> Bump version to `0.2.0-alpha.5`

- src/c_api/symbolize.rs
There is nothing unsafe about the `convert_symbolizedresults_to_c()` function. Remove the `unsafe` attribution.
> Make convert_symbolizedresults_to_c() safe

- include/blazesym.h
- src/c_api/inspect.rs
- src/c_api/normalize.rs
- src/c_api/symbolize.rs
- src/error.rs
- src/lib.rs
- src/normalize/meta.rs
- src/symbolize/source.rs
We try to have reasonably comprehensive documentation for public parts of the API surface. The compiler can help with that task by warning when such documentation is missing.
Enable the corresponding lint to make it do just that.
> Warn on `missing_docs`

- src/gsym/resolver.rs
We originally introduced find_line_info_impl() in
GsymResolver::find_line_info() to short circuit on the various error paths, because it was way too cumbersome to report custom errors on each.
By now we have the means for more concise error chaining and so we remove this internal function and report more detailed errors for each of the potential early returns.
> Make GsymResolver::find_line_info() report more error context

- src/dwarf/resolver.rs
Commit 304915fd1cf2 ("Make DwarfResolver work with AddrLineInfo objects") adjusted the signature of the DwarfResolver::find_line_info() method, but didn't adjust the comment talking about its return value. Do so now.
> Fix documentation surround DwarfResolver::find_line_info()

- CHANGELOG.md
- src/c_api/normalize.rs
We still had a todo!() in the code that could trigger when normalizing
an APK ELF file using the C APIs.
This change adds the necessary conversion to fix the potential panic.
> Add missing UserAddrMeta -> blaze_user_addr_meta conversion

- CHANGELOG.md
- Cargo.toml
- README.md
- cli/README.md
This change bumps the version of the crate to `0.2.0-alpha.6`.
> Bump version to 0.2.0-alpha.6

- src/dwarf/resolver.rs
- src/elf/resolver.rs
- src/gsym/resolver.rs
- src/kernel.rs
- src/ksym.rs
- src/resolver.rs
- src/symbolize/mod.rs
Rename the internal `AddrLineInfo` type to `AddrSrcInfo`. There is more information contained in its objects than just the line.
> Rename AddrLineInfo -> AddrSrcInfo

- src/dwarf/resolver.rs
- src/elf/resolver.rs
- src/gsym/resolver.rs
- src/kernel.rs
- src/ksym.rs
- src/resolver.rs
- src/symbolize/mod.rs
Rename the internal AddrSrcInfo type to AddrCodeInfo. We use "code" as opposed to "source" (or "src"), because we already use the latter for the symbolization source terminology.
> Rename AddrSrcInfo -> AddrCodeInfo

- CHANGELOG.md
- src/dwarf/resolver.rs
- src/elf/parser.rs
- src/elf/resolver.rs
- src/gsym/resolver.rs
- src/ksym.rs
- src/resolver.rs
- src/symbolize/symbolizer.rs
- tests/blazesym.rs
With this change we expose the symbol's size in the form of the newly added Sym::size member, if it is available. Currently the only symbolization source that does not expose the size is kallsyms.
> Add symbol size to Sym type

- src/symbolize/symbolizer.rs
This change removes some annoying code duplication in Symbolizer::symbolize_with_resolver(), that repeatedly turned out to be a maintenance complication.
> Remove code duplication in Symbolizer::symbolize_with_resolver()

- README.md
- src/symbolize/symbolizer.rs
This change adds a feature matrix for the symbolization functionality to the README as well as the Symbolizer type. It depicts which features are available in supported formats and whether blazesym supports them.
> Add feature matrix to README and Symbolizer documentation

- CHANGELOG.md
- src/elf/parser.rs
When we landed da913a1f488c ("Report ELF symbols with bogus size if only conceivable match"), which effectively caused us to ignore ELF reported symbol sizes as part of symbol lookup, we were not considering the possibility of "partly available" symbols. Specifically, the "bogus size" that we saw believed to have seen was actually a misinterpretation of an instruction-to-symbolize residing in a stripped function that was located between two non-stripped symbols.
Given this new understanding of the situation, this change adjusts the ELF parser code to honor symbol sizes. The only exception is for size 0, which is treated specially by ELF and used for symbols with "no size or an unknown size".
Refs: #269
> Fully trust ELF reported sizes aside from 0

- CHANGELOG.md
- benches/symbolize.rs
- cli/src/main.rs
- data/test-stable-addresses.c
- data/test-stable-addresses.ld
- examples/addr2ln.rs
- examples/addr2ln_pid.rs
- examples/backtrace.rs
- include/blazesym.h
- src/c_api/symbolize.rs
- src/dwarf/resolver.rs
- src/elf/resolver.rs
- src/gsym/inline.rs
- src/gsym/linetab.rs
- src/gsym/mod.rs
- src/gsym/parser.rs
- src/gsym/resolver.rs
- src/kernel.rs
- src/ksym.rs
- src/resolver.rs
- src/symbolize/mod.rs
- src/symbolize/symbolizer.rs
- src/util.rs
- tests/blazesym.rs
- tests/c_api.rs
> Add support for parsing Gsym inlined function information

- CHANGELOG.md
- benches/symbolize.rs
- include/blazesym.h
- src/c_api/symbolize.rs
- src/elf/cache.rs
- src/symbolize/symbolizer.rs
- tests/c_api.rs
We started using the terminology "code info" rather than "source location" for everything pertaining, well, source code location information, because "source" is ambiguous in the blazesym code base as it's already used to denominate the symbolization source. With this change we whole-sale adjust the corresponding terminology in the `Builder` type and everywhere else where it is still present.
> Rename `src_location` -> `code_info`

- tests/blazesym.rs
With the recent addition of the size member to the Sym type, we no longer need the find_function_size() function to retrieve the size of a function. Remove it.
> Remove find_function_size() helper function

- src/symbolize/mod.rs
- src/symbolize/symbolizer.rs
The CodeInfo, InlinedFd, and Sym type definitions are somewhat hard to find inside symbolize/symbolizer.rs and also conceptually don't exactly belong in there.
With this change we move them into symbolize/mod.rs.
> Move CodeInfo, InlinedFd, and Sym definitions into symbolize/mod.rs

- src/normalize/normalizer.rs
This change switches two uses of
`DefaultBuildIdReader::read_build_id_from_elf()` over to using the simpler `read_elf_build_id()` API.
> Use read_elf_build_id() more

- CHANGELOG.md
- benches/symbolize.rs
- cli/src/main.rs
- examples/addr2ln.rs
- examples/addr2ln_pid.rs
- examples/backtrace.rs
- include/blazesym.h
- src/c_api/symbolize.rs
- src/symbolize/mod.rs
- src/symbolize/symbolizer.rs
- src/util.rs
- tests/blazesym.rs
- tests/c_api.rs
After going back and forth about the approach to returning symbolized symbols, we concluded that the property if having a 1:1 mapping from input address index to resulting symbol index is desirable to have. To that end, this change removes the index based reporting logic and replaces it with a custom enumeration that encapsulates both successful symbolization as well as non-symbolized addresses in its variants. We decided against the usage of an Option to open up the possibility of adding more variants in the future.
> Introduce and use Symbolized enumeration

- src/dwarf/unit.rs
- src/dwarf/units.rs
The Unit::find_function_or_location() method is rather confusing and convoluted. The name seems to imply that "either or" is returned (at least that's always my reading of it) and it returns two things but the caller really only needs the first one. That's mostly because we kept its original intent and workings so far.
With this change we simplify it, renaming it to find_function() and making it return only the function, if found.
> Simplify Unit::find_function_or_location()

- src/dwarf/unit.rs
Remove the unnecessary 'unit lifetime from the Unit::parse_lines() method.
> Remove unnecessary lifetime from Unit::parse_lines()

- tests/blazesym.rs
Use the more convenient Symbolizer::symbolize_single() in our Gsym inline test. Not going to replace all similar call sites, but this one may get duplicated moving forward, so let's duplicate the simplified variant...
> Use Symbolizer::symbolize_single() in Gsym inline test

- .github/workflows/test.yml
- cli/src/main.rs
- examples/addr2ln.rs
- examples/addr2ln_pid.rs
- examples/backtrace.rs
- src/symbolize/mod.rs
- src/symbolize/symbolizer.rs
- tests/blazesym.rs
We missed to honor the demangle setting for the recently added inlined function calls. Make sure to demangle their names as necessary and desired.
Also adjust the various symbolization snippets floating around to fix some formatting issues.
```
$ cargo run --example=backtrace
> 0x005606435278e0: backtrace::symbolize_current_bt @ 0x2e770+0x170 blazesym/examples/backtrace.rs:59:18
> 0x00560643528255: backtrace::h @ 0x2f250+0x5 blazesym/examples/backtrace.rs:111:5
> 0x00560643528245: backtrace::f @ 0x2f240+0x5 blazesym/examples/backtrace.rs:101:5
>                   backtrace::g @ blazesym/examples/backtrace.rs:106:5 [inlined]
> 0x00560643528265: backtrace::main @ 0x2f260+0x5 blazesym/examples/backtrace.rs:115:5
> 0x00560643524f8a: core::ops::function::FnOnce::call_once @ 0x2bf80+0xa …
```
> Properly demangle inlined calls

- .github/workflows/test.yml
Let's depended on `Swatinem/rust-cache@v2` instead of `Swatinem/rust-cache@v2.x.y`. The former gets automatically bumped when a new release is cut, which is more convenient than having a pull request created every time (though it comes at the cost of being less obvious).
> Use Swatinem/rust-cache@v2

- .github/workflows/test.yml
- build.rs
- data/test.rs
- include/blazesym.h
- src/c_api/symbolize.rs
- src/symbolize/mod.rs
- tests/blazesym.rs
- tests/c_api.rs
With this change we expose inlined function information through the C API.
> Expose inlined functions through C API

- src/symbolize/symbolizer.rs
The documentation of the symbolize::Builder::enable_demangling() method is misleading. Fix it up.
> Fix documentation for symbolize::Builder::enable_demangling()

- CHANGELOG.md
- Cargo.toml
- README.md
- cli/README.md
This change bumps the version of the crate to `0.2.0-alpha.7`.
> Bump version to `0.2.0-alpha.7`

- build.rs
- data/test.rs
- tests/blazesym.rs
- tests/c_api.rs
With commit dff91ef1a01d ("Create proper Rust binary to test on") we provided a list of mangled symbol names of test_function() to our symbolize_dwarf_demangle test. However, that's not sufficient to ensure passing of the test unconditionally, because the compiler is free to conjure up additional mangled symbol variants as per the v0 mangling scheme.
To make the name stable, fix it using the `export_name` attribute instead.
> Provide a stable export mangled name for "test_function()"

- CHANGELOG.md
- Cargo.toml
- README.md
- cli/README.md
This change bumps the version of the crate to 0.2.0-alpha.7.
> Bump version to 0.2.0-alpha.7

- src/dwarf/resolver.rs
- src/elf/cache.rs
- src/elf/resolver.rs
Rename the various get_parser() methods to parser().
> Rename get_parser() to parser()

- .github/workflows/test.yml
- CHANGELOG.md
- src/elf/resolver.rs
The SymResolver::find_line_info() method was renamed a while back and an additional argument added some time later. However, presumably because of conditional compilation, the variant in the ElfResolver in use when the `dwarf` feature is not active had not been updated accordingly. Do that now to prevent a build failure.
Now we did have the --no-default-features CI job for this specific case. However, it turns out that because we build with the --workspace flag, with the introduction of blazecli (which depends on blazesym with the default features), we end up compiling with just the default features (despite specifying --no-default-features) and with that rendering the check useless. So fix it up work correctly again.
> Fix signature of ElfResolver::find_line_info() method

- CHANGELOG.md
- benches/normalize.rs
- benches/symbolize.rs
- src/dwarf/resolver.rs
- src/elf/parser.rs
- src/elf/resolver.rs
- src/gsym/parser.rs
- src/gsym/resolver.rs
- src/lib.rs
- src/mmap.rs
- src/normalize/normalizer.rs
- src/normalize/user.rs
- src/symbolize/symbolizer.rs
- src/zip.rs
- tests/blazesym.rs
- tests/c_api.rs
So far `Addr` was defined to be a `usize`. That is in line with Rust specifying that `usize` has the size of a pointer. However, once we start using the library in a cross compilation context (e.g., using it to symbolize parts of a dump captured on a different machine), the local pointer size has admittedly little meaning.
With this change we define `Addr` to be of type `u64`, which is in-line with the representation of many of the formats that we support. Doing so makes us more independent of the actual pointer size as it basically is meant as an upper limit on current sizes (that may not be entirely true with research architectures such as CHERI, but it is still a reasonable and arguably better approximation for what we expect to support).
> Make Addr a u64

- include/blazesym.h
- src/c_api/normalize.rs
- src/normalize/user.rs
- tests/c_api.rs
We use count and the shorter cnt for the same purposes. Converge on using only 'cnt' for brevity.
> Rename count -> cnt

- benches/normalize.rs
- cli/src/main.rs
- src/normalize/meta.rs
- src/normalize/mod.rs
- src/normalize/normalizer.rs
- src/normalize/user.rs
- tests/blazesym.rs
Rename `norm_addrs` (as frequently used to assigned the normalization result) to the more neutral `normalized`. With upcoming changes the result of normalization will no longer necessarily be addresses, but file offset and this term will allow us to reduce churn down the line.
> Rename norm_addrs -> normalized

- src/elf/parser.rs
- src/elf/resolver.rs
This change moves the file offset retrieval logic from the ELF resolver into the ELF parser, where it will be better co-located with similar functionality and is generally more accessible.
> Add find_file_offset() method to ElfParser

- src/elf/cache.rs
Stop returning an Rc instance from ElfBackend::to_dwarf() and just roll with a reference instead.
> Adjust ElfBackend::to_dwarf() to return a reference

- README.md
With the normalization API rework (mainly #359), we no longer intend to add specific remote symbolization APIs. Rather, the existing symbolization APIs were adjusted to be compatible for use with the outputs of normalization. As such, let's mark the remote symbolization TODO (and issue) as done.
Closes: #61
> Tick off Remote Symbolization from roadmap

- README.md
With the normalization API rework (mainly #359; issue: #321) we trimmed down the work performed as part of address normalization to what is pretty much the bare minimum (removing "heavy-weight" operations such as memory mapping large binaries or parsing ELF data structures). We don't see a need for additional caching at this point, unless proven slow. Remove the corresponding TODO.
> Remove normalization logic caching from roadmap

- CHANGELOG.md
- Cargo.toml
- include/blazesym.h
- src/elf/cache.rs
- src/lib.rs
- src/symbolize/symbolizer.rs
It arguably makes little sense to purge least recently used symbolization related data from a cache based solely on a number of elements in the cache: it means that a 50 KiB ELF file has the same "weight" as a 2 GiB DWARF monstrosity. Yet, that's what our ElfCache type currently does. To get more reasonable behavior, we'd need to account for how much actual data is allocated. That in turn needs to be made configurable, because 1 GiB of memory may be a lot to one user but not at all to another, and it needs to account for the potential of lazy loading (e.g., various DWARF data structures are only loaded into memory once needed, which can happen delayed compared to others). In short, it's a bunch of complexity that we do not want to deal with at this point (or ever).
To that end, this …
> Remove LRU caching logic

- src/zip.rs
This change adds a test ensuring coverage of the Debug impl of the zip::Archive type.
> Add "test" for Debug representation of zip::Archive type

- src/symbolize/symbolizer.rs
There are a few unnecessary spaces in the "feature table" for the symbolizer. Remove them to shrink its size a bit.
> Shrink symbolizer feature table a bit

- CHANGELOG.md
- cli/src/args.rs
- cli/src/main.rs
This change adds support for symbolizing Gsym addresses to blazecli.
$ cargo run -p blazecli -- symbolize gsym --path data/test-stable-addresses.gsym 0x200020a
> 0x0000000200020a: factorial_inline_test @ 0x2000200+0xa blazesym/data/test-stable-addresses.c:32
>                   factorial_inline_wrapper @ blazesym/data/test-stable-addresses.c:26 [inlined]
>                   factorial_2nd_layer_inline_wrapper @ blazesym/data/test-stable-addresses.c:21 [inlined]
> cli: Add support for symbolizing Gsym addresses

- src/gsym/linetab.rs
- src/gsym/resolver.rs
We use addr as opposed to address in many places. Rename the LineTableRow.address member to go with the flow.
> Rename LineTableRow.address to addr

- CHANGELOG.md
- src/gsym/linetab.rs
The check and early return when file_line is less than one inside of run_op() is bogus. It leads to wrong symbolization results and it is not prevent in the original C++ code. Remove it.
> Remove bogus file_line check in run_op()

- src/dwarf/resolver.rs
- src/elf/resolver.rs
With upcoming changes we are going to need the fact that `ElfParser` objects are generally managed inside an `Rc` at the various call sites using resolvers.
To that end, this change adjusts the `DwarfResolver` and `ElfResolver` getters to return `Rc<ElfParser>` references instead of mere `ElfParser` references.
> Return Rc<ElfParser> references from various getters

- CHANGELOG.md
- include/blazesym.h
- src/dwarf/resolver.rs
- src/elf/resolver.rs
- src/inspect/inspector.rs
With this change we start caching inspection related in-memory data structures across Inspector::lookup() requests. This is mirroring a similar scheme that we employ in the Symbolizer type.
> Cache inspection related data structures

- src/dwarf/resolver.rs
- src/inspect/inspector.rs
- src/symbolize/symbolizer.rs
It makes no sense to create a DwarfResolver object but then deny it the usage of DWARF debug information -- that's what is already controlled via the ElfBackend type. Remove the flag as a first step towards reclaiming sanity.
> Remove enable_debug_info_syms flag from DwarfResolver

- .github/workflows/test.yml
Let's employ the help of clippy to prevent todo!() call sites from sneaking into product code. Do so from CI, which is expected to check all crates in the workspace.
> Deny `todo!()` macro in product code

- src/elf/resolver.rs
- src/inspect/inspector.rs
It's questionable practice to have `DwarfResolver` and `ElfResolver` return partly initialized objects and then fix them up later on in the Inspector, as we do for the `SymInfo` objects returned by `SymResolver::find_addr()`.
Admittedly we can't fill in all the gaps at the lowest layer at this point, but we have all the necessary information in the `ElfResolver` itself. So perform all the "fixups" there and at least preserve sanity at the `SymResolver` API surface level.
> Move SymInfo object fixup from Inspector into ElfResolver

- src/dwarf/resolver.rs
- src/elf/resolver.rs
- src/inspect/inspector.rs
- src/inspect/mod.rs
- src/ksym.rs
- src/normalize/normalizer.rs
It's unclear what we gain from making the object file name retrieval conditional: the string is readily present unconditionally and so all we save is an allocation. On top of that, this flag isn't even exposed so it's complexity for nothing. Remove it.
> Remove FindAddrOpts::obj_file_name flag

- src/dwarf/resolver.rs
- src/elf/resolver.rs
- src/gsym/resolver.rs
- src/kernel.rs
- src/ksym.rs
- src/lib.rs
- src/resolver.rs
- src/symbolize/mod.rs
- src/symbolize/symbolizer.rs
This change moves the definition of the IntSym type into the symbolize module. We already defined the Sym in there, so it makes little sense to have a "more internal" type be defined at a higher level.
> Move IntSym definition into symbolize module

- CHANGELOG.md
- src/c_api/inspect.rs
- src/dwarf/resolver.rs
- src/elf/parser.rs
- src/elf/resolver.rs
- src/inspect/mod.rs
- src/ksym.rs
- tests/blazesym.rs
The SymInfo::file_offset member is not present all the time: some sources may not be able to provide this information and in general retrieval is currently optional (at least internally). Make this fact more obvious by making this member an Option. This could potentially be reverted in the future, but for the time being we want to have an explicit differentiation between None and 0 (certainly at the Rust level) for upcoming changes.
> Make SymInfo::file_offset an Option

- src/symbolize/mod.rs
- src/symbolize/symbolizer.rs
Code coverage is highlighting a bunch of "red" on the `#[derive(Debug)]` annotations on the `Symbolizer` related types. Add tests for them.
> Add "test" for Debug representation of Symbolizer related types

- src/elf/types.rs
It's annoying having to add `#[derive(Debug)]` every time we want to dump some internals. Add the derive permanently.
> Add Debug impls for various ELF types

- src/elf/parser.rs
- src/elf/types.rs
Our ELF support is incomplete. One issue we have is that we cannot handle more than 0xff00 section headers, because ELF special cases anything above this value.
This change fixes this very shortcoming, by using the correct sequence of steps for inferring the number of section headers.
Refs: #64
> Support more than 0xff00 (SHN_LORESERVE) section headers

- CHANGELOG.md
- Cargo.toml
- src/error.rs
- tests/error_backtrace.rs
- tests/error_no_backtrace1.rs
- tests/error_no_backtrace2.rs
Seeing error and their call chains can be tremendously useful and most of the time that is sufficient to get a good understanding of an issue. However, occasionally errors don't contain enough context and messages are reused on multiple call paths.
With this change we enhance our Error type with the capability to capture a backtrace at the time the error was created. This backtrace is then contained in the Debug representation. Note that because capturing a backtrace is a costly operation, backtrace capture is controlled by environment variables in the same way that Rust proper behaves.
> Optionally include backtraces in errors

- src/elf/parser.rs
- src/elf/types.rs
Our ELF support is incomplete. One issue we have is that we cannot handle a e_shstrndx value greater than 0xff00, because ELF special cases anything above this value.
This change fixes this very shortcoming, by using the correct sequence of steps for retrieving the actual value.
Refs: #64
> Support handling large e_shstrndx values

- src/elf/parser.rs
- src/elf/types.rs
Our ELF support is incomplete. One issue we have is that we cannot handle more than 0xffff program headers, because ELF special cases anything above this value.
This change fixes this very shortcoming, by using the correct sequence of steps for retrieving the actual value.
Refs: #64
> Support more than 0xffff program headers

- CHANGELOG.md
- Cargo.toml
- README.md
- cli/README.md
This change bumps the version of the crate to 0.2.0-alpha.8.
> Bump version to 0.2.0-alpha.8

- src/symbolize/mod.rs
In recent times we added a few more types to the symbolize/mod.rs file. Turns out their Debug representations aren't really exercised right now, resulting in easy to fix low coverage numbers. Add "tests" accordingly for some boost.
> Boost code coverage of symbolize/mod.rs

- CHANGELOG.md
- src/gsym/resolver.rs
- src/mmap.rs
- src/symbolize/symbolizer.rs
With this change we cache Gsym file-based resolvers based on the file system path used. This is similar to what we do for other resolvers such as those used for ELF files.
> Cache Gsym (file-based) resolvers

- src/gsym/resolver.rs
The GsymResolver::find_addr() method currently shows up as uncovered by testing. That's not a surprise, as our inspect functionality does not currently support Gsym sources.
Let's test it with a unit test, to at least not get penalized for it in our coverage report.
> Add test for GsymResolver::find_addr()

- src/elf/resolver.rs
- src/gsym/resolver.rs
This change introduces two more tests covering the Debug representation of various types.
> Add more tests for Debug representation

- .github/workflows/test.yml
Some of our build jobs are actively contending for the title of longest running job per CI workflow run.
Cache build artifacts similar to what we already do for benchmarks to speed them up. This has the potential to tremendously speed up builds, particularly on slower configurations. E.g., MacOS builds were seen to take anywhere from around 6-9 minutes in the past. With caching enabled they complete in less than 1 minute 20 seconds.
> Cache build artifacts in CI

- .github/workflows/test.yml
By now (and with commit 4599086a712b ("Cache build artifacts in CI") landed), the running of benchmarks is by far the longest part blocking submission of a pull request. There isn't really that much of a point in running them as part of a pull request, as we generally don't rely on benchmark runtimes for anything -- see commit 43d3742ed828b ("Run all benchmarks in CI")
With this change we run them only as part of a push to the main branch. To ensure we do not regress our benchmark code, we still run them in "test mode" (i.e., a single iteration) during testing by enabling the nightly flag for the coverage job.
> Run benchmarks only on push

- .github/workflows/test.yml
- CHANGELOG.md
- src/c_api/symbolize.rs
- src/dwarf/resolver.rs
- src/elf/resolver.rs
- src/file_cache.rs
- src/gsym/resolver.rs
- src/insert_map.rs
- src/inspect/inspector.rs
- src/lib.rs
- src/once.rs
- src/resolver.rs
- src/symbolize/mod.rs
- src/symbolize/symbolizer.rs
- src/util.rs
- tests/blazesym.rs
So far we unconditionally heap-allocated all dynamically sized bits of information that we hand out as part of the symbolization process. Conceptually a lot of these allocations are unnecessary: symbol names, file names, and directory paths all are present in the symbolization sources already.
With this change we adjust all involved types to carry Cow correspondents of the unconditionally-owned types previously used. We then adjust all the logic to omit allocating when that is unnecessary. Not all symbolization paths can be allocation free. For example, when the Gsym::Data source is used, we do not have control over the data and, hence, cannot safely embed references to it in the symbolization result. In such a case we fall back to heap allocating followed by copying of the necessary …
> Make symbolization results include references to memory mapped data

- benches/main.rs
- benches/symbolize.rs
All our existing end-to-end benchmarks included setup time and excluded
any benefits gained from caching symbolization data -- effectively a
worst case scenario.
This change adds a benchmark that keeps around the symbolizer and
symbolizes multiple addresses in a single call. All addresses have a
high (n >= 12) number of inlined functions, so reporting them does have
a large effect on performance.
When run with and without https://github.com/libbpf/blazesym/pull/402,
which eliminates large amounts of allocations (which apply to all symbol
names and paths, including those in reported inlined functions), we can
see an almost 12% performance improvement by said change:
```
main/symbolize_gsym_multi_no_setup
time:   [119.31 µs 121.71 µs 124.59 µs]
change: [-13.978% -11.955% -9.7199%] (p = 0.00 …
```
> Add benchmark for Gsym symbolization without setup

- src/ksym.rs
The `ksym_resolver_load_find` test is flaky. The reason being that `kallsyms` may contain multiple function names for the same address (probably because of aliases) and that can trip us over when searching for the one alias by address but then getting back a different one. Fix the test by doing a reverse lookup back from name to address to make sure that we did indeed find one correct candidate, instead of mindlessly just checking the names for equality.
> Fix ksym_resolver_load_find test

- CHANGELOG.md
- src/gsym/inline.rs
The start and end address calculation that we perform as part of the Gsym inlined function parsing could potentially result in a numeric overflow, depending on inputs.
Make sure to handle such cases more gracefully then panicking (on debug builds).
> Handle potential numeric overflows more gracefully

- src/elf/parser.rs
- src/ksym.rs
Switch `KsymResolver` over to using `OnceCell` as opposed to `RefCell`.
> Use `OnceCell` in `KsymResolver`

- build.rs
We should rerun the build script if the `LLVM_GSYMUTIL` environment variable changed, so that we automatically regenerate `*.gsym` files in the process.
> Rerun build script on LLVM_GSYMUTIL change

- src/gsym/parser.rs
Opt in to using explicitly checked arithmetic in two more places in the Gsym parser code.
> Use checked arithmetic some more

- .github/workflows/publish-cli.yml
- .github/workflows/publish.yml
Introduce a GitHub Actions workflow for publishing blazecli. For now it only covers publishing, not creating any GitHub releases or Git tags. These may or may not come later, as needed.
> Introduce workflow for publishing blazecli

- cli/Cargo.toml
It can come in handy to have blazecli available via cargo install and publishing it to crates.io will also increase visibility. Bump the version to 0.1.0, marking the first release.
> cli: Bump version to `0.1.0`

- .github/workflows/test.yml
- CHANGELOG.md
- src/file_cache.rs
It probably makes sense for us to explicitly cross-compile to a few more targets to weed out type casting bugs or similar early on. Do just that.
> Cross-compile to various targets in CI

- .github/workflows/publish-cli.yml
The publish workflow for blazecli runs the entire workspace test suite. However, by default blazecli consumes the in-repository copy of blazesym. This copy could potentially have unpublished changes. When we publish blazecli, however, it will end up consuming a published version of blazesym. If there is a divergence, a broken release may be the result.
Unfortunately, I haven't really found a satisfactory way of testing: ideally we'd want to run the test suite against the published blazesym (though doing so may have other problems). For now, let's just let cargo do its basic set of verification steps as part of the publish command to improve on what we have.
> cli: Run verification against crates.io blazesym before publish

- .github/workflows/publish-capi.yml
- capi/Cargo.toml
This change introduces a workflow for publishing the `blazesym-c` crate. For now it only covers publishing, not creating any GitHub releases or Git tags. These may or may not come later, as needed.
> Introduce workflow for publishing `blazesym-c`

- capi/src/symbolize.rs
Add a test for the debug representation of the `blaze_symbolize_inlined_fn` type of our C API bindings in order to increase coverage numbers slightly.
> Add test for debug repr of blaze_symbolize_inlined_fn

- .github/codecov.yml
- .github/workflows/test.yml
Blazecli is arguably a trivial wrapper around functionality provided by the main library. Given how simple it currently is, we didn't see a point in adding another test suite for it.
Exclude it from Codecov's coverage assessment accordingly.
> Exclude blazecli from coverage assessment

- cli/CHANGELOG.md
- cli/README.md
- cli/src/main.rs
The process symbolization fails because we are providing the wrong input type to the library. Fix up the logic.
> cli: Fix process symbolization

- .github/workflows/test.yml
It turns out Swatinem/rust-cache does not automagically include all job related metadata in the cache key used. Rather, we have to tell it explicitly that we use a given toolchain with a given profile.
> Add key suffix for Swatinem/rust-cache matrix usage

- .github/codecov.yml
Codecov is erring out again when code coverage decreases ever so slightly. The suspicion is that it has to do with the projects that we introduced.
Let's add the necessary property to them as well, in the hope that it helps.
> Run codecov in informational mode for all projects

- cli/CHANGELOG.md
- cli/Cargo.toml
- cli/README.md
This change bumps blazecli's version to 0.1.1. The following notable changes have been made since 0.1.0:
- Fixed process symbolization erring out with wrong input type message
> cli: Bump version to 0.1.1

- CHANGELOG.md
- src/maps.rs
- src/normalize/user.rs
We currently ignore all proc maps entries that are non-executable. That can be a problem once addresses of variables or other data are meant to be symbolized as well.
To remove this potential issue, let's work with both executable OR readable entries.
> Stop filtering out non-executable but readable proc maps entries

- cli/README.md
The README for `blazecli` mentions how to build the `shell-complete` binary, but the command for doing so is relative to the `cli/` sub-directory. That's not the case for other commands higher up in the README. Add the necessary package specification to make this command behave as the others.
> cli: Adjust shell complete cargo command to specify package

- .github/workflows/publish-capi.yml
- .github/workflows/publish-cli.yml
- .github/workflows/publish.yml
- .github/workflows/test.yml
The `actions-rs/toolchain` GitHub action is no longer maintained. Switch over to using `dtolnay/rust-toolchain` in its stead.
> Replace deprecated actions-rs/toolchain usage

- src/elf/parser.rs
This change adds context to two more error paths in an attempt to improve error reporting.
Refs: #266
> Add a few more error contexts

- Cargo.toml
- README.md
- capi/Cargo.toml
- cli/CHANGELOG.md
- cli/Cargo.toml
- cli/README.md
This change bumps the version of the crate to `0.2.0-alpha.9`.
> Bump version to `0.2.0-alpha.9`

- build.rs
We should be using the runtime environment variable query mechanism for reading CARGO_MANIFEST_DIR. Switch over.
> Query `CARGO_MANIFEST_DIR` variable at runtime

- capi/Cargo.toml
The `blazesym-c` crate needs `libc` really only as a dev-dependency. Downgrade it accordingly.
> capi: Make libc a dev-dependency

- src/elf/parser.rs
This change improves code coverage slightly by adding "tests" for Debug representations of more types of the ELF parser module.
> Add test coverage for more Debug representations

- capi/build.rs
- cli/build.rs
As a follow on to 8ca056740fe4 ("Query CARGO_MANIFEST_DIR variable at runtime"), which just provided a quick fix to blazesym proper, this change adjusts the remaining build scripts to query the CARGO_MANIFEST_DIR environment variable at runtime rather than compile time. This is the correct approach as per the reference [0]
[0] https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts
> Query CARGO_MANIFEST_DIR at runtime from build scripts

- CHANGELOG.md
- build.rs
- capi/src/symbolize.rs
- cli/src/main.rs
- examples/addr2ln.rs
- examples/addr2ln_pid.rs
- examples/backtrace.rs
- src/elf/parser.rs
- src/elf/resolver.rs
- src/gsym/resolver.rs
- src/kernel.rs
- src/ksym.rs
- src/normalize/user.rs
- src/resolver.rs
- src/symbolize/mod.rs
- src/symbolize/symbolizer.rs
- tests/blazesym.rs
Many paths can lead to an unsuccessful symbolization, and it may be hard for callers to figure out why symbolization didn't pan out. For example, a user may have provided a stripped binary, without being aware of that fact.
With this change we introduce the symbolize::Reason enumeration, which now accompanies the Symbolized::Unknown variant and aims to provide a best guess as to why symbolization was not successful.
> Introduce Reason enumeration to accompany `Symbolized::Unknown` variant

- tests/permission.rs
This change adds a test checking expected behavior when access to a symbolization source file is denied.
> Add a test for permission denied test case

- .github/workflows/test.yml
With this change we use the Swatinem/rust-cache GitHub Action in more of our CI jobs to speed up the workflow even more.
> Cache artifacts for more CI jobs

- .github/workflows/publish-cli.yml
- .github/workflows/publish.yml
Improve the release workflow for blazecli by also creating a tag and release for the published version.
> Improve release workflow for blazecli

- src/normalize/buildid.rs
Put the example code for the `read_elf_build_id()` function into a dedicated "Examples" section, similarly to how the standard library does things.
> Put read_elf_build_id() example code into "Examples" section

- src/symbolize/mod.rs
The _non_exhaustive markers we use in a bunch of public types were never meant to be visible in the documentation. Hide them.
> Hide _non_exhaustive markers from documentation

- .github/workflows/test.yml
It doesn't really make sense to restore, say, Linux build artifacts for a MacOS build.
Include the "runs-on" value in the cache key we use for the matrix to make that happening less likely.
> Include "runs-on" value in CI matrix cache key

- CHANGELOG.md
- benches/normalize.rs
- capi/include/blazesym.h
- capi/src/normalize.rs
- cli/src/main.rs
- src/normalize/meta.rs
- src/normalize/mod.rs
- src/normalize/normalizer.rs
- tests/blazesym.rs
The pid argument in the normalization APIs fulfills pretty much the same job as the src in the symbolization logic. As such, we should order them consistently with respect to the addresses provided. With this change we move the argument before the address list.
> Reorder pid argument in normalization APIs

- CHANGELOG.md
- benches/inspect.rs
- capi/src/inspect.rs
- capi/src/symbolize.rs
- src/inspect/inspector.rs
- src/inspect/mod.rs
- tests/blazesym.rs
The symbolization APIs order the source to use as the first actual element, before the list of addresses. For the inspect APIs we diverge -- for no good reason.
This change reorders `src` to be the first argument there as well.
> Reorder `src` argument in inspection APIs

- capi/src/symbolize.rs
It's unclear why we would have a PartialEq impl for the blaze_symbolize_src_kernel type -- there is really no need for comparing two such objects and comparing the contained pointers for equality is arguably providing the wrong semantics anyway. Remove the impl.
> capi: Remove `PartialEq` impl for `blaze_symbolize_src_kernel`

- capi/src/inspect.rs
- capi/src/symbolize.rs
Reuse the from_cstr() function that we have defined for the symbolization functionality from the inspect module, where it makes sense to use it for the same purpose.
> capi: Reuse `from_cstr()` in the `inspect` module

- README-devel.md
- benches/inspect.rs
- benches/symbolize.rs
Our end-to-end Criterion benchmarks depend on the
generate-large-test-files feature, because we need to have vmlinux-5.17.12-100.fc34.x86_64 kernel image present, which gets "prepared" when this feature is enabled.
At the same time, whenever this feature is switched we download and process a 700 MiB file, which takes a long time and may cause excessive SSD wear. In short, it's just not viable.
When this image is not present benchmarks fail with a pretty clear error message what is missing, so let's just not guard the running of benchmarks with this feature. Unless generated files are deleted, it's only necessary to enable this feature once to prepare files.
> Don't require generate-large-test-files for criterion benchmarks

- README-devel.md
Document the incantation necessary for creating a flamegraph for one of the criterion based benchmarks.
> Document how to create flamegraphs for criterion benchmarks

- .clippy.toml
- src/elf/types.rs
- src/lib.rs
In the past we had many submissions that, for one reason or another, were using absolute paths to functions/constants in a very inconsistent manner. It is not particularly great use of anybody's time pointing these out and it's certainly a job that computers can do better. Clippy folks seem to concur that this can be a useful lint [0] and we got blessed with clippy::absolute_paths.
Enable it throughout the crate and fix all violations.
[0] https://github.com/rust-lang/rust-clippy/issues/10568
> Enable clippy::absolute_paths lint

- .rustfmt.toml
- capi/include/blazesym.h
- capi/src/inspect.rs
- capi/src/symbolize.rs
- src/dwarf/lines.rs
- src/dwarf/unit.rs
- src/dwarf/units.rs
- src/elf/parser.rs
- src/error.rs
- src/gsym/linetab.rs
- src/gsym/parser.rs
- src/gsym/resolver.rs
- src/inspect/inspector.rs
- src/lib.rs
- src/normalize/buildid.rs
- src/normalize/normalizer.rs
- src/normalize/user.rs
- src/once.rs
- src/zip.rs
It turns out `rustfmt` can ensure a consistent comment length by applying automatic wrapping. Let's enable the functionality to get some more consistency into the code base and ensure that pull requests adhere to a basic standard in the process.
> Let rustfmt take care of wrapping comments

- .github/workflows/test.yml
- CHANGELOG.md
- Cargo.toml
- src/cfg.rs
- src/lib.rs
- src/normalize/normalizer.rs
- src/symbolize/mod.rs
- src/symbolize/source.rs
- src/symbolize/symbolizer.rs
Not every user will have a use for symbolization of addresses in APK files or for Gsym support. While conceptually these features should not have much of an impact on the library's footprint (neither in terms of compile time, number of dependencies, runtime performance, nor code size), there is still an argument to be made that users should not pay for something they don't use -- it feels wrong to include support for Gsym symbolization if it is clear that this feature will simply never be used.
To that end, this change introduces compile time features that guard the availability of APK and Gsym support. We also make sure to highlight which functionality is enabled by which feature in the generated documentation by usage of the doc_cfg rustdoc functionality (and enable it for generation on …
> Introduce 'apk' and 'gsym' features

- data/test-exe.c
- data/test-so.c
- src/dwarf/units.rs
- tests/blazesym.rs
- remove unnecessary `errno.h` include
- fix comment for recently added symbolize_process_in_mount_namespace test
- remove outdated header comment from test-exe.c
> Fix a few minor issues

- capi/CHANGELOG.md
- capi/README.md
- capi/include/blazesym.h
- capi/src/symbolize.rs
There is a divergence between the terminology we use for the Input enum in Rust code and the suffixes we added to the symbolization functions in the C API.
This change unifies the two to minimize the potential for confusion.
> capi: Use our "Input" terminology in C API

- CHANGELOG.md
- Cargo.toml
- capi/Cargo.toml
With this change we disable the recently introduced 'apk' and 'gsym' features by default. We anticipate both to be comparably fringe features (one making only sense on an Android system and the other requiring development effort [in the sense that special APIs have to be used] in order to use) and so it makes more sense to have them be opt-in. For the blazesym-c crate, we enable both features by default, because we do not anticipate the C library to have this kind of configurability -- there will only be a single version of it.
> Disable 'apk' and 'gsym' features by default

- src/normalize/user.rs
This another typo, this time in the documentation of the `normalize_user_addrs_sorted_impl()` function.
> Fix another typo

- Cargo.toml
Now that we have more non-default features, make sure to tell docs.rs what features to generate the documentation with, or it will lack crucial information.
> Set desired features for docs.rs documentation

- src/dwarf/resolver.rs
- src/error.rs
- src/gsym/resolver.rs
It arguably makes more sense to co-locate the `ErrorExt` impl for each error type that we support with the functionality that is using this error type, as opposed to it being located in a central location, as that leads to less conditional compilation directives being spread throughout the code base.
To that end, this change moves the `ErrorExt` impl for `gimli::Error` into the dwarf module.
> Move ErrorExt impl for gimli::Error into dwarf module

- src/symbolize/symbolizer.rs
This change adds a test exercising the code paths for unsupported APK symbolization inputs, as we do for other sources as well.
> Add test for unsupported APK symbolization inputs

- src/gsym/resolver.rs
Report a proper error from GsymResolver::find_addr(), which currently isn't supported. This functionality should not be accessible through public functions, so there shouldn't be any change in perceived semantics to users.
> Report proper unsupported error from GsymResolver::find_addr()

- .github/workflows/test.yml
- Cargo.toml
So far we have captured the need for building with our minimum supported Rust version (MSRV) by just building the library. Because we do not check in a Cargo.lock file, that means that the most recent versions of dependencies are being pulled in. Recently this backfired, because transitive dependencies started to have a higher minimum supported Rust version than we do.
This change fixes this issue by introducing a proper CI job for checking the MSRV and making sure to explicitly downgrade all dependencies to their minimum versions as part of it.
> Introduce proper minimum supported Rust version CI job

- src/symbolize/symbolizer.rs
Add a test exercising the Debug impl of the symbolize::Resolver enum to increase coverage.
> Test Debug impl of symbolize::Resolver

- .github/workflows/test.yml
- cli/Cargo.toml
Be sure to build blazecli and blazesym-c in isolation, to prevent any feature unification from messing up the result. Fix the blazecli build, which broke because the program does not enable the gsym feature of blazesym.
> Build blazecli and blazesym-c in isolation in CI

- src/gsym/parser.rs
- src/util.rs
Gsym encodes addresses inside its address table using the smallest integer that can capture all addresses used in it. Our code assumed that the address to search for can also be expressed as such an integer, but that is not necessarily the case, even for perfectly valid addresses: if the last symbol in the address table ends at a boundary that exceeds the type used to express the start address, then our Gsym will currently fail symbolization, as the conversion of the provided address into said integer type will not succeed.
This change fixes this issue by, instead of downcasting the input addresses for the binary search to happen, we upcast the addresses in the address table to our Addr type.
> Fix Gsym symbolization issue for "large" addresses

- CHANGELOG.md
- Cargo.toml
- README.md
- capi/Cargo.toml
- cli/CHANGELOG.md
- cli/Cargo.toml
- cli/README.md
This change bumps the version of the crate to `0.2.0-alpha.10`.
> Bump version to `0.2.0-alpha.10`

- cli/CHANGELOG.md
- cli/Cargo.toml
This change bumps blazecli's version to 0.1.2. The following notable changes have been made since 0.1.1:
- Bumped blazesym dependency to 0.2.0-alpha.10
> cli: Bump version to 0.1.2

- .github/workflows/test.yml
- .gitignore
- CHANGELOG.md
- Cargo.toml
- README.md
- benches/symbolize.rs
- build.rs
- cli/CHANGELOG.md
- cli/Cargo.toml
- cli/src/args.rs
- cli/src/main.rs
- src/breakpad/file.rs
- src/breakpad/mod.rs
- src/breakpad/parser.rs
- src/breakpad/resolver.rs
- src/breakpad/types.rs
- src/cfg.rs
- src/error.rs
- src/lib.rs
- src/symbolize/mod.rs
- src/symbolize/source.rs
- src/symbolize/symbolizer.rs
- tests/blazesym.rs
> Add support for Breakpad format

- src/maps.rs
Add a test for the parsing of a proc maps line that does not contain a path. It's already implicitly covered, but an explicit test can't hurt. While at it, remove an outdated comment from the parse_file() function.
> Add explicit test for parsing proc maps line without path

- src/lib.rs
- src/pid.rs
Move the Pid type into the pid module, where it is easier to extend it.
> Move Pid type into pid module

- .github/workflows/test.yml
- Cargo.toml
The fine folks over at criterion have decided to be play unresponsive to any asks for new releases. Pull in a git snapshot of the library that includes:
- daa84cafe706e731139c768f7c67cc5577041309 ("Include thousands-separators in `bencher` output (#705)")
- 928d8a96dfd755dc14eb0f4821c196a9ec73cc9f ("Enable `--help` messages and accept `--include-ignored` as no-op (#703)")
to get what we need.
> Pull in git version of criterion

- .github/workflows/test.yml
- CHANGELOG.md
- capi/CHANGELOG.md
- capi/include/blazesym.h
- capi/src/symbolize.rs
- src/elf/parser.rs
- src/maps.rs
- src/mmap.rs
- src/normalize/user.rs
- src/pid.rs
- src/symbolize/mod.rs
- src/symbolize/perf_map.rs
- src/symbolize/source.rs
- src/symbolize/symbolizer.rs
- tests/empty_perf_map.rs
Support handling of perf maps. Please see individual commits for descriptions.
> Support handling of perf maps

- CHANGELOG.md
- capi/src/inspect.rs
- src/inspect/mod.rs
We want to leave open the options of adding additional variants to the inspect::SymType enum down the line without breaking backwards compatibility.
Mark the type as non-exhaustive to make sure that this is a possibility.
> Make inspect::SymType enum non-exhaustive

- src/elf/resolver.rs
- src/normalize/normalizer.rs
- src/symbolize/source.rs
- src/symbolize/symbolizer.rs
We do not intend to run tests with recently introduced optional features (apk, dwarf, gsym, ...) disabled. Our recursive dev-dependency "ensures" that they are, in fact, enabled.
Remove the unnecessary complexity introduced by making certain tests conditional on said features.
> Make tests assume necessary features to be present

- capi/Cargo.toml
Enabling the blazesym-c crate as a library ensures that we can compose the blazesym library with other rust libraries that would publish C bindings.
> Publish the C api crate a library

- CHANGELOG.md
- capi/CHANGELOG.md
- capi/include/blazesym.h
- capi/src/inspect.rs
- capi/src/symbolize.rs
- data/test-stable-addresses.c
- data/test-stable-addresses.ld
- src/dwarf/resolver.rs
- src/elf/parser.rs
- src/elf/resolver.rs
- src/elf/types.rs
- src/gsym/resolver.rs
- src/inspect/inspector.rs
- src/inspect/mod.rs
- src/ksym.rs
- src/lib.rs
- src/normalize/normalizer.rs
- src/symbolize/symbolizer.rs
- tests/blazesym.rs
> Add support for `STT_GNU_IFUNC` and `STT_OBJECT` ELF symbols types

- capi/CHANGELOG.md
- capi/include/blazesym.h
- capi/src/normalize.rs
- capi/src/symbolize.rs
- src/normalize/normalizer.rs
- tests/blazesym.rs
This change adds the blaze_normalizer_new_opts() constructor for blaze_normalizer objects to the C API. Using it users can control the availability of build IDs as part of the normalization output.
> capi: Add blaze_normalizer_new_opts() constructor

- capi/CHANGELOG.md
- capi/include/blazesym.h
- capi/src/inspect.rs
Given our abbreviated names `BLAZE_SYM_FUNC` and `BLAZE_SYM_VAR`, it makes sense to shorten `BLAZE_SYM_UNDEFINED` to `BLAZE_SYM_UNDEF`. Rename the variant accordingly.
> capi: Rename BLAZE_SYM_UNDEFINED to BLAZE_SYM_UNDEF

- .github/workflows/test.yml
With an upcoming change we will add more conditional build logic to build scripts that has the potential for screwing with rebuilds. To preempt any screw ups from the start, make sure that our nop-rebuilds job checks the entire workspace.
> Test nop rebuilds of entire workspace

- capi/src/lib.rs
- capi/src/normalize.rs
Enable the `unsafe_op_in_unsafe_fn` lint. Refer to commit 0f4b25dd43fd ("Make unsafe blocks explicit") for details.
> capi: Enable `unsafe_op_in_unsafe_fn` lint

- cli/CHANGELOG.md
- cli/src/args.rs
- cli/src/main.rs
Introduce the --no-debug-syms option to the 'symbolize elf' sub-command, so that users can opt out of the usage of debug symbols.
> cli: Add --no-debug-syms option to 'symbolize elf' sub-command

- CHANGELOG.md
- build.rs
- src/dwarf/function.rs
- src/dwarf/location.rs
- src/dwarf/unit.rs
- src/dwarf/units.rs
- tests/blazesym.rs
When a DWARF debug information contains a DW_TAG_subprogram entry with
an DW_AT_abstract_origin that is outside the current compilation unit,
function name retrieval fails, because cross unit lookups of this form
were not covered by our existing logic. E.g.,
```
0x0000000b: DW_TAG_compile_unit
DW_AT_producer    ("GNU GIMPLE [...]")
DW_AT_language    (DW_LANG_C99)
DW_AT_name        ("<artificial>")
...
0x00000066:   DW_TAG_subprogram
DW_AT_abstract_origin   (0x000000000000026d "factorial")
DW_AT_low_pc    (0x0000000002000100)
DW_AT_high_pc   (0x000000000200012b)
...
0x0000019b: DW_TAG_compile_unit
DW_AT_producer    ("GNU C17 [...]")
DW_AT_language    (DW_LANG_C99)
...
0x0000026d:   DW_TAG_subprogram
DW_AT_external  (true)
DW_AT_name      ("factorial")
...
```
This change fixes this short …
> Resolve function names across DWARF units

- .github/workflows/test.yml
- capi/.gitignore
- capi/CHANGELOG.md
- capi/Cargo.toml
- capi/build.rs
- capi/cbindgen.toml
- capi/examples/input-struct-init.c
- capi/include/blazesym.h
- capi/src/inspect.rs
- capi/src/lib.rs
- capi/src/normalize.rs
- capi/src/symbolize.rs
In order to ensure some level of forward & backward compatibility, this change extends all our input types with a member holding the objects size. Users need to set this member to the size of the type. The library can then ignore unsupported fields (forward compatibility) or provide reasonable defaults for fields not provided (backward compatibility).
> capi: Add object sizes to input types

- .github/workflows/test.yml
- capi/src/inspect.rs
The test was meant to be run, but because we did not execute Miri on the entire workspace, it actually wasn't. Make sure to test the workspace. Also disable stacked borrows for the time being, because it seems to cause a false positive. Or at least I can't find an issue with it. Lastly, use addr_of! macro for good measure. We should probably do that throughout the code base eventually.
> Run elf_src_validity in CI

- src/util.rs
The `read_i16()` and `read_i32()` methods of the `ReadRaw` trait aren't actually used by the crate (anymore). Current versions of Rust lament this fact.
Remove them to make the toolchain happy.
> Remove unneeded ReadRaw trait methods

- src/file_cache.rs
- src/insert_map.rs
- src/symbolize/symbolizer.rs
Introduce the `FileMeta` helper type holding all the file meta data attributes that our `FileCache` cares about. Grouping all these fields in a single type will make it easier to work with them in the future.
> Introduce `FileMeta` helper type

- src/file_cache.rs
- src/insert_map.rs
- src/util.rs
All our symbolization requests are funneled through our `FileCache`. Assuming "auto reloading" is enabled, we open the symbolization source in question, read its meta-data (modification time etc.), and insert a new entry only if the meta data changed.
In most cases we expect there to be no change, in which case we unnecessarily opened the file and closed it. It is more efficient to just read only its meta-data by default, but potentially do that work twice if we found that the file did indeed change.
With this change we adjust the `FileCache::entry()` method accordingly.
> Only read file meta-data in FileCache on happy-path

- src/symbolize/symbolizer.rs
It seems incorrect for us to use the symbolic path as the APK path when symbolizing an address in a process. Similar to what we do for ELF files, we should work with the maps file entry instead.
> Use maps file entry for in-process APK symbolization

- benches/normalize.rs
- src/breakpad/parser.rs
- src/elf/types.rs
Add a benchmark for normalizing a set of addresses without reading of build IDs. This way we can easily assess the impact that reading of build IDs has on normalization performance.
> Add benchmark for normalizing without reading of build IDs

- cli/CHANGELOG.md
- cli/src/args.rs
- cli/src/main.rs
Introduce the --no-build-ids option to the 'normalize user' sub-command. This way, users can opt out of the reading (and reporting) of build IDs.
```
$ cargo run -p blazecli -- normalize user --pid=236355 0x7f7aafeeb13f --no-build-ids
> 0x007f7aafeeb13f: file offset 0x113f in /home/muellerd/local/opt/blazesym/data/libtest-so.so
```
> cli: Add --no-build-ids option to 'normalize user' sub-command

- src/normalize/buildid.rs
All methods on the `NoBuildIdReader` type are no-ops. As such, it's probably not a bad idea to declare them as `#[inline]`, to increase chances of them vanishing entirely.
> Declare two more functions #[inline]

- .github/workflows/test.yml
- capi/Cargo.toml
- capi/benches/capi.rs
- capi/benches/normalize.rs
This change adds a benchmark for the normalization of addresses using the C API.
> capi: Add benchmark for address normalization

- Cargo.toml
- capi/Cargo.toml
Update the `test-log` dev-dependency to version `0.2.14`. In this version we no longer need to declare the `tracing-subscriber` and `env_logger` dependencies ourselves. Remove them.
> Update test-log dev-dependency to 0.2.14

- benches/normalize.rs
As a tiny addition, also check the meta count in the normalization benchmarks, to make sure that we get ballpark correct results.
> Check meta count in normalization benchmarks

- tests/blazesym.rs
Rename the inspect test functions to include the type of source being worked on. This will make it easier to add tests for additional sources in the future.
> Rename inspect test functions

- src/breakpad/parser.rs
- src/breakpad/resolver.rs
- src/breakpad/types.rs
- src/inspect/inspector.rs
- src/inspect/mod.rs
- src/inspect/source.rs
- src/util.rs
- tests/blazesym.rs
This change adds inspection support for the Breakpad format. Specifically, We support look up by name as well as iteration of symbols. Note, though, that only functions are contained in the Breakpad file, and so these are all that we support as well. And even there disclaimers abound, as GNU indirect functions, for example, are not necessarily contained and public symbols may not carry sufficient information to be reported either.
> Add Breakpad support to inspect APIs

- CHANGELOG.md
- Cargo.toml
- README.md
- capi/Cargo.toml
- cli/CHANGELOG.md
- cli/Cargo.toml
- cli/README.md
This change bumps the version of the crate to 0.2.0-alpha.11.
> Bump version to 0.2.0-alpha.11

- cli/CHANGELOG.md
- cli/Cargo.toml
This change bumps blazecli's version to 0.1.3. The following notable changes have been made since 0.1.2:
- Added support for symbolization using Breakpad (*.sym) files
- Added --no-debug-syms option to symbolize elf sub-command
- Added --no-build-ids option to normalize user sub-command
- Bumped blazesym dependency to 0.2.0-alpha.11
> cli: Bump version to 0.1.3

- README.md
- cli/README.md
Enhance the various README files with some links to our prebuilt blazecli binary CI job.
> Advertise prebuilt blazecli binaries more

- .github/workflows/build.yml
- .github/workflows/publish-cli.yml
We generally can and do trigger blazecli builds manually, whenever there is a need. However, it most certainly makes sense to have artifacts around whenever we release a new version.
Automatically trigger the build workflow from the publish-cli CI job to make that happen. Note that ideally we'd attach all those build artifacts to the release, but that is a royal hassle with GitHub Actions.
> Automatically build blazecli artifacts on publish

- data/test-so.c
The time logic inside of test-wait.c is no longer used. Remove it.
> Remove unnecessary cruft from test-wait.c

- .github/workflows/publish-capi.yml
This change enhances the publish workflow by having it create a proper GitHub release as well as tag the published commit appropriately.
> capi: Enhance publish workflow

- capi/CHANGELOG.md
- capi/Cargo.toml
This change bumps the blazesym-c's version to 0.1.0-alpha.0. The following notable changes have been made since the decoupling from blazesym proper (version 0.2.0-alpha.8):
- Added constructs for forward & backward compatibility:
- Added type_size member to input types and BLAZE_INPUT macro for initialization
- Reserved trailing padding bytes to ensure zero initialization
- Reserved space for future extension in output types
- Added blaze_normalizer_new_opts function and blaze_normalizer_opts type
- Added auto_reload attribute to blaze_symbolizer_opts
- Renamed various symbolization functions to closer reflect Rust terminology
- Renamed BLAZE_SYM_UNKNOWN enum variant to BLAZE_SYM_UNDEF
- Added perf_map and map_files members to blaze_symbolize_src_process type
> capi: Bump version to 0.1.0-alpha.0

- capi/README.md
Now that we have our first "actual" release of blazesym-c, add a badge showing the version published to crates.io to the README.
> capi: Add crates.io version badge to README

- capi/CHANGELOG.md
- capi/Cargo.toml
Make sure to include the blazesym.h header file in the published package, to make it easier to work with only the crates.io package, even when building a C program.
> capi: Include blazesym.h in published package

- capi/CHANGELOG.md
- capi/Cargo.toml
This change bumps the blazesym-c's version to 0.1.0-alpha.1. The following notable changes have been made since 0.1.0-alpha.0:
- Included blazesym.h header file in release package
> capi: Bump version to 0.1.0-alpha.1

- capi/src/inspect.rs
- capi/src/symbolize.rs
- src/breakpad/resolver.rs
- src/elf/resolver.rs
- src/inspect/inspector.rs
- src/lib.rs
- src/symbolize/symbolizer.rs
- src/util.rs
We have a bunch of redundant imports in test modules that were not flagged by earlier version of rustc. Remove them so that once we upgrade we don't see any warnings/errors.
> Remove a bunch of redundant imports

- capi/src/symbolize.rs
The C symbolizer code converts a zero element array into a mutable pointer, but that is being flagged in newer versions of Rust:
> error: casting references to a bigger memory layout than the backing
>        allocation is undefined behavior, even if the reference is
>        unused
Go with two method calls to accomplish the same feat.
> capi: Omit unnecessary cast

- .github/workflows/test.yml
Nightly Rust has been fixed and the issue necessitating pinning the version is no longer present. Revert the change pinning the version.
This reverts commit db01d98008ad09c2683490ae21eedba218f91aa2.
> Revert "Pin nightly toolchain in CI"

- src/normalize/user.rs
Downgrade the addresses iterator from an `ExactSizeIterator` to a more generic one, as there is no need to know the iterator's size inside the function.
> Downgrade addrs: A bound of normalize_sorted_user_addrs_with_entries()

- src/normalize/user.rs
- src/symbolize/symbolizer.rs
The normalize_sorted_user_addrs_with_entries() currently accepts a Handler and returns said Handler once done. That's a reasonable pattern to employ conceptually, but it makes it hard to use dynamic dispatch on the handler, as that would require boxing the object in the return position.
With this change we switch the
normalize_sorted_user_addrs_with_entries() function over to accepting a &mut Handler instead, removing the return argument in the process. In so doing we sidestep this issue and open the door for using runtime dispatch moving forward.
> Adjust normalize_sorted_user_addrs_with_entries() to work with &mut Handler

- src/normalize/user.rs
- src/symbolize/symbolizer.rs
Similar to what we did earlier for the handler argument to the normalize_sorted_user_addrs_with_entries() function, this change causes us to use a trait object and dynamic dispatch for the MapsEntry iterator argument. In so doing we open the door for using the same instance of the function for different MapsEntry iterator types, minimizing the potential for binary bloat.
> Use Iterator trait object for MapsEntry sequence

- benches/normalize.rs
Instead of passing in a flag for each feature that we want to configure in the Normalizer instance to the benchmark function, let's just pass in the configured Normalizer instance directly.
> Pass Normalizer object to benchmark function

- benches/normalize.rs
Currently we benchmark slightly more than just the actual normalization call. That's fine in principle, but it is limiting once we work with a potentially stateful Normalizer instance.
With this change we benchmark only the part of the function that actually performs the normalization. In so doing we allow for reuse of the Normalizer instance across benchmark runs, which is a property we will use subsequently.
> Benchmark normalization sub-functions only

- .github/workflows/test.yml
- Cargo.toml
- tests/allocs.rs
This change adds some infrastructure that we can use for capturing memory allocation statistics. As a first step we capture such statistics for the address normalization path. We include the means for printing backtraces for each allocation being made, which can help with better understanding the reported numbers.
```
> $ cargo test --test=allocs -- normalize_process --nocapture
> Stats: Stats {
>   allocations: 47,
>   deallocations: 47,
>   reallocations: 11,
>   bytes_allocated: 19742,
>   bytes_deallocated: 19742,
>   bytes_reallocated: 540,
> }
> $ RUST_BACKTRACE=1 cargo test --test=allocs -- normalize_process --nocapture
> ...
```
> Add infrastructure for capturing allocation statistics

- Cargo.toml
Compiling benchmarks is taking excessive time, owing to our use of LTO and working with a single codegen unit. Loosen these settings to get back some compilation speed. At the same time, enable LTO for release builds, which have an impact mostly for `blazecli`.
> Disable LTO for 'bench' profile

- CHANGELOG.md
- src/maps.rs
The last component in a /proc/<pid>/maps line is optional. We treat it this way, but by using the split_once() function, which produces nice errors, we unnecessarily create an Error object just to throw it away subsequently. Because Errors are heap allocated, we incur some heap allocations on the happy path, which is not the intention. Remove them by working only with Option objects at the location in question. For the normalize_process test, this reduces the number of allocations by 20 (47 down to 27) on my system:
```
> $ cargo test --test=allocs -- normalize_process --nocapture
> Stats: Stats {
>     allocations: 27,
>     deallocations: 27,
>     reallocations: 7,
>     bytes_allocated: 18322,
>     bytes_deallocated: 18322,
>     bytes_reallocated: 252,
> }
```
> Reduce number of allocations for address normalization

- README-devel.md
This change adds a section on how to use our allocation profiling infrastructure to the `README-devel` file.
> Add section about allocation profiling to README-devel

- src/error.rs
- src/lib.rs
There is no cblazesym crate, it is now called blazesym-c. Fix the typo and clean up a few other minor bits.
> Fix 'cblazesym' mention in documentation

- CHANGELOG.md
- benches/normalize.rs
- capi/CHANGELOG.md
- capi/include/blazesym.h
- capi/src/normalize.rs
- src/maps.rs
- src/normalize/normalizer.rs
- src/normalize/user.rs
- src/pid.rs
This change adds the necessary logic for caching the parsed
`/proc/<pid>/maps` data on a per-process basis, when the Normalizer's
'reevaluate_maps' property is `false`.
Having caching in place can help speed up repeated address normalization
for the process, but because there does not appear to be a way to detect
up-to-dateness of the cached `/proc/<pid>/maps`, there exists the
potential for correctness issues.
```
main/normalize_process
time:   [36.494 µs 37.249 µs 38.141 µs]
main/normalize_process_no_build_ids
time:   [28.232 µs 28.482 µs 28.709 µs]
main/normalize_process_no_build_ids_cached
time:   [1.1735 µs 1.1839 µs 1.1934 µs]
```
> Optionally cache parsed `/proc/<pid>/maps` entries during normalization

- src/maps.rs
- src/normalize/normalizer.rs
- src/normalize/user.rs
- src/symbolize/symbolizer.rs
This change optimizes the normalization of addresses using cached /proc/<pid>/maps entries further. Specifically, we eliminate the clone of the potentially large MapsEntry object, which involves a bunch of heap allocations.
In order to do so we end up going back to a world where normalization functions accept the MapsEntry iterator as a generic argument as opposed to a trait object, because doing so allows us to abstract over ownership using the AsRef trait.
As a result of this work, we improve the performance of this path by close to 35%:
```
> main/normalize_process_no_build_ids_cached
>      time:   [621.76 ns 624.34 ns 627.07 ns]
>      change: [−35.120% −34.666% −34.255%] (p = 0.00 < 0.02)
>      Performance has improved.
```
> Optimize cached address normalization further

- src/maps.rs
- src/normalize/normalizer.rs
The normalization logic uses the
```
maps::parse(..)
.filter_map(..
maps::filter_map_relevant(entry)
..)
```
construct in two locations. Let's introduce the maps::parse_filtered() helper to simplify the code at these two call sites.
> Factor out maps::parse_filtered() helper

- src/maps.rs
- src/normalize/user.rs
Up until commit 27925760054b ("Remove PathMapsEntry type") we were converting the `MapsEntry` passed in to `maps::filter_map_relevant()` into a `PathMapsEntry` object, making it necessary to return the new object. With the removal of this type, however, we can switch over to just returning a `bool`, sticking more closely to what the `Iterator::filter()` method expects.
> Adjust maps::filter_map_relevant to return a bool

- capi/src/lib.rs
Add a section about the thread-safety guarantees that the library provides to its documentation.
> capi: Document thread-safety guarantees

- capi/build.rs
- capi/cbindgen.toml
- capi/include/blazesym.h
We don't really want users to understand the generated header file as the library's documentation (despite it coming with some explanations), because links won't be resolved and additional context won't be provided.
With this change we make sure to include a link to the docs.rs documentation prominently at the top of the header file.
> capi: Include link to documentation in generated header

- src/normalize/normalizer.rs
We intended for the maps caching to be disabled by default, but missed to negate the value when negating the associated flag's meaning ("reevaluate_maps" -> "cache_maps"). Make caching disabled by default.
> Fix normalizer maps caching default value

- README-devel.md
Add a section on how to re-generate the C header file to README-devel, so that people attempting to add a new C API have an easier time understanding the process.
> Document how to generate C header to README-devel

- CHANGELOG.md
- benches/normalize.rs
- capi/include/blazesym.h
- capi/src/normalize.rs
- src/normalize/buildid.rs
- src/normalize/normalizer.rs
- src/normalize/user.rs
Build ID caching, on top of normalization reason logic (https://github.com/libbpf/blazesym/pull/560).
Benchmark results:
```
> main/normalize_process_uncached_build_ids_uncached_maps
>     time:   [32.616 µs 32.638 µs 32.666 µs]
> main/normalize_process_uncached_build_ids_cached_maps
>     time:   [20.211 µs 20.251 µs 20.303 µs]
> main/normalize_process_cached_build_ids_uncached_maps
>     time:   [52.176 µs 52.275 µs 52.403 µs]
> main/normalize_process_cached_build_ids_cached_maps
>     time:   [3.4718 µs 3.4760 µs 3.4808 µs]
> main/normalize_process_no_build_ids_uncached_maps
>     time:   [29.789 µs 29.812 µs 29.846 µs]
> main/normalize_process_no_build_ids_cached_maps
>     time:   [921.03 ns 921.65 ns 922.41 ns]
```
> Add support for caching build IDs in address normalization

- capi/include/blazesym.h
- capi/src/symbolize.rs
Currently, the C API does not support symbolizing file offsets in an ELF file, despite this feature being available in the Rust implementation. This is particularly important for use cases where the result of normalization (file offset and ELF file) for a given process needs to be passed into the symbolizer for further symbolization.
> capi: Add symbolization for file offsets in an ELF file

- src/insert_map.rs
Code coverage shows that the InsertMap::default() constructor is not exercised by any of the tests. Make sure to change that fact to boost our coverage numbers by a bit.
> Include InsertMap::default() usage in tests

- benches/main.rs
With the recent addition of longer named benchmarks for the normalization functionality, we reached and exceeded our previously set name width, causing the summary to look somewhat garbled. Increase the constant to make things look nice again.
> Increase benchmark name width constant

- README-devel.md
The suggestion of running `cargo test` to test "everything" isn't really accurate anymore, because of the split into multiple crates a while back.
Let's suggest the usage of `cargo test --workspace` instead, making it obvious that there is more than just the core library.
> Update README-devel to suggest testing the entire workspace

- Cargo.toml
- build.rs
As part of https://github.com/mozilla/dump_syms/pull/667 the Config::with_output() constructor was introduced as a short hand to exhaustively specifying all fields. This functionality is now contained in version 2.3 of the crate.
This change adjusts our build script to use it.
> Use dump_syms::Config::with_output() constructor

- tests/allocs.rs
Use a const block in our usage of the thread_local! macro to silence a newly reported warning [0].
[0] https://rust-lang.github.io/rust-clippy/master/index.html#/thread_local_initializer_can_be_made_const
> Use const block in thread_local! macro

- capi/include/blazesym.h
- capi/src/inspect.rs
- capi/src/normalize.rs
- capi/src/symbolize.rs
Improve the documentation of the normalizer/symbolizer/inspector creation APIs, so that it is easier to find out what default options are enabled or not.
> capi: Document normalizer/symbolizer/inspector creation APIs a bit more

- capi/Cargo.toml
- src/gsym/parser.rs
- src/gsym/types.rs
- src/normalize/normalizer.rs
Improve a few minor details with the normalization API documentation and remove unnecessary documentation for some internal helper function, which does not really differ from its public counter part.
> Adjust wording in normalizer documentation slightly

- capi/CHANGELOG.md
- capi/cbindgen.toml
- capi/examples/input-struct-init.c
- capi/include/blazesym.h
- capi/src/lib.rs
The macro no longer adds any value as we can just rely on padding bytes being zero initialized because they are explicitly declared now. Instead just obfuscates what is going on. Remove it.
> capi: Remove `BLAZE_INPUT` macro

- cli/CHANGELOG.md
- cli/src/args.rs
- cli/src/main.rs
- data/test-stable-addresses-cu2.c
- data/test-stable-addresses.c
- src/gsym/resolver.rs
Introduce the 'inspect' command to the program. It in turn is comprised
of the 'lookup' and 'dump' sub-commands. Right now only inspection of
ELF files is supported.
```
$ cargo run --package blazecli -- inspect dump elf --path ../data/test-stable-addresses.bin
> main:                  0x00000002000000+59   [FUNC]
> i_exist_twice:         0x0000000200003b+14   [FUNC]
> factorial_wrapper:     0x00000002000049+17   [FUNC]
> foo:                   0x0000000200005a+17   [FUNC]
> i_exist_twice:         0x0000000200006b+14   [FUNC]
> factorial_wrapper:     0x00000002000079+17   [FUNC]
> my_indirect_func:      0x0000000200008a+7    [FUNC]
> indirect_func:         0x00000002000091+11   [FUNC]
> resolve_indirect_func: 0x00000002000091+11   [FUNC]
> dummy:                 0x0000000200009c+0 …
```
> cli: Introduce 'inspect' command

- cli/src/args.rs
- cli/src/main.rs
- data/test-stable-addresses-cu2.c
Add support for working with Breakpad files to the 'inspect' command.
```
$ cargo run --package blazecli -- inspect lookup breakpad --path data/test-stable-addresses.sym resolve_indirect_func main i_exist_twice
> resolve_indirect_func: 0x00000000000088+11   [FUNC]
> i_exist_twice:         0x00000000000040+14   [FUNC]
> i_exist_twice:         0x00000000000093+14   [FUNC]
$ cargo run --package blazecli -- inspect dump breakpad --path data/test-stable-addresses.sym
> i_exist_twice:         0x00000000000040+14   [FUNC]
> factorial_wrapper:     0x0000000000004e+17   [FUNC]
> foo:                   0x0000000000005f+17   [FUNC]
> factorial_wrapper:     0x00000000000070+17   [FUNC]
> my_indirect_func:      0x00000000000081+7    [FUNC]
> resolve_indirect_func: 0x00000000000088+11   [FUNC]
> …
```
> cli: Add support for Breakpad files to 'inspect' command

- cli/src/args.rs
- cli/src/main.rs
Add support for reading ELF build IDs to the program. Perhaps a bit counter to the direct mirroring of blazesym's structure we adhere to for other functionality, we add this functionality below the 'inspect' command. At least right now that seems the most appropriate.
```
$ cargo run --package blazecli -- inspect buildid elf data/libtest-so.so
> df0178b961f7ffb9f956d96781970219674b75e2
$ cargo run --package blazecli -- inspect buildid elf data/test-stable-addresses.bin
> N/A
```
Refs: #304
> cli: Add support for reading ELF build IDs

- .github/workflows/test.yml
- CHANGELOG.md
- Cargo.toml
- README.md
- build.rs
- capi/Cargo.toml
- cli/Cargo.toml
- src/dwarf/units.rs
- src/elf/parser.rs
- src/elf/types.rs
- tests/blazesym.rs
Add support for working with compressed ELF sections ([0] [1]). To the best of my knowledge, these are currently only used in conjunction with compressed DWARF information. This change only adds support zlib compressed sections. zstd is another algorithm supported by ELF and should be easy to add as a follow up.
Decompression currently happens entirely at the ELF layer. This makes it a trivial addition. However, it means that we have to decompress the entire section data in advance. Doing so may be less controversial than one might think, though: generally there is no random access into compressed data and while it may be possible to build something resembling random-access for certain formats (e.g., [2]), none of the zlib Rust crates evaluated seemed to sport random-access support in any …
> Add support for compressed ELF sections

- cli/src/main.rs
Using a plus sign ('+') followed by the size of the function/variable when looking up/dumping symbols, it is not easy to infer the meaning. Switch to using a more expressive output where we just print the size labeled as such:
```
$ cargo run --package blazecli -- inspect dump breakpad --path data/test-stable-addresses.sym
> factorial_wrapper:     0x00000000000040 (size=17)   [FUNC]
> i_exist_twice:         0x00000000000051 (size=14)   [FUNC]
> foo:                   0x0000000000005f (size=22)   [FUNC]
> factorial_wrapper:     0x00000000000075 (size=17)   [FUNC]
> my_indirect_func:      0x00000000000086 (size=7)    [FUNC]
> resolve_indirect_func: 0x0000000000008d (size=11)   [FUNC]
> i_exist_twice:         0x00000000000098 (size=14)   [FUNC]
> factorial:             0x00000000000100 …
```
> cli: Change the way symbol size is conveyed

- CHANGELOG.md
- cli/src/main.rs
- src/breakpad/resolver.rs
- src/elf/parser.rs
- src/inspect/inspector.rs
- tests/blazesym.rs
The Inspector::for_each() method currently carries a "result" around for each symbols visited. There isn't really any point to having a result like this be passed around, given that we are not constraining its type and so we effectively can't do anything with it.
Remove it from the signature. Users can just close mutably over the state that previously was passed around. By removing it we bring the method signature in line with that of [`Iterator::for_each()`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.for_each).
> Remove 'R' generic argument from Inspector::for_each() method

- .github/workflows/test.yml
- Cargo.toml
- build.rs
- capi/Cargo.toml
- cli/Cargo.toml
- src/dwarf/units.rs
- src/elf/parser.rs
- tests/blazesym.rs
Add support for decompressing zstd compressed ELF sections. This is a bit tricky to test by default, at the moment, because most distributions don't ship `zstd` enabled toolchains. For that reason we don't enable the feature or tests by default.
> Add zstd decompression support for ELF sections

- CHANGELOG.md
Make sure to mention the recently added zstd decompression support for ELF sections in the CHANGELOG.
> Mention zstd decompression support in CHANGELOG

- src/inspect/mod.rs
- src/symbolize/mod.rs
As it turns out, even re-exports of public items need to add the `cfg_attr(docsrs, ...)` attribute, or the generated documentation will not show the necessary features to include said item. Adjust our re-exports accordingly.
> Highlight required features in documentation better

- capi/CHANGELOG.md
- capi/include/blazesym.h
- capi/src/inspect.rs
- capi/src/lib.rs
- capi/src/normalize.rs
- capi/src/symbolize.rs
- src/error.rs
Our fallible API functions currently simply return a pointer that can be
NULL, conveying failure but not what kind of failure. This can make it
unnecessarily hard to understand problems.
With this change we introduce the blaze_error enum, mirroring the
ErrorKind type of the Rust crate, that categorizes the error at a high
level. We also adjust all fallible functions to return this error.
> Introduce `blaze_err` enum and adjusted all fallible functions to return it

- src/symbolize/source.rs
Establish a backlink from the symbolize::Source enum to the Symbolizer::symbolize() method -- it's main consumer -- in the documentation.
> Backlink symbolize::Source to Symbolizer::symbolize in documentation

- capi/src/lib.rs
- src/symbolize/symbolizer.rs
When symbolizing APK addresses of unsupported types, the error messages mention "ELF symbolization". That's not entirely incorrect, given that we currently assume ELF files to reside inside, but let's refer to the process as "APK symbolization" for the sake of understanding.
> Correct APK related error messages on invalid input

- src/inspect/source.rs
Establish a backlink from the `inspect::Source` enum to the `Inspector::lookup()` and `Inspector::for_each()` methods in the documentation.
> Backlink inspect::Source to Inspector methods in documentation

- src/elf/resolver.rs
The times when ElfResolver had a "load address" are long gone, as it was a broken concept. Remove the documentation still mentioning it.
> Remove outdated ElfResolver description

- src/dwarf/resolver.rs
The test-only DwarfResolver::open() constructor currently accepts a debug_line_info argument, which all callers set to true. Remove it altogether to simplify call sites.
> Remove debug_line_info argument from DwarfResolver::open() constructor

- capi/Cargo.toml
Similar to what we did for the main crate with commit a5c4ef57a36b ("Don't create features for various dependencies"), use the 'dep:' syntax for specifying dependencies that we do not need to expose as features.
> capi: Don't create features for various dependencies

- cli/Cargo.toml
Add categories and features to Cargo.toml so that the program can be discovered more easily on crates.io.
> cli: Add categories & features to Cargo.toml

- src/dwarf/resolver.rs
- src/dwarf/units.rs
In addition to the `Function` reference, return a `Unit` reference from `dwarf::Units::find_function()` instead of the `Language` previously returned. Doing so will allow for better reuse of data down the line.
> Adjust dwarf::Units::find_function() to return a Unit

- src/breakpad/resolver.rs
- src/dwarf/resolver.rs
- src/dwarf/units.rs
- src/elf/resolver.rs
- src/gsym/resolver.rs
- src/inspect/inspector.rs
- src/kernel.rs
- src/ksym.rs
- src/resolver.rs
- src/symbolize/mod.rs
- src/symbolize/perf_map.rs
- src/symbolize/symbolizer.rs
The SymResolver trait contains two methods used to fulfill symbolization requests: find_sym() unearths basic information about the symbol such as its name, address, and size, and find_code_info() reports additional source code level information, if present.
This split is rather arbitrary and it can be the cause of inefficiencies. Specifically, source code information may be co-located with symbol information and by having this two-way split we may need to perform the same lookup twice. This is obviously the case already in the Breakpad resolver, but it is actually also happening in a more convoluted way in the DWARF logic.
The only conceivable reason why such a split may have been desired in the past in the first place, is to "refine" symbol information from one source with that of …
> Merge SymResolver::find_code_info() into SymResolver::find_sym()

- src/symbolize/mod.rs
It should be sufficient to restrict visibility of the overall IntSym type to prevent it from leaking outside the crate, but there is no need to restrict member visibility to the same level. Just make the members public.
> Declare IntSym members public

- src/breakpad/resolver.rs
- src/dwarf/resolver.rs
- src/elf/resolver.rs
- src/gsym/resolver.rs
- src/kernel.rs
- src/ksym.rs
- src/resolver.rs
- src/symbolize/mod.rs
- src/symbolize/perf_map.rs
- src/symbolize/symbolizer.rs
With recent refactorings, the signature of the `SymResolver::find_sym()` method has become rather...convoluted. Now that `SymResolver::find_code_info()` is no more, the need for keeping source code location information separate from the symbol data has vanished. This change adds a `AddrCodeInfo` member to the `IntSym` type to reflect that fact and simplify the signature of `SymResolver::find_sym()`.
> Add AddrCodeInfo member to IntSym

- src/breakpad/resolver.rs
- src/dwarf/resolver.rs
- src/elf/resolver.rs
- src/gsym/resolver.rs
- src/ksym.rs
- src/symbolize/mod.rs
- src/symbolize/perf_map.rs
- src/symbolize/symbolizer.rs
Ever since we added Gsym inline function reporting support, we had to do this weird dance of bubbling up a AddrCodeInfo object which we then use to fix up reported symbol names conditionally. That was necessary due to...the unnecessary split between SymResolver::find_code_info() and SymResolver::find_sym().
Now that this split is no longer present, this change moves the inlined function information data directly into the IntSym type. Once we do that, we can move the symbol name fixup to exactly the place where it is needed: inside the GsymResolver. That in turn simplifies the logic in Symbolizer::symbolize_with_resolver() in a major way and just generally concentrates related bits of functionality in a single location instead of spreading them over multiple places. It also means that our …
> Simplify source code location reporting logic

- src/breakpad/resolver.rs
- src/elf/resolver.rs
- src/gsym/resolver.rs
- src/inspect/inspector.rs
- src/inspect/mod.rs
- src/kernel.rs
- src/ksym.rs
- src/resolver.rs
- src/symbolize/perf_map.rs
Ever since the beginning of time, most internals have evolved around the SymResolver trait. As we double down on providing inspection functionality (such as iteration over all symbols), this trait felt more a more like the wrong abstraction. The reason being that some symbol sources basically by design don't support such inspection. That led to shenanigans such as methods being effectively unimplemented, but returned an error, which then meant that we needed tests for this unimplemented functionality, to not have abysmal code coverage numbers. Long story short, the SymResolver trait as-is, is not quite the right abstraction.
This change takes a first step towards mitigating this issue. Specifically, we factor out the Inspect trait, which encapsulates the already present inspection …
> Factor out Inspect trait

- src/breakpad/resolver.rs
- src/elf/resolver.rs
- src/gsym/resolver.rs
- src/kernel.rs
- src/ksym.rs
- src/lib.rs
- src/resolver.rs
- src/symbolize/mod.rs
- src/symbolize/perf_map.rs
- src/symbolize/symbolizer.rs
The SymResolver trait now solely caters to address symbolization use cases. Rename it to Symbolize to reflect that fact better. Furthermore, move it into the symbolize module fortify this property further.
> Rename SymResolver to Symbolize and move it into symbolize module

- src/gsym/resolver.rs
- src/symbolize/symbolizer.rs
With commit e016426cfcfd ("Remove dependency on circular crate") we switched over to memory mapping breakpad source files and then parsing data directly from that mapped memory as opposed to reading everything into a buffer first using "regular" file IO.
On top of simplifying the logic tremendously, this switch turns out to have another positive side-effect: we no longer have to necessarily allocate the symbol data that we hand out, because we use zero-copy parsing and can just reference memory mapped data directly. To that end, this change switches us over to using the "cached" resolver variant on the breakpad symbolization path, which will cause elimination of unnecessary allocations.
> Hand out cached results for breakpad symbolization

- src/elf/parser.rs
- src/elf/resolver.rs
- src/symbolize/mod.rs
Adjust the signature of the ElfParser::find_sym() method to mirror that of Symbolize::find_sym(). Doing so makes for easier interoperability internally.
> Adjust ElfParser::find_sym() signature to mirror Symbolize::find_sym()'s

- src/dwarf/resolver.rs
- src/elf/parser.rs
- src/elf/resolver.rs
- src/kernel.rs
- src/normalize/buildid.rs
- src/normalize/normalizer.rs
- src/symbolize/symbolizer.rs
- src/zip.rs
Move the file name (or rather: path) of the ELF object operated on from the ElfResolver type into ElfParser. Right now this is the most appropriate location to store it.
> Move file name from ElfResolver into ElfParser

- src/elf/resolver.rs
The find_addr_impl() function inside of ElfResolver::find_addr() is no longer necessary. Remove it.
> Remove internal impl method from ElfResolver::find_addr()

- src/breakpad/resolver.rs
- src/dwarf/resolver.rs
- src/elf/parser.rs
- src/elf/resolver.rs
- src/inspect/inspector.rs
- src/inspect/mod.rs
- src/ksym.rs
The for_each() symbol iteration functionality is currently pretty ad-hoc, with each type having their own variant. Let's unify everything and move it into the Inspect trait, so that we have a bit more structure.
> Make for_each functionality part of Inspect trait

- src/elf/parser.rs
- src/elf/resolver.rs
- src/symbolize/mod.rs
- src/symbolize/symbolizer.rs
This change factors out the TranslateFileOffset trait, which provides the ability to map file offsets into virtual offsets. We use it to encapsulate the existing elf_offset_to_address() functionality in a more convenient interface (though right now this is all an implementation detail and could change at any time).
> Introduce TranslateFileOffset trait

- CHANGELOG.md
- src/symbolize/symbolizer.rs
There isn't really a convincing case for having a Clone impl for the symbolize::Builder type. Remove it.
> Remove Clone impl from symbolize::Builder

- CHANGELOG.md
- src/dwarf/resolver.rs
We have seen cases where symbolization performance with especially large (10+ GiB) DWARF binaries lacks behind that of llvm-symbolizer. The profile has shown excessive effort being exerted handling abbreviations. What likely is happening on those binaries is that the debug information is not particularly optimized and so abbreviations may end up being duplicated among compilation units, causing them to be reevaluated anew frequently [0].
This is a more or less common problem and to that end gimli even provides the means for managing a cache of said abbreviations. Enable it.
```
$ ls -lh service
> -rwxr-xr-x 1 nobody nogroup 11G XXXX-XX-XX XX:XX service
Before:
$ time blazecli symbolize elf --path service  0x2d0bff94
> 0x0000002d0bff94: [...]
> …
```
> Populate and use abbreviation cache when parsing DWARF

- .github/workflows/test.yml
- examples/backtrace.rs
Start exercising examples that don't need user input in CI, to make sure that they still work as expected. While at it, fix up the backtrace example, which somehow was using the wrong input address type.
> Start running examples in CI

- build.rs
- capi/src/inspect.rs
- capi/src/symbolize.rs
- src/dwarf/resolver.rs
- tests/blazesym.rs
The name of the `test-stable-addresses-dwarf-only.bin` binary is a bit confusing and will actively cause conflicts in the future. The binary does contain ELF and DWARF bits, but the ELF symbols tables have been stripped.
Make that a bit more obvious by renaming it to `test-stable-addresses-stripped-elf-with-dwarf.bin`.
> Rename test-stable-addresses-dwarf-only.bin binary

- src/breakpad/parser.rs
We have gotten reports of a crash caused by numeric overflow when attempting to parse a Breakpad file. The reason lies in the error conversion functionality that nom provides. Specifically, the nom::error::convert_error() function expects errors with a context that derefs to an str slice. In order to fulfill that contract we convert everything to Cow<str>.
However, the function also implicitly assumes that substrings belong to the same input slice. That is not the case, and cannot be easily fixed, because there is no sane way of "relocating" arbitrary byte slice after a lossy string conversion. The requirement of derefing into a str while *also* mapping to byte slices and are assumed to be subslices of each other just seems plain broken.
This change imports a copy of the convert_error() …
> Fix potential panic when reporting nom errors

- capi/src/lib.rs
We were lacking the necessary NUL termination in the "error" string reported for the `BLAZE_ERR_OK` constant. Add it.
> capi: Make sure to NUL terminate "success" error string

- CHANGELOG.md
- src/error.rs
Add a Display impl for the ErrorKind enum. We already have Display impls for all Reason types provided by the crate, and ErrorKind is very similar in nature. Also, std::io::ErrorKind has a Display impl and it makes sense for us to behave similarly.
> Add Display impl for ErrorKind

- src/breakpad/parser.rs
Our `stringify_error()` helper as defined in the Breakpad logic still uses nom's `Offset` logic, which assumes that all input slices are sub-slices of each other. However, one of the tests did not actually uphold this invariant. Fix it.
> Use correct input slice in nom error conversion test

- src/elf/resolver.rs
As it turns out the `ElfResolver::parser()` method, by now, is used only in the `elf/resolver.rs` module itself. Make sure that it stays that way by making it private.
> Make ElfResolver::parser() private

- CHANGELOG.md
- Cargo.toml
- README.md
- capi/CHANGELOG.md
- capi/Cargo.toml
- cli/CHANGELOG.md
- cli/Cargo.toml
- cli/README.md
- examples/gsym-in-apk/Cargo.toml
- examples/sym-debuginfod/Cargo.toml
This change bumps the version of the crate to 0.2.0-alpha.12.
> Bump version to 0.2.0-alpha.12

- cli/CHANGELOG.md
- cli/Cargo.toml
This change bumps blazecli's version to 0.1.4. The following notable changes have been made since 0.1.3:
- Added 'inspect' command
- Bumped blazesym dependency to 0.2.0-alpha.12
> cli: Bump version to 0.1.4

- capi/CHANGELOG.md
- capi/include/blazesym.h
- capi/src/lib.rs
- capi/src/normalize.rs
- src/normalize/mod.rs
This change introduces the `blaze_normalize_reason_str()` helper function that can be used to retrieve a textual representation of a reason for a normalization failure.
> capi: Introduce blaze_normalize_reason_str() helper function

- src/elf/resolver.rs
Similar to what we did in commit 2ed468d2ffcb ("Fall back to using debug link parser for Inspect::find_addr()"), adjust ElfResolver::find_sym() to directly dispatch to DwarfResolver or ElfParser, but not to have some weird conditional logic in there. This is now possible, because the DwarfResolver will automatically fall back to its internal ELF parser. Without this change we may end up consulting the ELF parser twice for the same input address, which is unnecessary.
> Simplify ElfResolver::find_sym()

- build.rs
- src/dwarf/resolver.rs
- tests/blazesym.rs
Similar to what we did in commit 2ed468d2ffcb ("Fall back to using debug link parser for Inspect::find_addr()"), adjust DwarfResolver::find_sym() to use the debug link ELF parser as a first fall back, if present.
> Fall back to using debug link parser for DwarfResolver::find_sym()

- CHANGELOG.md
We have cut a release before debug link support landed. As such, the CHANGELOG entry it made should go into a new Unreleased section. Adjust it accordingly.
> Fix up CHANGELOG entry for debug link support

- README.md
With commit 1f00b7976162 ("Add an example that uses debuginfod for retrieving debug information") we have support for advanced symbolization use cases as well as for plugging in debuginfod specifically. Tick off the road map item.
> Tick off debuginfod road map item

- src/normalize/mod.rs
- src/symbolize/mod.rs
Fix wrong spelling of 'unsupported' in a couple of user facing strings.
> Fix typo: 'unsupprted' -> 'unsupported'

- CHANGELOG.md
- data/test-stable-addrs.c
- src/gsym/resolver.rs
- tests/blazesym.rs
Commit c1b5affa0550 ("Reuse more data between GsymResolver::find_sym() and find_code_info()") merged parts of the
GsymResolver::find_code_info() logic into GsymResolver::find_sym(). In the process it copied the address sanity check over. As it turns out this check had been subtly broken, in that it did not correctly handle zero sized symbols.
This change fixes the issue by correcting the logic for zero sized symbols.
> Fix reporting of zero sized symbols in Gsym

- src/elf/parser.rs
The ELF compression header resides inside an ELF section's actual data. As such, it may not be aligned correctly. Switch over to reading it using read_pod() to make sure that we are able to read it even if unaligned.
> Use read_pod() for reading compression header

- data/test.rs
It appears that with the switch to using rust.lld as the default linker on x86_64-unknown-linux-gnu our data/test.rs fails to link due to missing rust_eh_personality symbol. It's not 100% clear why that is, as this symbol should only have meaning when unwinding on panic (but we abort). That being said, we don't care much either way. Let's just define the symbol and move on with our lives. As long as the test binary builds we should be golden.
> Define rust_eh_personality symbol in data/test.rs

- CHANGELOG.md
- src/dwarf/resolver.rs
- src/elf/parser.rs
- src/elf/types.rs
We have seen cases where, with the debug link logic in place, we fail to read ELF section contents. The reason being in such a scenario, it is common for some ELF sections to not contain any data, despite keeping their original address and size meta data information. We just look at this meta data information to determine what data to read. What we should additionally take into consideration is the fact that the section type gets changed to NOBITS, indicating that no data is actually in the file. If this type is used, we shouldn't even attempt to read contents.
> Treat NOBITS ELF sections as containing no data

- src/symbolize/source.rs
Add a note about process symbolization being a privileged operation to the corresponding "source" type.
> Add note about process symbolization being privileged

- src/symbolize/mod.rs
- src/symbolize/symbolizer.rs
Our tracing span for the Symbolizer::symbolize() method always occupy multiple lines, because we use the "pretty" formatting in order to force 0x prefixes for hexadecimal values, but that also causes arrays to be formatted across multiple lines. That is super annoying. Until Rust supports specifying formatting attributes for individual nested components (there is a Rust issue somewhere...), we have to hand roll some logic to fix this issue.
> Niceify tracing output

- cli/src/main.rs
Our span output can get somewhat lengthy. Omit the "target" from said output to shorten it slightly.
> cli: Omit "target" from tracing output

- src/dwarf/resolver.rs
- src/error.rs
It's confusing to reference the std::error::Error trait via the StdError import as well as via error::Error. Switch to using StdError throughout the file.
> Use StdError import more

- src/inspect/inspector.rs
Introduce a proper span around the Inspector::lookup() method, to better support tracing use cases.
> Add span around Inspector::lookup()

- build.rs
Introduce the cc_test_so() helper function in order to get rid of all the arguments necessary for compiling this test binary.
> Factor out `cc_test_so()` helper function

- src/gsym/resolver.rs
Commit 7140f5816775 ("Fix reporting of zero sized symbols in Gsym") fixed the reporting of zero sized symbols in Gsym. However, since then have seen cases where certain zero sized symbols stopped being reported that the LLVM Gsym implementation *does* report and that also common tools such as llvm-addr2line and llvm-symbolizer report. E.g.,
```
$ llvm-gsymutil --address 0x99820 libstdc++.so.6.0.29.gsym --verbose
> Looking up addresses in "libstdc++.so.6.0.29.gsym":
> FunctionInfo for 0x0000000000099820:
> [0x0000000000099000 - 0x0000000000099000) "_init"
>
> LookupResult for 0x0000000000099820:
> 0x0000000000099820: _init + 2080
```
We have confirmed that this behavior is indeed intentional and with this change we relax our checks accordingly, to follow this behavior and be more liberal …
> Report Gsym symbols with size = 0 even if addresses don't match

- src/breakpad/parser.rs
- src/breakpad/types.rs
- src/dwarf/resolver.rs
- src/dwarf/units.rs
- src/elf/parser.rs
- src/file_cache.rs
- src/gsym/inline.rs
- src/gsym/linetab.rs
- src/gsym/parser.rs
- src/kernel.rs
- src/ksym.rs
- src/mmap.rs
- src/normalize/user.rs
- src/symbolize/perf_map.rs
- src/util.rs
- src/zip.rs
Switch various methods from having 'pub' visibility to 'pub(crate)' in order to prevent accidental leakage but also to reduce the amount of confusion.
> Declare various methods as pub(crate)

- CHANGELOG.md
- src/dwarf/debug_link.rs
- src/dwarf/mod.rs
- src/dwarf/resolver.rs
- src/elf/mod.rs
- src/elf/resolver.rs
- src/inspect/inspector.rs
- src/symbolize/symbolizer.rs
- tests/blazesym.rs
When following debug links, we currently have a hard-coded list of directories that we search. Users may reasonably want to have control over this list and so with this change we make sure to expose a knob to influence the contents. This list is a property of the symbolizer instance, as opposed to a per-request one. If we were to make it a per-request thing we'd need to parametrize all our caches with it, which seems undesirable. Conceptually, the set of directories should be easy to infer and it should be static in many if not all cases.
> Make debug directories to search configurable

- src/symbolize/symbolizer.rs
Code coverage showed easy to fix gaps in our unit tests. Add tests for the "hexification" of address arrays as well as the failure path of the internally used create_apk_elf_path() helper function.
> Add two more unit tests

- src/symbolize/symbolizer.rs
- src/util.rs
Move the Hexify helper type into the util module -- as less opinionated location for this reusable functionality.
> Move Hexify type into util module

- src/normalize/normalizer.rs
Use the Hexify helper in the Normalizer traces and use the same "opt-in" scheme for fields to report as we do in the Symbolizer.
> Use Hexify helper in Normalizer traces

- src/symbolize/symbolizer.rs
- tests/blazesym.rs
All our `Builder` methods allow for resetting a previously set value, but the recently introduced `set_debug_dirs()` does not currently. Adjust the method's signature to accept an `Option` to make such resetting possible.
> Adjust symbolize::Builder::set_debug_dirs() to accept Option

- capi/CHANGELOG.md
- capi/src/lib.rs
- capi/src/normalize.rs
- capi/src/symbolize.rs
- src/symbolize/mod.rs
As it turns out, C does not necessarily require natural alignment for primitive data types [0]. It is certainly more relaxed than Rust [1] in this respect, and that can be a source of problem when it comes to interoperability.
With this change we add support for working with potentially unaligned input addresses. We do so by taking necessary steps to read unaligned data into a temporary buffer and working on said temporary buffer.
[0] https://en.wikipedia.org/w/index.php?title=Data_structure_alignment&oldid=1209741102#Typical_alignment_of_C_structs_on_x86
[1] https://doc.rust-lang.org/reference/type-layout.html#primitive-data-layout
Closes: #678
> capi: Support working with potentially unaligned input arrays

- src/normalize/user.rs
Exclude some more APK specific code from being included in the crate if the 'apk' feature is disabled. This mirrors similar conditionals that we have on the symbolization path.
> Make more APK related paths conditional on 'apk' feature

- .github/workflows/publish-capi.yml
The publish workflow for the blazesym-c crate was changing to the wrong directory when attempting to retrieve the crate version. Fix up the path to make tag creation work as it should.
> Fix blazesym-c publish workflow

- capi/include/blazesym.h
- capi/src/symbolize.rs
- src/symbolize/mod.rs
The Sym/blaze_sym types are used in symbolization contexts, not normalization. Adjust the documentation comment accordingly.
> Fix typo normalizing -> symbolizing

- capi/src/inspect.rs
- capi/src/lib.rs
- capi/src/normalize.rs
- capi/src/symbolize.rs
- capi/src/util.rs
Move a bunch of utility functionality into the newly introduced util module. In so doing we make CI test everything in this module under Miri.
> capi: Factor out util module

- src/lib.rs
Enable the 'clone_on_ref_ptr' Clippy lint, which flags the usage of .clone() syntax on reference counted pointers. The more explicit Rc::clone() syntax is preferable in many cases, because it will invalidate the code should the Rc be removed, instead of unintentionally causing creation of a potentially expensive deep clone.
> Enable clippy::clone_on_ref_ptr lint

- cli/CHANGELOG.md
- cli/src/args.rs
- cli/src/main.rs
Introduce the --debug-dirs option to the 'symbolize elf' sub-command. This option can be used to adjust the directories being used when searching for target files of debug links.
```
$ cargo run -p blazecli -- symbolize elf --path /tmp/test-stable-addrs-stripped-with-link.bin 0x2000100
> 2024-06-03T22:27:33.408437Z  WARN debug link references destination `test-stable-addrs-dwarf-only.dbg` which was not found in any known location
> 0x00000002000100: <no-symbol>
$ cargo run -p blazecli -- symbolize elf --path /tmp/test-stable-addrs-stripped-with-link.bin 0x2000100 --debug-dirs data/
> 0x00000002000100: factorial @ 0x2000100+0x0 data/test-stable-addrs.c:10:27
```
> cli: Add --debug-dirs option to symbolize elf sub-command

- capi/CHANGELOG.md
- capi/Cargo.toml
- capi/include/blazesym.h
- capi/src/symbolize.rs
Make the list of debug directories configurable, similar to what commit e62caa983763 ("Make debug directories to search configurable") did for the Rust crate.
> capi: Make debug directories to search configurable

- .github/workflows/test.yml
- Cargo.toml
- capi/Cargo.toml
- capi/src/inspect.rs
- capi/src/util.rs
- src/insert_map.rs
- src/util.rs
The way we specify the tests to run under Miri is error-prone at best. Basically, we roughly group eligible tests into modules or hard code function names of suitable functions inside the CI configuration. This is prone to result in missed tests (if somebody renames a test and forgets to adjust the CI script). It is also non-obvious from the code what is happening and that makes it much less likely that new tests are onboarded to run there. Lastly, because we establish a grouping by module (to minimize maintenance burden of naming dozens of tests in the CI configuration), we end up with attributes such as `#[cfg_attr(miri, ignore)]` for opting out.
With this change we switch over to using the test-tag crate for tagging Miri tests as such, which will make it much easier to onboard new …
> Use test-tag crate for tagging Miri tests

- capi/include/blazesym.h
- capi/src/symbolize.rs
The blaze_symbolize_*() functions don't really return an array of blaze_result objects. Reword the documentation accordingly.
> capi: Reword documentation of blaze_symbolize_*()

- capi/src/inspect.rs
- capi/src/symbolize.rs
Now that we are tagging tests eligible for running under Miri it is much easier to onboard new ones. Add a bunch.
> capi: Run more tests in Miri

- src/error.rs
- src/ksym.rs
- src/maps.rs
- src/resolver.rs
Now that we are tagging tests eligible for running under Miri it is much easier to onboard new ones. Add a bunch.
> Run more tests in Miri

- capi/src/normalize.rs
Shorten the normalization reason code & tests a bit by glob importing the blaze_normalize_reason variants.
> capi: Shorten normalization reason code/tests a bit

- capi/CHANGELOG.md
- capi/include/blazesym.h
- capi/src/symbolize.rs
- src/symbolize/mod.rs
This change introduces the blaze_symbolization_reason enumeration to blazesym-c and adjusts the blaze_sym type to carry such a reason. We also introduce the blaze_symbolization_reason_str() helper function that can be used to retrieve a textual representation of a reason for a symbolization failure.
> capi: Add `blaze_symbolization_reason` enum

- src/gsym/inline.rs
- src/gsym/linetab.rs
- src/util.rs
As it turns out, the Rust compiler uses variable length LEB128 encoded integers internally. It so happens that they spent a fair amount of effort micro-optimizing the decoding functionality [0] [1], as it's in the hot path.
With this change we replace our decoding routines with these optimized ones. To make that happen more easily (and to gain some base line speed up), also remove the "shift" return from the respective methods. As a result of these changes, we see a repsectable speed up:
Before:
```
test util::tests::bench_u64_leb128_reading  ... bench:  128 ns/iter (+/- 10)
```
After:
```
test util::tests::bench_u64_leb128_reading  ... bench:  103 ns/iter (+/- 5)
```
Gsym decoding, which uses these routines, improved as follows:
```
main/symbolize_gsym_multi_no_setup
time:   [146.26 µs …
```
> Optimize LEB128 data reading

- src/lib.rs
- src/symbolize/symbolizer.rs
- src/test_helper.rs
Factor out a new test-only module containing helper functionality, test_helper, and move the find_the_answer_fn() function into it. This way, we will be able to reuse it from various tests instead of duplicating the logic all over the place.
> Factor out test_helper module

- Cargo.toml
- capi/src/normalize.rs
With commit a12675902d7d ("capi: Onboard yet more tests to Miri") we removed the usage of the elf_conversion() test function in some of the normalization tests, because the test-tag::tag attribute didn't make the function accessible under at the top level.
Version 0.1.3 of the crate rectified this short coming and with this change we update to it and revert the relevant changes of the commit.
> capi: Partially revert a12675902d7d

- build.rs
- data/test-so.map
- src/elf/parser.rs
We may not be able to determine a file offset for each symbol in an ELF file. For example, when using version scripts many linkers emit zero sized symbols such as GLIBC_2.2.5 as version markers into a binary. Those are marked as type "absolute" and have a value ("address") of zero.
Currently we bail out hard when attempting to calculate the file offset for such a symbol: the section index would be SHN_ABS (0xfff1) and such a section will not be found.
Logically, the address zero cannot be a valid file offset, because that's where the ELF header resides, so we need to build in optionality into the file offset retrieval. With this change we do just that, and bulk ignore symbols with any reserved section indices, including SHN_ABS.
> Be more forgiving when attempting to calculate file offset

- CHANGELOG.md
- Cargo.toml
- README.md
- capi/CHANGELOG.md
- capi/Cargo.toml
- cli/CHANGELOG.md
- cli/Cargo.toml
- cli/README.md
- examples/gsym-in-apk/Cargo.toml
- examples/sym-debuginfod/Cargo.toml
This change bumps the version of the crate to 0.2.0-rc.0. We should already have stopped using the "alpha" version suffix a while back, as the library has been running in production in several services for some time now. But be that as it may, at this point we are getting ready for the 0.2 release and right now we do not foresee any more breaking changes to the API surface before that. So it seems reasonable to start tagging release candidates.
> Bump version to 0.2.0-rc.0

- cli/CHANGELOG.md
- cli/Cargo.toml
This change bumps blazecli's version to 0.1.5. The following notable changes have been made since 0.1.4:
- Added --debug-dirs option to 'symbolize elf' sub-command
- Bumped blazesym dependency to 0.2.0-rc.0
> cli: Bump version to 0.1.5

- capi/CHANGELOG.md
- capi/Cargo.toml
- capi/include/blazesym.h
This change bumps the blazesym-c's version to 0.1.0-rc.0. The following notable changes have been made since 0.1.0-alpha.1:
- Added debug_dirs attribute to blaze_symbolizer_opts
- Added cache_maps attribute to blaze_normalizer_opts
- Introduced blaze_err enum and adjusted all fallible functions to set a thread local error
- Introduced blaze_err_last to retrieve the last error
- Introduced blaze_err_str function to convert errors to textual representation
- Introduced blaze_normalize_opts and added blaze_normalize_user_addrs_opts to use it
- Removed blaze_normalize_user_addrs_sorted function
- Introduced blaze_normalize_reason type
- Added reason attribute to blaze_user_meta_unknown
- Added blaze_normalize_reason_str to retrieve textual representation
- Introduced blaze_symbolize_reason …
> capi: Bump version to 0.1.0-rc.0

- Cargo.toml
So far the tracing dependency created an implicit feature. Switch over to declaring it explicitly instead, to make it more obvious what is going on and to document it better.
> Introduce explicit 'tracing' feature

- data/test-stable-addrs.ld
- tests/blazesym.rs
Both lld and gold fail to work with our linker script properly. The former insists on at least .shstrtab not being discarded and the latter barks about some supposed segment overlap.
Silence both by making the corresponding changes. Doing so will give us more flexibility down the line.
> Make linker script compatible with lld and gold linkers

- build.rs
Introduce the change_ext() helper function for adjusting the extension present in a Path more conveniently than is currently possible.
> Introduce change_ext() helper function

- data/test-stable-addrs.ld
Copy over more of the DWARF related debug section definitions from the default ld linker script into our custom one, to make sure that we do not loose debug information.
> Include more debug related sections in test-stable-addrs.ld

- build.rs
Adjust the toolize_impl() function to require a full path to the destination file. Doing so will allow us to make the function work properly with multiple input files, which could conceivably reside in different directories.
> Adjust toolize_impl() to require full destination path

- src/symbolize/perf_map.rs
- src/test_helper.rs
With Rust 1.79, clippy warns about a missing transmute annotation. Add it to silence the warning.
> Fix clippy reported warning

- capi/Cargo.toml
- capi/src/symbolize.rs
set_debug_dirs is gated by feature "dwarf" in symbolize::Builder. I got below error if the "dwarf" feature is not enabled.
```
error[E0599]: no method named `set_debug_dirs` found for struct
`blazesym::symbolize::Builder` in the current scope
--> capi/src/symbolize.rs:632:21
|
632 |             builder.set_debug_dirs(Some(iter))
|                     ^^^^^^^^^^^^^^ method not found in `Builder`
```
> capi: only set_debug_dirs when dwarf feature enabled

- .github/workflows/test.yml
- capi/src/symbolize.rs
Make sure that we have a job that builds `blazesym-c` without features in CI, to catch any regressions there.
> capi: Build without features in CI

- src/dwarf/function.rs
- src/dwarf/lines.rs
- src/dwarf/location.rs
- src/dwarf/range.rs
- src/dwarf/unit.rs
- src/dwarf/units.rs
Switch over to using gimli::UnitRef as a replacement for the various gimli::Unit & Units tuples that we pass around. We still need Units in some places, but we can now remove its dwarf() method, which exposed a gimli::Dwarf object, which may be problematic in the context of split DWARF support.
> Use gimli::UnitRef

- src/normalize/user.rs
Since commit d906c3dea79a ("Introduce normalize::Reason enum") the private UserOutput::add_unknown_addr() method's doc comment has been out of date. Adjust it to reflect the new reality.
> Adjust documentation of UserOutput::add_unknown_addr()

- capi/CHANGELOG.md
- capi/include/blazesym.h
- capi/src/symbolize.rs
Rename the blaze_result type to blaze_syms, which more aptly reflects the intention and will help with future API extensions. Furthermore rename blaze_result_free() to blaze_syms_free() to preserve consistency.
> capi: Rename blaze_result to blaze_syms

- capi/src/symbolize.rs
convert_symbolizedresults_to_c() is a fallible function, but so far we have not checked its result but just returned it straight away. That can result in a NULL pointer being returned without an error code set. Despite being highly unlikely (Rust code would just panic earlier on allocation failure) as it's only our C layer that handles these situations more gracefully, this is not ideal and counter to our stated contract.
Make sure to check the function's return value and set the last error accordingly.
> capi: Bubble up blaze_syms allocation errors properly

- capi/src/inspect.rs
- capi/src/symbolize.rs
We store the size of the allocated result buffer inside the buffer itself, except that this size does not contain the eight bytes used for storing said size. As a result, we have to add these eight bytes to the buffer size on both the allocation as well as the deallocation path. There is no reason for *not* just storing the full allocation size and eliminate this additional calculation from the deallocation path -- so do just that.
> capi: Perform result buffer size calculation only once

- src/error.rs
Because of accounting changes we dropped below the 95% code coverage mark. Get us back on track with some trivial tests checking error kind reporting.
> Add tests for error kind reporting

- src/error.rs
- src/normalize/user.rs
It can be mildly confusing to have Error implicitly refer to std::io::Error given that the crate has its own error type. Make it more explicit that std::io::Error is used.
> Use io::Error via std::io import

- CHANGELOG.md
- capi/include/blazesym.h
- capi/src/normalize.rs
- src/normalize/buildid.rs
- src/normalize/meta.rs
- src/normalize/normalizer.rs
- src/normalize/user.rs
So far any failures to read the build ID as part of an address normalization request have short-circuit the entire operation. While somewhat reasonable behavior in principle, the result will be that such a read failure for one of the files can fail normalization for others, which isn't really behavior that we are striving for. Rather, because we support batched symbolization, we should report the failure at the level of an individual address.
For build IDs specifically, we already have to work with files not containing a build ID and so the most sensible behavior is to just map read failures to a non-existent build ID.
> Swallow build ID read failures

- src/normalize/meta.rs
- src/symbolize/symbolizer.rs
Add a test covering the symbolization of maps "entries" without a path as well as with a "component" (as opposed to a file).
> Add test for symbolization of additional "entry" types

- Cargo.toml
From the looks of it, the zip crate once again has managed to break its alignment logic with the release of version 2.1.4. Restrict the version we support for the time being.
> Restrict zip dependency to <2.1.4

- Cargo.toml
Update the gimli dependency to version 0.31 to get the latest and greatest. Bump addr2line alongside, as the two have to be updated in tandem.
> Update gimli dependency to 0.31

- .github/workflows/test.yml
- benches/normalize.rs
- benches/symbolize.rs
- capi/benches/normalize.rs
- capi/src/normalize.rs
- src/lib.rs
- src/normalize/normalizer.rs
- src/symbolize/perf_map.rs
- src/util.rs
- tests/allocs.rs
- tests/blazesym.rs
- tests/common/mod.rs
- tests/permission.rs
- tests/permissionless.rs
Now that we started supporting Windows in a very limited capacity, add the necessary infrastructure for starting to run tests on it. As a first step, we test symbolization of addresses in ELF files.
> Start running subset of tests on Windows

- .github/workflows/test.yml
- tests/blazesym.rs
Enable the 'symbolize_elf_stripped' test for running on Windows.
> Onboard 'symbolize_elf_stripped' test to running on Windows

- .github/workflows/test.yml
- CHANGELOG.md
- README.md
- tests/blazesym.rs
Enable more tests to run on the Windows target. This should provide us with some confidence that basic workings of ELF, DWARF, Gsym, and Breakpad symbolization are working on Windows.
> Run more tests on Windows

- .github/workflows/test.yml
It should be pretty unlikely that tests break on Windows but not on other targets. As such, the regular and merge delaying testing on every pull request for this target seems unnecessary -- especially given that it takes quite a bit longer than running tests on Linux. As such, only run Windows based tests on push to the main branch.
> Only run Windows tests on push to main

- capi/include/blazesym.h
- capi/src/symbolize.rs
- src/elf/parser.rs
With Rust 1.80, clippy complains about some supposedly unnecessary borrow. Except it isn't unnecessary at all, as removing it causes a compilation failure. Silence the nonsense.
> Silence clippy reported "issue"

- CHANGELOG.md
- src/breakpad/parser.rs
Our breakpad parser supports various CFI directives and other constructs, despite never actually using them. That is partly necessary: we need to recognize them in order to ignore them. However, we don't have to go all the way and parse them correctly. Rather, we can just skip over them more quickly. Adjust the code to do just that. As a result, we are a bit more lenient in what we accept (except for spurious empty lines that we now no longer accept...), but nobody should be using our parser to judge validity of a file, so being more accepting is fine. As a result, we speed up parsing of breakpad files that contain quite significantly:
```
> main/symbolize_breakpad
>   time:   [245.08 ms 245.62 ms 246.20 ms]
>   change: [−12.182% −11.608% −11.143%] (p = 0.00 < 0.02)
>   Performance has …
```
> Improve Breakpad file parsing performance

- LICENSE
It confusing and a maintenance nightmare to have copyright holder names embedded in the LICENSE file. GitHub does so for MIT and BSD-3-clause license templates, but not for, say, GPLv3. Hence, it can't really be a necessity to have them there. Just remove the names. They are listed inside the individual Cargo.toml files. While at it, update the copyright year.
Reported-by: Michel Lind <salimma@fedoraproject.org>
> Remove copyright holder names from LICENSE file

- .clippy.toml
- .github/workflows/test.yml
Tell Clippy our minimum supported Rust version, in the hopes that it won't recommend changes that would cause it to be bumped.
> Make Clippy aware of MSRV

- src/util.rs
Introduce the ReadRaw::advance() trait method, which advances the read pointer in a slice.
> Introduce ReadRaw::advance() method

- src/dwarf/debug_link.rs
Factor out the parse_debug_link_section_data() helper function from the existing read_debug_link(). This new function operates in a slice and can be unit tested more easily.
> Introduce parse_debug_link_section_data() helper function

- CHANGELOG.md
- src/dwarf/debug_link.rs
We interpreted the CRC associated with the debug link as being aligned on a four byte boundary relative to the file's start address. However, we have seen a case where that led to an invalid read of the checksum, when both the containing .gnu_debuglink section had no alignment and the CRC was at an unaligned offset as well.
What the specification actually says is that the checksum is aligned relative to the section start. In most cases the outcome is the same, but it may not be if the section itself is unaligned. This change fixes up our logic to treat alignment as given in relation to the start address of the section, not the file.
Closes: #769
> Interpret debug link CRC alignment as relative to section start

- src/dwarf/debug_link.rs
The unaligned_debug_link_parsing() test does not perform any I/O. As such, it is fine to be run under Miri. Do just that.
> Run unaligned_debug_link_parsing() under Miri

- Cargo.toml
Loosen the zip version requirements now that a fix has landed.
This reverts commit aab845abc0df3f01df96bd2b5de4907e5a76f43a.
> Revert "Restrict zip dependency to <2.1.4"

- src/normalize/normalizer.rs
We repeated some doc comments in the Normalizer and Builder types, which makes them unnecessarily hard to maintain.
Deduplicate things a bit to reduce the maintenance burden.
> Deduplicate doc comments in Normalizer

- README-devel.md
It's not obvious how to generate the documentation as it would appear on docs.rs once a release is cut. To that end, dedicate a section in README-devel to the topic.
> Add note about how to generate documentation to README-devel

- src/once.rs
Recent version of Rust seem to be unhappy with our attempt of "handling" the Result::Err variant:
```
> error: unreachable pattern
>   --> src/once.rs:98:13
>    |
> 98 |             Err(_) => unsafe { unreachable_unchecked() },
>    |             ^^^^^^
>    |
>    = note: this pattern matches no values because `Infallible` is uninhabited
>    = note: `-D unreachable-patterns` implied by `-D warnings`
>    = help: to override `-D warnings` add `#[allow(unreachable_patterns)]`
```
That is of course correct, and yet practically speaking utter nonsense. We can't just ignore the Err(_) pattern because that violates match semantics.
Allow the lint.
> Allow 'unreachable_patterns' lint in once.rs

- src/normalize/normalizer.rs
The libc crate doesn't have the `__errno_location` variable on Arm, requiring repeated massaging of code whenever we need to run tests there. Just exclude the test in question when building for this target.
> Exclude user_address_normalization() test on Arm

- CHANGELOG.md
- capi/CHANGELOG.md
- capi/include/blazesym.h
- capi/src/helper.rs
- capi/src/lib.rs
- capi/src/normalize.rs
- src/lib.rs
- src/normalize/ioctl.rs
- src/normalize/mod.rs
- src/normalize/normalizer.rs
Add a way to check for support of the PROCMAP QUERY ioctl via the public is_procmap_query_supported() helper. On an otherwise unknown system, this function allows to selectively enable (or disable) the usage of the corresponding code paths.
> Introduce is_procmap_query_supported() helper

- src/maps.rs
- src/normalize/ioctl.rs
- src/normalize/user.rs
- src/symbolize/symbolizer.rs
The "mode" thingy that we use in our VMA handling logic is not exactly a joy to deal with: there is barely any type safety and the bit ordering is hard to remember.
Replace it with a proper alternative supporting all the basic operations that we need and that allows us to make the code more expressive via use of aptly named constants. In the process we get rid of the "shared" or "private" flag. Since the introduction of the PROCMAP_QUERY ioctl support we have seen occasional CI failures caused by a difference of this bit between what is being being reported by the text interface versus the ioctl. Investigating the matter briefly, we concluded that the flag is indeed dynamic and may change at the discretion of the kernel. As such, it is probably wise for us to ignore it all together, as we …
> Replace ad-hoc "mode" with properly structured Perm type

- capi/include/blazesym.h
- capi/src/helper.rs
Make sure to set the last error on all paths of the blaze_supports_procmap_query() helper, not just in case of error. Also, improve documentation slightly.
> capi: Set last error on all paths of blaze_supports_procmap_query()

- capi/src/helper.rs
The recently introduced blaze_supports_procmap_query() function is reporting low coverage numbers, because we can't test error reporting of the PROCMAP_QUERY ioctl easily. Refactor it so that pretty much all lines are unconditionally executed.
> Refactor blaze_supports_procmap_query() slightly

- .github/workflows/test.yml
With release 0.14 vmtest has become unusable for us. The reason being that it turns out that with the usage of the host's /tmp/ handling of temporary files broke due to deficiencies in the 9P file system [0]. Given that by now vmtest-action@master uses this very version, our CI is broken.
To work around the issue until a permanent fix is found, pin vmtest-action to a usable SHA-1.
[0] https://github.com/danobi/vmtest/issues/83
> Pin vmtest-action to working version

- src/symbolize/perf_map.rs
Use named temporary files in our perf map tests, because they actually "require" a path to work with, which currently is just made up.
> Use named temporary files in perf map tests

- .github/workflows/build-linux.yml
- .github/workflows/test.yml
Generalize the build-linux CI workflow a bit, making it easier to reuse. Basically, we allow users to provide the repository as well as Git revision as input and the workflow will do the rest. This is just a refactoring, functionality should not change.
> Generalize build-linux CI workflow

- src/maps.rs
Most of the "bit" operations on the Perm type are tested indirectly, but the BitAndAssign impl is showing some red in the coverage report. Add explicit tests for this functionality to improve numbers slightly.
> Add test for Perm operations

- .github/workflows/build-linux.yml
We missed adjusting the cache key for the kernel in one location as part of commit 798bb5274445 ("Generalize build-linux CI workflow"), causing caching to be broken. Fix it up.
> Fix key used for kernel artifact upload

- src/maps.rs
Implement the BitAnd impl for the Perm type by reusing the existing BitAndAssign impl. This makes for slightly better code sharing.
> Implement BitAnd for Perm in terms of BitAndAssign

- CHANGELOG.md
- src/maps.rs
- src/normalize/normalizer.rs
With the introduction of the 'maps_file' option to the normalize APIs, we started reporting /proc/<pid>/.. paths as normalization results, as this information may be useful in certain out-of-band normalization contexts.
What we missed to change, though, was to resolve symbolic "PIDs" such as "self" in those paths. That is a problem, because in an out-of-band symbolization scenario, /proc/self/.. will reference something different in the process where the normalization happens versus that of the symbolization.
The more general solution is to just map self to the actual PID and with this change we do just that.
> Properly "dereference" 'self' component in normalized paths

- capi/Cargo.toml
This is needed for either
- regenerating the C header with `cargo check --package blazesym-c --features=generate-c-header`
- using `cargo-c` which generates the same header but with version info, for distribution packaging
Verify the file gets included
```
michel in blazesym/capi
$ cargo package --list --allow-dirty | grep cbindgen.toml
cbindgen.toml
```
Without `cbindgen.toml` the default language is C++ and there is no inclusion guard to make sure the header is only included once
With `cbindgen.toml`, regenerating the C header results in an identical header when building in Fedora
Diff of included header and the one `cargo-c` generates
```
michel in build/BUILD/rust-blazesym-c-0.1.0_rc.0-build
$ diff -u blazesym-c-0.1.0-rc.0/include/blazesym.h …
```
> Include `cbindgen.toml` in the published crate

- CHANGELOG.md
- capi/src/symbolize.rs
- src/normalize/meta.rs
- src/normalize/normalizer.rs
- src/normalize/user.rs
- tests/blazesym.rs
Rename the UserMeta::{apk,elf,unkown}() getters by prefixing the methods with as_. If nothing else, this is more consistent with the already present Symbolized::as_sym(), which has very similar semantics.
> Rename UserMeta getters

- src/dwarf/units.rs
- src/symbolize/perf_map.rs
- src/symbolize/symbolizer.rs
Newer versions of Rust warn about elided lifetimes that get resolved to otherwise declared ones. Use said declared ones to prevent any such warnings from showing up.
> Fix warnings about elided lifetimes

- src/symbolize/perf_map.rs
Let's follow the recommendations of the clippy::byte_char_slices lint instead of ignoring it.
> Remove clippy::byte_char_slices lint allowance

- CHANGELOG.md
- Cargo.toml
- README.md
- capi/CHANGELOG.md
- capi/Cargo.toml
- cli/CHANGELOG.md
- cli/Cargo.toml
- cli/README.md
- examples/gsym-in-apk/Cargo.toml
- examples/sym-debuginfod/Cargo.toml
This change bumps the version of the crate to 0.2.0-rc.1.
> Bump version to 0.2.0-rc.1

- CHANGELOG.md
- capi/CHANGELOG.md
- capi/Cargo.toml
- capi/include/blazesym.h
This change bumps the blazesym-c's version to 0.1.0-rc.1. The following notable changes have been made since 0.1.0-rc.0:
- Added 'procmap_query_ioctl' attribute to blaze_normalizer_opts
- Renamed blaze_result to blaze_syms
- Renamed blaze_result_free to blaze_syms_free
- Renamed 'cache_maps' attribute of blaze_normalizer_opts to 'cache_vmas'
- Introduced blaze_supports_procmap_query helper
- Bumped blazesym dependency to 0.2.0-rc.1
> capi: Bump version to 0.1.0-rc.1

- .github/workflows/build-cli.yml
- .github/workflows/publish-cli.yml
The 'Build' workflow is not very telling in its function. Rename it to 'Build blazecli' to make it more clear what it is about.
> Rename 'Build' workflow to 'Build blazecli'

- .github/workflows/build-cli.yml
- .github/workflows/publish-capi.yml
- .github/workflows/publish-cli.yml
- .github/workflows/publish.yml
Since forever we have wanted to attach statically linked binaries of blazecli to the corresponding release. However, because GitHub Actions can't seem to get their Matrix workflows interacting with anything, really, that seemed impossible to do.
This change proposes a workaround that makes each job of the matrix attach the binary to the release itself, provided that the associated input argument it set. While at it also make sure to use the --fail-with-body option in all our special-sauce curl invocations, so that errors are bubbled up properly.
> cli: Attach statically build binary to release

- .github/workflows/test.yml
Recent nightly version of Rust fail running one of our tests under Miri [0]. The claim is that data is used uninitialized, but it's not really clear why there would be anything uninitialized at this point and this test has been working fine ever since its inception. Suspicion is that nightly Miri could have a bug. And even if it's a bug in our code it would be in test code itself, rather than the library. Pin the version we use to a known good one for the time being to get us back to green.
[0] https://github.com/libbpf/blazesym/actions/runs/10842437849/job/30216935620
> Work around Miri failures

- src/lib.rs
- src/util.rs
- tests/common/mod.rs
In the future we are likely to need to share more functionality between blazesym and adjacent crates (blazecli, blazesym-c, or integration tests) to simplify our lives. As such, introduce the means for doing so and de-duplicate the existing definition of stat().
> De-duplicate definition of stat() functionality

- src/normalize/buildid.rs
Add a test for the error reporting behavior of the read_elf_build_id() helper function.
> Add test for error behavior of read_elf_build_id()

- src/symbolize/mod.rs
Increase code coverage by adding tests for the Input::map() and Input::into_inner() helper functions.
> Add tests for Input::map() helper function

- src/normalize/normalizer.rs
- src/normalize/user.rs
- tests/permissionless.rs
Addresses issue https://github.com/libbpf/blazesym/issues/821
Use the `symbolic_path` when the normalizer is configured with `map_files=false`.
When Docker container runs in unprivileged mode, even the root-user cannot access the `/proc/XX/map_files`. This prevents from `build-id`s collection in such environment.
By setting `map_files=false` (default being `true`), we instruct the normalizer to retrieve the `build-id`s using the `symbolic_path`.
same as https://github.com/libbpf/blazesym/pull/823 (closed by me by mistake)
> Allow retrieving build-ids in permissionless env

- tests/permissionless.rs
Recent changes to the "permissionless" test broke the Windows build. Fix it.
> Fix Windows test workflow

- CHANGELOG.md
Add a CHANGELOG entry for pull request #824, which change the way we read build IDs as part of address normalization when `NormalizeOpts::map_files` is set to `false`.
> Add CHANGELOG entry for #824

- capi/src/helper.rs
The test we have for the blaze_read_elf_build_id() helper function is roughly a copy of that for helper::read_elf_build_id() in Rust. However, it doesn't check all the byte copying stuff that we do to expose the C style array to callers.
This change improves the test by comparing the build ID against the one reported by the Rust API.
> capi: Improve test for blaze_read_elf_build_id() helper

- README.md
Update our roadmap outline to include more items pertaining symbolization of kernel addresses.
> Update roadmap to include more kernel symbolization items

- examples/sym-debuginfod/Cargo.toml
- examples/sym-debuginfod/main.rs
Update the sym-debuginfod example to use debuginfod 0.1.1 and work with the CachingClient::from_env() constructor specifically. In so doing we use the default location of the debuginfod data cache, which improves interoperability with other debuginfod aware programs such as gdb.
> Update sym-debuginfod example to use debuginfod 0.1.1

- Cargo.toml
- examples/inspect-mangled.rs
- src/inspect/inspector.rs
Most symbol sources store mangled symbol names. Hence, the mangled name is what the Inspector::lookup facility matches against. However, that is not always desired. Rather, sometimes filtering needs happen based on the demangled name or other information encoded in the mangled symbol (such as number of function arguments).
We support this use case via the Inspector::for_each functionality, but it's not trivially obvious that this is possible to begin with. With this change we add an example that illustrates such usage.
> Add example illustrating look up of mangled symbols

- src/dwarf/resolver.rs
Factor out the internal DwarfResolver::function_to_sym_info() helper as a means to share the logic for converting a Function object into a SymInfo.
> Factor out DwarfResolver::function_to_sym_info() helper

- src/normalize/normalizer.rs
The result of address normalization are file offsets, not virtual addresses. The documentation of the normalize::Normalizer type is outdated in that respect, presumably from times when virtual address were still reported (i.e., before commit 9f3c71344f9f ("Make normalization report file offsets")).
Adjust the documentation to mention files offset.
Reported-by: Nicolas Savoire <nicolas.savoire@datadoghq.com>
> Fix Normalizer documentation incorrectly citing "virtual addresses"

- Cargo.toml
- examples/normalize-virt-offset.rs
Add an example illustrating how to post-process the output of address normalization to have virtual offsets instead of file offsets available.
Refs: #835
> Add example illustrating normalization output post-processing

- .github/workflows/test.yml
Run two more example that work without user input as part of our regular CI checks.
> Run more examples in CI

- .github/workflows/test.yml
Running with LeakSanitizer enabled is a mess: we are seeing spurious failures in CI on completely unrelated changes to the symbolize_process_symbolic_paths test. Attempting to reproduce locally them is denied with line noise such as:
> LeakSanitizer: CHECK failed: lsan_interceptors.cpp:82 "((!lsan_init_is_running)) != (0)" (0x0, 0x0) (tid=29001)
The suspicion is that more recent version of LLVM (compared to the CI environment) are b0rked.
In any event, AddressSanitizer comes with leak detection support and so let's just use that instead -- it hasn't caused any problems and we haven't seen any issues using it locally either.
> Remove explicit LeakSanitizer usage from CI

- examples/sym-debuginfod/README.md
Fix a typo in the README of the sym-debuginfod example.
> Fix typo in README of sym-debuginfod example

- src/ksym.rs
- src/symbolize/symbolizer.rs
Introduce the KsymResolver::load_from_reader() constructor, which:
1) allows us to better test the resolver, because we can provide an
in-memory buffer
2) addresses a deficiency where, in the Symbolizer, we were effectively
circumventing our FileCache construct and re-opening the kallsyms
file by path
> Introduce KsymResolver::load_from_reader() constructor

- src/ksym.rs
The Vec contains spare capacity for future extension of the contained data, but we parse kernel symbols eagerly and then never modify them again. As such, let's just use a boxed slice which is more space efficient.
> Store boxed slice in KSymResolver

- CHANGELOG.md
- src/ksym.rs
It makes absolutely no sense for us to allocate a vector with the tokens of a line just to check its length and pick out the first three. Just use an iterator directly. This speeds up the kallsyms parsing code by a significant amount.
```
$ cargo bench --features=nightly -- bench_parse_kallsyms
> test ksym::tests::bench_parse_kallsyms  ... bench:   4,453,396.50 ns/iter (+/- 136,465.51)
```
> Speed up parsing of kallsyms data

- src/ksym.rs
We potentially store a lot of symbols inside the KSymResolver type, depending on how large kallsyms is. As such, overhead of each object has some impact. Decrease the size of each Ksym by storing a boxed str instead of a String, which eliminates a word otherwise used for the string's capacity.
> Store boxed strings in KSymResolver

- .github/workflows/test.yml
- src/file_cache.rs
Fix the Windows build for tests, which broke due to the recently added std::os::fd::AsRawFd import. Also add a CI job building tests for Windows to prevent regressions in the future.
> Fix Windows build

- .github/workflows/test.yml
- Cargo.toml
- README-devel.md
- examples/gsym-in-apk/Cargo.toml
- tests/blazesym.rs
Remove various test file generation features from the main crate. These features will from now on only be present on blazesym-dev. The reason for the removal is that the existing main-crate features are broken. Evidently, Cargo does not correctly handle dependent features if triggered via a dev-dependency. As a result, it turns out that our Windows tests were broken, because the build-test-artifacts job, by virtue of relying on the generate-unit-test-files on the main crate, was not generating and uploading the expected set of test artifacts.
> Remove various test file generation features

- cli/CHANGELOG.md
- cli/src/args.rs
- cli/src/main.rs
Add support for symbolization of kernel addresses to the program. Right now we do not expose any additional options and just rely on the "default" kernel symbolization source.
```
$ cargo run -p blazecli -- symbolize kernel 0x0000000000019008 0xffffffffc005e378
> 0x00000000019008: espfix_stack @ 0x19008+0x0
> 0xffffffffc005e378: bpf_prog_6deef7357e7b4530_sd_fw_ingress @ 0xffffffffc005e2dc+0x9c
```
> cli: Add support for symbolizing kernel addresses

- src/normalize/ioctl.rs
We are still seeing the occasional flake of the vma_comparison test, caused by a one page difference in the size of one of the memory regions.
In the hopes of achieving more of a quiesced state, sleep a bit between iterations in there.
> Sleep a bit between iterations in vma_comparison test

- .github/workflows/test.yml
We also need the various system dev-dependencies installed when running benchmarks and building Windows test artifacts. Do just that.
> Install dev-dependencies for more CI jobs

- .github/workflows/test.yml
- src/kernel/bpf/prog.rs
- src/kernel/ksym.rs
- src/symbolize/symbolizer.rs
Add benchmarks for the symbolization of BPF program kernel addresses.
```
$ cargo bench --features=nightly -- bench_symbolize_kernel
> test symbolize::symbolizer::tests::bench_symbolize_kernel_bpf_cached   ... bench:       2,154.55 ns/iter (+/- 15.81)
> test symbolize::symbolizer::tests::bench_symbolize_kernel_bpf_uncached ... bench:  24,989,552.60 ns/iter (+/- 1,066,936.44)
```
> Add benchmarks for BPF program kernel address symbolization

- CHANGELOG.md
Add a CHANGELOG entry for pull request #859, which effectively made Mac OS an "officially" partially supported operating system.
> Add CHANGELOG entry for #859

- src/kernel/bpf/prog.rs
- src/kernel/ksym.rs
- src/kernel/resolver.rs
Everything and anything pertaining kernel symbolization has been notoriously under-tested in the past. Add two tests for the KernelResolver in an attempt to start mitigating this situation somewhat and increasing our code coverage numbers.
> Add more tests for KernelResolver

- src/error.rs
Basically all error handling paths are assumed to be cold and only rarely called. Convey that to the compiler by marking two of the core ones as #[cold], so that it can try and generate better code as a result. This attribute should transitively affect all call-sites.
> Mark core Error methods as #[cold]

- capi/src/normalize.rs
- capi/src/util.rs
- cli/CHANGELOG.md
- cli/src/args.rs
- cli/src/main.rs
Introduce the --map-files option to the 'normalize user' sub-command. This option can be used to switch over to reporting '/proc/<pid>/map_files/' paths as part of the address normalization process.
```
$ cargo run -p blazecli -- normalize user --pid 13466 0x7fdf2b957000
> 0x007fdf2b957000: file offset 0x357000 in /usr/lib64/libcrypto.so.3
$ cargo run -p blazecli -- normalize user --pid 13466 0x7fdf2b957000 --map-files
> 0x007fdf2b957000: file offset 0x357000 in /proc/13466/map_files/7fdf2b957000-7fdf2ba3c000
```
> cli: Add --map-files option to normalize user sub-command

- .github/workflows/test.yml
Make sure to cross-compile not just blazesym but also blazesym-c in CI for various targets.
> Cross-compile blazesym-c in CI

- .github/workflows/test.yml
Add i686-unknown-linux-gnu as a cross-compilation target in CI to have another one representing a 32 bit system.
> Add i686-unknown-linux-gnu as CI cross-compilation target

- capi/CHANGELOG.md
- capi/cbindgen.toml
- capi/include/blazesym.h
As of commit f3c8d248a198 ("Make Addr a u64") all addresses were supposed to be represented as 64 bit integers. However, that changed did not adjust the C API bindings. Usually that would have been picked up transparently in the C header, except that cbindgen required us to explicitly specify the address type, leading to a mismatch. Fix it up.
> Fix addresses being represented as uintptr_t

- .github/workflows/build-cli.yml
- .github/workflows/test.yml
Build `blazecli` for the `i686-unknown-linux-gnu` target, now that we build the main library for it as well.
> cli: Add i686-unknown-linux-gnu build

- Cargo.toml
- build.rs
- dev/Cargo.toml
- dev/build.rs
- src/file_cache.rs
- src/kernel/bpf/mod.rs
- src/lib.rs
- src/normalize/ioctl.rs
- src/normalize/normalizer.rs
- src/symbolize/perf_map.rs
- src/symbolize/symbolizer.rs
- src/test_helper.rs
- src/util.rs
- tests/allocs.rs
- tests/blazesym.rs
- tests/common/mod.rs
- tests/permission.rs
- tests/permissionless.rs
Introduce a cfg alias for the `target_os = "linux"` dance. Right now this is effectively just a syntactic simplification, but down the line it will allow us to more easily also capture Android -- as a Linux variant -- under the Linux umbrella.
> Introduce 'linux' config alias

- capi/Cargo.toml
To the degree that is possible, we intend to only ship a single version of blazesym-c, which means that it should have relevant features enabled. It's generally useful to have support for the recently added BPF program symbolization included as well, so enable the 'bpf' feature of the main library. We also enable 'dwarf', but that's just to make it more obvious that it's enabled, as it actually is enabled by default.
> capi: Enable 'bpf' feature of main library

- .github/workflows/test.yml
The 'bpf' feature is expected to work on all Linux flavors for all supported target architectures etc. Make sure to do our various cross compilations with it enabled, to check that nothing blows up.
> Cross-compile with 'bpf' feature

- CHANGELOG.md
- src/elf/parser.rs
We were seeing an issue where normalization + file offset symbolization was reporting an incorrect symbolization result for certain addresses in a certain binary.
In short, in a binary with segments:
```
> Type  Offset     VirtAddr           PhysAddr           FileSiz    MemSiz     Flg Align
> LOAD  0x949be40  0x000000000969be40 0x000000000969be40 0x11d6c930 0x11d6c930 R E 0x200000
> LOAD  0x1b208780 0x000000001b409780 0x000000001b409780 0x01b5e8   0x01c1f0   RW  0x1000
> LOAD  0x1b224980 0x000000001b426980 0x000000001b426980 0x343888   0xca594c   RW  0x1000
> LOAD  0x1b600000 0x000000001c200000 0x000000001c200000 0x4a358ac  0x4a358ac  R E 0x200000
```
We were normalizing absolute address 0x1c23b4d0 to file offset 0x1b63b4d0. That's based on the calculation
```
> 0x1c23b4d0 - 0x1c200000 …
```
> Use file size in file offset -> virtual offset translation

- Cargo.toml
- build.rs
As it turns out cfg_aliases does a borderline trivial thing, in that it basically just checks an environment variable and emits one or two lines of 'cargo:' directives. When a build system other than Cargo is used that does not honor build scripts we end up having to craft similar logic ourselves. In such an instance, all cfg_aliases does is obfuscate what is really going on.
So we might as well just include the logic ourselves and get rid of the build dependency, given that we have to do it in one shape or form anyway.
> Get rid of cfg_aliases build dependency

- capi/Cargo.toml
- cli/Cargo.toml
Enable the 'bpf' feature on the main library only for target OSs that support it.
> capi: Make 'bpf' feature conditional on target OS

- src/elf/parser.rs
Add a regression test for the change introduced with pull request #875. It's unfortunately very involved and cumbersome to come up with a complete end-to-end test and so with this change we add a unit test based on partial data from the binary in question.
> Add regression test for #875

- data/test-block-augmented.ld
- data/test-block.c
- dev/build.rs
- tests/blazesym.rs
Add an end-to-end test for the fix provided by pull request #875. The test basically normalizes an address in a specially crafted binary and symbolizes the resulting file offset. It fails without commit 1a4e10740652 ("Use file size in file offset -> virtual offset translation"), because then the file offset to virtual offset translation produces a virtual offset that can't be symbolized to the expected _start function.
> Add end-to-end test for #875

- CHANGELOG.md
- Cargo.toml
- README.md
- capi/CHANGELOG.md
- capi/Cargo.toml
- cli/CHANGELOG.md
- cli/Cargo.toml
- cli/README.md
- examples/gsym-in-apk/Cargo.toml
- examples/sym-debuginfod/Cargo.toml
This change bumps the version of the crate to 0.2.0-rc.2.
> Bump version to 0.2.0-rc.2

- capi/CHANGELOG.md
- capi/Cargo.toml
- capi/include/blazesym.h
This change bumps the blazesym-c's version to `0.1.0-rc.2`. The following notable changes have been made since `0.1.0-rc.1`:
- Fixed various functions accepting `uintptr_t` addresses, when they really should be using `uint64_t`
- Introduced `blaze_read_elf_build_id` helper
- Bumped `blazesym` dependency to `0.2.0-rc.2`
> capi: Bump version to 0.1.0-rc.2

- cli/CHANGELOG.md
- cli/Cargo.toml
This change bumps blazecli's version to 0.1.7. The following notable changes have been made since 0.1.6:
- Added support for symbolization of kernel addresses
- Added '--map-files' option to 'normalize user' sub-command
- Bumped blazesym dependency to 0.2.0-rc.2
> cli: Bump version to 0.1.7

- Cargo.toml
- capi/Cargo.toml
- cli/Cargo.toml
As it turns out Cargo now allows us to define certain Cargo meta-data in a workspace-wide manner and then more easily reuse that. We intend to update things such as the edition or supported Rust version for all crates in the workspace. This makes those properties (and others) perfect candidates for this infrastructure.
With this change we switch over to using workspace-wide properties for a bunch of meta-data.
> Use workspace-wide definitions for various meta-data

- .github/workflows/build-cli.yml
- cli/README.md
Our pre-built binaries are arguably excessively large, because they carry debug and symbol information in them. That may or may not be a reasonable default when building manually, but it may be making the wrong trade-off for pre-built binaries.
For the time being, build those binaries with debug and symbol information stripped.
> cli: Strip pre-built binaries

- .github/workflows/test.yml
Some of our CI jobs only run as part of a push to main and not on the pull request preceding it. Runtime of these jobs is effectively irrelevant, because they are not blocking everything. We are constantly at the disk usage limit of our caches in the CI infrastructure and so it makes sense to relieve some pressure from it by eliminating the caches used by these jobs.
> Remove caching from push-only CI jobs

- Cargo.toml
We added the simd-adler32 dev-dependency for our minimum version downgrade to work properly. By now it appears that this hack is no longer necessary. Remove it.
> Remove no longer necessary simd-adler32 dev-dependency

- capi/include/blazesym.h
- capi/src/symbolize.rs
Reference the 'reason' member more prominently inside the documentation of the blaze_sym type, to make it easier to discover.
> capi: Reference 'reason' more prominently in blaze_sym struct

- Cargo.toml
- tests/integration.rs
- tests/suite/inspect.rs
- tests/suite/mod.rs
- tests/suite/normalize.rs
- tests/suite/symbolize.rs
Split up the integration test suite into symbolize, normalize, and inspect modules. Doing so mirrors what we are already doing for benchmarks and is just a more logical grouping all things considered. While at it, rename the integration test suite from 'blazesym', which is quite ambiguous and prevalent throughout the code base, to 'integration'.
> Split up integration test suite

- README.md
A while back we renamed the 'build' workflow to 'build-cli'. Adjust the README to reference the new workflow.
> Adhere to build workflow rename

- README.md
Extend the "format" table in the README with lines detailing the support for BPF programs.
> Add BPF programs to "format" matrix in README

- README.md
The feature roadmap that we have in the README doesn't really add a whole lot of value: some of the features are partially implemented and for others the short summary doesn't serve them justice. In general we have issues open for the majority of them and that's how GitHub users generally discover functionality gaps or similar.
Remove the roadmap from the README to remove the maintenance burden that it constitutes.
> Remove roadmap from README

- src/elf/resolver.rs
- src/inspect/inspector.rs
- src/normalize/normalizer.rs
- src/symbolize/symbolizer.rs
> Misc tracing improvements

- capi/CHANGELOG.md
- capi/Cargo.toml
- capi/include/blazesym.h
- capi/src/lib.rs
- capi/src/symbolize.rs
- capi/src/trace.rs
- capi/tests/trace.rs
- src/normalize/normalizer.rs
The main Rust crate allows for configuration of the generic tracing infrastructure to glean some insights into what is going on. So far the C library didn't have any mechanism for tapping into that. This change adds such infrastructure with the new blaze_trace() function, which allows for registration of a callback function that is invoked for each emitted trace line. It is intended to be used to better understand what is going on.
Closes: #587
> capi: Add support for tapping into traces

- .github/workflows/test.yml
Install the gcc-multilib package in the build-test-artifacts CI workflow to fix Ubuntu's broken header mess.
> Install gcc-multilib in build-test-artifacts CI workflow

- .github/workflows/test.yml
Make sure to provide libtest-so* files to the MacOS and Windows test workflows, because some of the tests may want to use them.
> Provide libtest-so* files to MacOS and Windows tests

- src/dwarf/location.rs
- src/dwarf/units.rs
Incorporate some suggestions made by Clippy that cause CI to fail with newer versions of Rust.
> Incorporate Clippy reported suggestions

- src/elf/parser.rs
- src/elf/types.rs
- src/util.rs
It's not entirely correct to read the fully blown Elf64_Ehdr object and only then look at the e_ident contained in it: if the ELF file is a 32 bit thing then only a Elf32_Ehdr would be present. This type is smaller meaning that the read of a larger object could legitimately fail (of course that would only happen if no other data is present, which is at best possible in artificially constructed cases). With this change we make sure to read the e_ident array first, check that we properly support the file, and only continue then.
> Properly read e_ident separately

- cli/CHANGELOG.md
- cli/src/main.rs
- cli/src/trace.rs
Even for tiny bits of work (such as symbolization of a single address), any generated traces are extremely hard to parse by a human because of the verbosity that tracing-subscriber's FmtSubscriber introduces: for each trace event or span event literally all fields of all active spans are included in each emitted line.
There does not appear to be a reasonable way around this, other than writing a custom "layer" that does better. This change introduces such a layer and switches the program over to using it. Note that the reason for the default verbosity may be that it is somewhat necessary in concurrent/multi-threaded contexts. However, we do not live in such a world, so this constraint doesn't really apply to us. As a side effect of this rework, we also now emit traces to stderr, which …
> cli: Rework tracing output

- cli/CHANGELOG.md
- cli/Cargo.toml
This change bumps blazecli's version to 0.1.8. The following notable changes have been made since 0.1.7:
- Significantly shortened tracing output when enabled (via -v)
> cli: Bump version to 0.1.8

- capi/cbindgen.toml
Remove a bunch of unnecessary cbindgen options from the configuration. It makes no sense to set a config such as derive_ostream, when we are generating a C header. Others are just what is the default or similarly have no bearing on the generated header.
> capi: Remove a bunch of unnecessary cbindgen options

- src/elf/parser.rs
- src/elf/types.rs
So far we have layered the decompression of ELF section data on top of our internal Cache type. In an attempt to co-locate everything cached better, move this logic into a new method inside the Cache type. Note that we cannot possibly make decompression fully transparent, because once we decompress we necessarily end up with a lifetime shorter lived than 'mmap.
> Store decompressed ELF section data inside Cache

- .github/workflows/test.yml
Convert over our jobs using llvm-gsymutil and LLVM more generally to use version 18 of the toolchain. Doing so requires us to bump to using the Ubuntu 24.04 image.
> Use LLVM 18 (and Ubuntu 24.04) in CI

- .github/workflows/test.yml
We install the llvm-18 package in a couple of our jobs for <reasons>. Said <reasons> no longer seem to hold for <other-reasons> now, presumably because of the runner image upgrade, but who wants to investigate black box behavior with an iteration time of multiple minutes. Regardless, stop installing the package.
> Remove no longer necessary llvm-18 CI dependency

- cli/CHANGELOG.md
- cli/src/args.rs
- cli/src/main.rs
Introduce the --no-debug-syms option to the 'inspect dump elf' sub-command, so that users can decide whether to dump DWARF or ELF symbols.
> cli: Add --no-debug-syms option to 'inspect dump elf' sub-command

- src/elf/parser.rs
- src/elf/types.rs
Having the ElfN type implement Copy is a convenience, but not a necessity. With upcoming work it may not be feasible to keep this type copyable. Hence, remove the Copy implementation. Go even one step further and also remove Clone, as it does not really seem necessary either.
> Remove Clone + Copy bounds from ElfN type

- src/elf/parser.rs
- src/elf/types.rs
Similar to what we did for the ElfN enum, remove the Clone & Copy impls of the ElfNSlice type. Not requiring these impls makes the code more amenable to future changes.
> Remove Clone + Copy bounds from ElfNSlice type

- src/elf/parser.rs
Instead of returning a Vec from `SymbolTableCache::create_str2sym()` and then later converting it into a boxed slice, directly collect into the latter and return that. This makes the code more straight forward while also potentially eliminating one reallocation (+ copy).
> Make `SymbolTableCache::create_str2sym()` return `Box`

- src/dwarf/units.rs
- src/elf/parser.rs
- src/kernel/bpf/prog.rs
- src/lib.rs
- src/symbolize/symbolizer.rs
Return a boxed slice from the query_line_info() helper function, to make it clear that the result is not meant to be resized and to cut down on unnecessary information being stored (the vector's capacity).
> Return boxed slice from query_line_info() helper

- src/kernel/bpf/prog.rs
In the query_line_info() helper function, we convert a Path into a PathBuf into a Box<Path> into an Rc<Path>. However, it turns out there exists a direct conversion from Path to Rc<Path>, so use that instead.
> Convert Path into Rc<Path> more directly

- src/kernel/ksym.rs
Similar to what we did beforehand, adjust
`KSymResolver::create_by_name_idx()` to return a boxed slice directly.
> Return boxed slice from KSymResolver::create_by_name_idx() helper

- src/elf/parser.rs
- src/elf/types.rs
Simplify our Cache::parse_ehdr() function by introducing and using additional ElfN_Ehdr accessor functions.
> Abstract away more ElfN_Ehdr attributes

- src/elf/parser.rs
- src/elf/types.rs
- src/normalize/buildid.rs
So far iteration over an `ElfNSlice` was assumed to always start with the slice's first element. With upcoming changes we are going to adjust that, similarly to how things already work for `ElfN_BoxedSyms`. With this change we introduce a start index argument to the `ElfNSlice::iter()` method, which causes iteration to start at said index.
> Add "offset" argument to ElfNSlice::iter

- src/elf/parser.rs
So far our symbol name to symbol index inside the SymbolTableCache type was just referencing memory mapped strings directly. That works well, but it breaks once we introduce the option of not using a memory mapping but reading sections from a file using "regular" file I/O -- which is something that we require as a "fallback" with upcoming changes. Basically, if SymbolTableCache::strs is heap allocated then str2sym can't easily reference data from it, as that would be self-referential. To work around this issue, instead of storing references inside the str2sym table, we work with indexes.
As a perhaps positive side effect of making this change, we also opted for pushing the string validation further out to the point where we actually need the Unicode string. This could, conceivably, help …
> Rework SymbolTableCache::str2sym member

- src/elf/parser.rs
- src/elf/types.rs
So far our symbol table cache had the symbols mapped into memory and then sorted references to them by the respective symbol's address, in a heap allocated array. This is conceptually fine, but it is an approach that is incompatible with future changes.
This change reworks the SymbolTableCache type as follows: 1) we to store the memory mapped symbols as-is; that is, we keep an
(unsorted) slice of the symbols around
2) we then build an additional index that is sorted by address on top of
that
In so doing we eliminate the need for keeping unnecessary references to the memory mapped data around. Further more, we could optimize the (heap allocated) index further, by using a smaller index size when the number of symbols is below certain maxima. Third, because symbol filtering now happens …
> Introduce address based index to ELF symbol table cache

- src/elf/types.rs
- src/gsym/types.rs
- src/util.rs
- src/zip.rs
With upcoming changes we are going to support either working with memory mapped ELF data or with data retrieved using regular file I/O APIs. Obviously, from a memory management perspective the two behave differently: where one just requires some massaging of byte slices, the other necessitates heap allocated buffers.
In order for our ELF types to play nice with the latter, guarantee that everything implementing Pod also is cloneable.
> Require that Pod: Clone

- src/elf/parser.rs
- src/elf/types.rs
- src/util.rs
For implementation peculiarities on Linux, we cannot make do with an ELF parser that unconditionally relies on memory mapped data. Rather, for certain /proc files we are actually forced to use file I/O instead. In order to switch between the two, introduce the Backend trait that abstracts over the differences between the two. In a nutshell, for the mmap backend we continue reading references to objects while for the file I/O based one we will work with owned objects instead.
> Introduce ELF Backend type

- src/elf/parser.rs
Add a benchmark for the creation of our ELF "str2symtab". This creation should trigger a good chunk of our data structure traversing and "parsing" paths. The performance is roughly as follows:
```
$ cargo bench --features=nightly -- bench_str2sym_creation
> test elf::parser::tests::bench_str2sym_creation  ... bench:  26,023,493.50 ns/iter (+/- 644,362.62)
```
The main reason for the addition of the benchmark is to get an idea how much performance we lost due to recent ELF parser changes: both the introduction of 32 bit support as well as the logic for working with different backends is assumed to have some runtime impact. Backporting the benchmark on top of commit 4688aa06bd5a ("cli: Rework tracing output") results in the following performance numbers before said ELF changes:
```
$ cargo …
```
> Add benchmark for ELF "str2symtab" creation

- src/elf/parser.rs
The `test_elf64_symtab` test compares the ELF reported symbol size with the one returned by ElfParser::find_sym(). However, those two are not guaranteed to match up: if an ELF symbol has a size of 0 its size is "zero or unknown". As such, we report the size as None instead. Adjust the logic to deal with this condition properly.
> Fix `test_elf64_symtab` test

- .github/workflows/test.yml
Currently we only generate the "large" benchmark files for the Criterion benchmarks in our 'bench' CI job, because that is when they are needed. However, with commit 9d1978e66160 ("Add benchmark for ELF "str2symtab" creation") it now one of the earlier nightly benchmarks that already requires one of those files.
Thus, make sure to generate them just a bit earlier.
> Generate large benchmark files for nightly benchmarks

- .github/workflows/build-linux.yml
- .github/workflows/test.yml
We don't need "recommended" packages to be installed in CI, but that's what apt-get chooses to do by default. Provide the `--no-install-recommends` option to prevent this from happening.
> Stop installing recommended packages in CI

- src/dwarf/debug_link.rs
- src/util.rs
We may need additional variants of the align_up() helper function for different integer types in the future. While it is possible to abstract over all the nitty gritty details of generic integer operations, it requires complex trait machinery in the form of the num-traits crate. For us it makes more sense to just duplicate the logic via macros. Prepare for that by defining align_up() in terms of a macro.
Signed-off-by: Daniel Müller <deso@posteo.net
> Define align_up() helper via macro

- .github/workflows/test.yml
Switch over to using kernel 6.11 in CI, now that the necessary changes have made it upstream.
> Use 6.11 kernel in CI

- .github/workflows/test.yml
As we add more jobs and have existing ones perform more work, CI slows down. One of the main offenders is the 'test-release' job, which is found to have a both cold start runtime but also doesn't play particularly nice with our caching infrastructure. This has potential trickle down effects on other jobs, which may only get scheduled on runners once others have finished (because there exist overall limits on the number of runners in use), potentially delaying overall CI time doubly.
The slowness of this job seems to come down to two things: 1) our release builds use LTO etc., making linking a very lengthy
process
2) it turns out that release builds are not incremental by default [0],
causing a lot of recompilation to happen, despite our efforts of
caching intermediate artifacts
To fix …
> Improve test-release CI job runtime

- src/elf/types.rs
- src/normalize/buildid.rs
The `Elf32_Nhdr` and `Elf64_Nhdr` types have the same size and layout. So far we have not exploited this fact and just stuck to the existing logic of differentiating between 32 and 64 bit types depending on the ELF bitness, as we do elsewhere.
However, there is a certain amount of complexity associated with supporting the two bitnesses. With this change we introduce the `ElfN_Nhdr` type as an alias to `Elf64_Nhdr` and rely solely on it.
> Introduce ElfN_Nhdr type

- src/gsym/parser.rs
We don't have to use the ReadRaw::read_slice() method in conjunction with a fallible cast to read a compile-time-sized amount of bytes, but can use the ReadRaw::read_array() helper.
> Use ReadRaw::read_array() in Gsym parsing code

- src/normalize/buildid.rs
- src/util.rs
ELF notes do not come in a one-per-section scheme, but a single section (or even segment...) can contain multiple of them. That also applies to the build ID.
For our build ID reading logic, that means that we really ought to scan all notes for the expected type instead of just looking at the first one. Implement the necessary logic.
> Actually search for build ID note

- src/kernel/bpf/prog.rs
Clippy complains that we are using str.as_bytes().len() when we could be using str.len(). Point taken. Adjust the code accordingly.
> Incorporate Clippy reported suggestion

- .github/workflows/test.yml
- dev/Cargo.toml
Force usage of 12.12.4. Evidently, with a constraint of <12.13.0 we end up picking 11 in addition to the most recent 12.13.x o_O
> Unbreak Windows CI builds^2

- src/elf/mod.rs
- src/elf/parser.rs
- src/elf/types.rs
- src/normalize/kernel.rs
- src/normalize/mod.rs
In order to (eventually...) support normalization of kernel addresses, we need to take into account whether the running kernel has address space layout randomization enabled. If that is the case, we will need to incorporate the randomization offset in the normalization process. This change introduces the necessary logic for reading said offset, so that it can be used down the line.
This change builds on all the infrastructure we added for making the ELF parser optionally work with using regular I/O APIs instead of relying on memory mapping.
Refs: #950
> Add logic for reading KASLR offset

- capi/src/inspect.rs
Add a test for the `blaze_inspect_syms_elf()` function with an input source that has reserved bytes that are non-zero.
> capi: Add test for blaze_inspect_syms_elf() with non-zero reserved bytes

- tests/suite/symbolize.rs
Add a test for kallsyms-based kernel address symbolization. We rely on the already present kallsyms copy, as opposed to data from a live system.
> Add test for kallsyms-based kernel address symbolization

- capi/src/symbolize.rs
Add a test for kallsyms-based kernel address symbolization.
> capi: Add test for kallsyms-based kernel address symbolization

- src/kernel/bpf/prog.rs
Add a test for converting a `BpfProg` object into a `SymInfo` entity. This conversion is not currently exercised otherwise, because we don't support inspection of kernel data at this point.
> Add test for converting BpfProg into SymInfo

- dev/Cargo.toml
With the `12.13.2` release [0] `symbolic-demangle` is usable again on GitHub Action Windows workers. Remove the version override that we introduced to work around earlier issues.
[0]: https://github.com/getsentry/symbolic/releases/tag/12.13.2
> Remove symbolic-demangle version patch workaround

- capi/CHANGELOG.md
- capi/include/blazesym.h
- capi/src/symbolize.rs
For whatever reason our `blaze_sym` type does not yet capture the symbol's size, which is available in the Rust counterpart. Expose it in the C API as well.
> capi: Expose symbol size

- .github/workflows/test.yml
GitHub Actions comes with an auto-merge feature, which allows for automatically merging PRs once certain requirements are met. For us, these requirements would be the passing of all CI checks. Alas, their !@#*&()$&@!(#* configuration requires us to explicitly list all CI jobs that need to pass, which is an absolute maintenance nightmare. To improve on the situation at least somewhat, introduce a job that captures all required checks, so that the definition of this arbitrary entity is at least co-located with the definition of these jobs and not hidden behind four layers of clicky-bunti UI fluff.
The logic is adapted from:
https://github.com/orgs/community/discussions/75568#discussioncomment-10351973
> Introduce required-checks CI job

- CHANGELOG.md
- src/kernel/resolver.rs
- tests/suite/symbolize.rs
As a side effect of commit 7ee10afffe9e ("Merge
SymResolver::find_code_info() into SymResolver::find_sym()") we changed the behavior of the kernel resolver in that where previously it would consult the ELF resolver for source code information, it no longer did so. That was mostly a result of the kernel resolver giving preference to the internally used KSymResolver, as opposed to the ElfResolver. This change adjusts the logic to make sure that if an ElfResolver is present, we end up using it for symbolization.
> Give preference to ELF symbolization for kernel addresses

- CHANGELOG.md
- capi/CHANGELOG.md
- capi/include/blazesym.h
- capi/src/symbolize.rs
- src/kernel/resolver.rs
- src/lib.rs
- src/symbolize/source.rs
- src/symbolize/symbolizer.rs
- tests/suite/symbolize.rs
Currently there is no (reasonable) way for users to opt out of usage of kallsyms or the ELF kernel image: if they specify to use "None" a default will be used and if an actual value is provided so will it. That can be a problem in many conceivable scenarios.
To allow the user to specify either a specific value, the library default, or to disable either of the sources, introduce a tri-choice enum.
> Provide more control over kernel symbolization

- capi/include/blazesym.h
- capi/src/symbolize.rs
- src/kernel/resolver.rs
- src/symbolize/source.rs
- tests/suite/symbolize.rs
The kernel image file, even if present, is limited in which addresses it is able to resolve. Kernel addresses belonging to modules, for example, can't be symbolized this way. While we may eventually add better support for kernel modules, for now the best course of action seems to be to fall back to usage of kallsyms.
> Make sure to use kallsyms as fallback

- src/kernel/resolver.rs
Declare the members of the KernelResolver type as private, to ensure proper isolation.
> Make KernelResolver members private

- src/kernel/kaslr.rs
- src/kernel/mod.rs
- src/normalize/mod.rs
- tests/common/mod.rs
As it turns out we will need the KASLR logic not just in normalization code but also in parts of the symbolization logic. As such, let's move the containing module out of the normalize functionality and into the more generic parts of the crate.
> Move KASLR logic into "generic" kernel module

- src/kernel/ksym.rs
- src/kernel/mod.rs
- src/kernel/resolver.rs
- src/symbolize/symbolizer.rs
Rename `KSymResolver` to `KsymResolver` to better match existing naming with `Ksyms`.
> Rename `KSymResolver` -> `KsymResolver`

- cli/src/args.rs
With earlier versions of Clap, the attribute for configuring attribute options was called `#[clap(...)]`. This name is still available, but it seems as if `#[arg(...)]` is the preferred syntax now. So switch over to using the latter.
> cli: Use #[arg(...)] attribute over #[clap(...)]

- CHANGELOG.md
- capi/CHANGELOG.md
- capi/include/blazesym.h
- capi/src/symbolize.rs
- cli/CHANGELOG.md
- cli/src/args.rs
- cli/src/main.rs
- src/kernel/resolver.rs
- src/symbolize/source.rs
- src/symbolize/symbolizer.rs
- tests/suite/symbolize.rs
The terms "kernel image" is pretty ambiguous and somewhat nebulous, to the point that it is probably not clear to many what it or its properties should be. What we (and other debugging/profiling tools) really seem to be interested in is what generally seems to be referred to as vmlinux [0].
Switch terminology from "kernel image" to "vmlinux". The latter is much more easily discoverable (both in the sense that the meaning of the word can be pinned down as well as that a file of that name [or with such a prefix] can be found on the file system) and more precisely defined.
[0] https://en.wikipedia.org/w/index.php?title=Vmlinux&oldid=1252541783
> Rename "kernel image" to "vmlinux"

- Cargo.toml
- capi/Cargo.toml
Make the URL to the documentation of each of the library crates known so that it will be easier to click through to it from a crates.io search.
> Add direct links to documentation

- src/symbolize/symbolizer.rs
In general not all entries in `/proc/[pid]/maps` are of interest to us and we perform some pre-filtering based on somewhat coarse grained criteria. However, for one reason or another we didn't do that in the symbolization logic, only when normalizing. Having failed to surface why that is, exactly, let's switch over to using the filtered version nonetheless, as none of our tests fail with the filtered version. Do so should speed up things a bit and make follow-on changes easier to digest.
> Use maps::parse_filtered() for process symbolization

- .github/workflows/build-linux.yml
- .github/workflows/test.yml
- CHANGELOG.md
- Cargo.toml
- capi/src/symbolize.rs
- src/elf/mod.rs
- src/elf/parser.rs
- src/kernel/kaslr.rs
- src/kernel/mod.rs
- src/kernel/resolver.rs
- src/symbolize/source.rs
- src/symbolize/symbolizer.rs
- tests/suite/symbolize.rs
Our vmlinux based symbolization can only work properly of the kernel location is not randomized, because then the in-memory addresses should match up with those in the file.
To make sure that symbolization will work properly when KASLR (kernel address space layout randomization) is enabled, query the corresponding randomization offset and incorporate it in symbolization requests. Also add a new attribute, `kaslr_offset`, to the Kernel symbolization source that allows for passing in the offset if necessary.
> Include KASLR offset in vmlinux based symbolization logic

- data/test-block.c
- tests/suite/symbolize.rs
Adjust the test-block binary to emit the address of its _start function to stdout rather than stderr. Doing so is the first step towards unifying more of our "remote process" tests. Line buffering, as mentioned in the comment, does not seem to be an issue, presumably because it's a libc thing and we are directly using system calls.
> Adjust test-block to emit address to stdout

- data/test-so.c
- tests/suite/common/mod.rs
- tests/suite/symbolize.rs
Currently the libtest-so.so shared object's await_input() function nicely formatted the address of said function before emitting it to stdout. In an attempt to make all "remote process" tests use similar mechanisms, switch to just dumping the address as binary, foregoing the to-text conversion.
> Adjust libtest-so.so to dump await_input() address without text conversion

- tests/suite/common/mod.rs
- tests/suite/normalize.rs
- tests/suite/symbolize.rs
Rename the `run_user_symbolization_test` test to
`run_unprivileged_process_test`, to better reflect its intended purpose.
> Rename run_user_symbolization_test -> run_unprivileged_process_test

- CHANGELOG.md
- benches/inspect.rs
- benches/symbolize.rs
- capi/CHANGELOG.md
- capi/include/blazesym.h
- capi/src/inspect.rs
- capi/src/normalize.rs
- capi/src/symbolize.rs
- cli/src/main.rs
- examples/addr2ln.rs
- examples/addr2ln_pid.rs
- examples/backtrace.rs
- examples/gsym-in-apk/main.rs
- examples/inspect-mangled.rs
- examples/normalize-virt-offset.rs
- examples/sym-debuginfod/main.rs
- src/inspect/mod.rs
- src/inspect/source.rs
- src/normalize/meta.rs
- src/symbolize/cache.rs
- src/symbolize/mod.rs
- src/symbolize/source.rs
- src/symbolize/symbolizer.rs
- tests/suite/inspect.rs
- tests/suite/normalize.rs
- tests/suite/symbolize.rs
Users may legitimately be interested in being able to symbolize addresses inside a process even if the process has exited in the meantime.
To support such use cases, introduce a new top-level API to the Symbolizer: the cache() method allows for caching various data pertaining a symbolization source. At this point we only support caching of process VMA metadata, but in the future we can support pre-parsing ELF and DWARF metadata and similar, which could speed up symbolization requests significantly.
> Add support for pre-caching process VMA metadata

- capi/include/blazesym.h
- capi/src/symbolize.rs
Add a test exercising the conversion from `blaze_cache_src_process` to `cache::Process`.
> capi: Add `blaze_cache_src_process` conversion test

- tests/suite/symbolize.rs
We have seen another failure of the symbolize_kernel_system_vmlinux test, caused by a symbol being aliased as both "T" and "W" type, under different names:
```
$ cat /proc/kallsyms | grep blake2s_compress
> ffffffff858cd870 T blake2s_compress_generic
> ffffffff858cd870 W blake2s_compress
```
This is another source of ambiguity that we can't really anticipate in advance. To fix issues of this kind, include "W" symbols (and "D" ones) in the list of candidate ones to symbolize. This way, the alias detection logic will be able to filter them out based on their equal addresses.
> Include "W" symbols in symbolize_kernel_system_vmlinux test

- capi/src/inspect.rs
- capi/src/symbolize.rs
- data/test-stable-addrs.ld
- src/dwarf/resolver.rs
- src/elf/parser.rs
- src/gsym/parser.rs
- src/gsym/resolver.rs
- src/lib.rs
- tests/suite/inspect.rs
- tests/suite/symbolize.rs
When adding more functionality to `test-stable-addrs`, we start running into issues with insufficient space in the `.text` section, causing it to overlap with .text.factorial.
To give us some more room to breath, move `.text.factorial` back by 0x100 bytes.
> Move `.text.factorial` section of `test-stable-addrs*` binaries

- src/elf/parser.rs
Adjust the logic in `ElfParser::pick_symtab_addr()` to stop reporting data for symbols that are aliases, as those are ambiguous to symbolize. This is similar to what we did in commit 8f2786be3434 ("Fix symbolize_kernel_system_vmlinux test flakiness").
> Adjust ElfParser::pick_symtab_addr() logic

- capi/include/blazesym.h
- capi/src/symbolize.rs
The documentation of the blaze_symbolize_cache_process() function references non-existing inputs arguments. Fix it up.
> capi: Fix documentation for blaze_symbolize_cache_process

- .github/workflows/test.yml
- capi/src/inspect.rs
With commit cf9a687db372 ("Work around Miri failures") we pinned the Miri version used in CI to a know version, because newer ones were suddenly causing test failures, and the suspicion was that this could be caused by a bug in Miri itself. This is pinning of an old version is now becoming an issue, as it is blocking the update of a dependency [0].
Investigation has now put a light on the actual issue, which is that we are modifying data through a pointer, while an exclusive reference to said data exists, which is -- as Miri reports -- undefined behavior, because we are violating aliasing rules.
With this change we fix this problem and roll back to using more up-to-date versions of Miri.
This reverts commit cf9a687db372fa9ad5694f9c44d7df2aad637a4a.
[0] …
> Revert "Work around Miri failures"

- cli/Cargo.toml
It seems over the top to specify patch versions for clap and that appears to be causing Dependabot to decide to create an update pull request for each patch level release. Just drop the patch bits from the version.
> cli: Loosen clap version requirements

- capi/src/symbolize.rs
The `symbolize_in_kernel()` test may inadvertently use a vmlinux file that could be present on the system and that could lead to a wrong symbolization. Given that the test is only meant to work with kallsyms image, disable usage of vmlinux altogether to prevent any interference with system data.
> capi: Don't use vmlinux in symbolize_in_kernel() test

- examples/gsym-in-apk/main.rs
The gsym-in-apk example still uses the memory size in the file offse to virtual offset translation. Similar to what we did in commit 1a4e10740652 ("Use file size in file offset -> virtual offset translation") switch to using the file size instead.
> Use file size in gsym-in-apk example

- CHANGELOG.md
- src/normalize/meta.rs
- src/normalize/mod.rs
- src/normalize/user.rs
We use the 'apk' feature in the symbolization part of the crate to guard inclusion of everything and anything APK related. However, for the normalization APIs we only really exclude the actual implementation (i.e., creation of APK meta entries). That seems to be a bit confusing. Make sure to guard the APK meta data types of the normalization bits by the 'apk' feature as well.
> Make normalization APK exports conditional on 'apk' feature

- src/normalize/mod.rs
- tests/suite/normalize.rs
Document that the `Default` impl of the `normalize::NormalizeOpts` type disables all options, as it is not obvious how it behaves otherwise.
> Document the NormalizeOpts Default impl better

- dev/Cargo.toml
- examples/gsym-in-apk/Cargo.toml
"Relax" some of the version constraints we have from including patch levels. In none of the cases there is really any relevance to the last component.
> Relax some version constraints

- src/apk.rs
- src/lib.rs
- src/symbolize/symbolizer.rs
Move the `create_apk_elf_path()` helper function into the newly created `apk` module, to make it accessible from outside the symbolization logic.
> Move create_apk_elf_path() helper into new apk module

- .clippy.toml
- .github/workflows/test.yml
- CHANGELOG.md
- Cargo.toml
- README.md
- capi/README.md
- cli/README.md
- src/apk.rs
- src/symbolize/symbolizer.rs
It doesn't really make much sense for the create_apk_elf_path() helper to be fallible. Conceptually at least, the algorithm is super straight forward and there is no reason to report an error just because no APK path is present. Yes, it's a logical error of sorts, but it's a logical error everywhere else as well, not just in this function. Adjust the logic to be a bit more robust (or at least easier to grasp) and to not emit any errors.
> Make create_apk_elf_path() infallible

- capi/include/blazesym.h
- capi/src/normalize.rs
Sync up the `blaze_user_meta_elf` documentation with that of `normalize::NormlizeOpts` after recent changes.
> capi: Update blaze_user_meta_elf documentation

- CHANGELOG.md
- capi/CHANGELOG.md
- capi/include/blazesym.h
- capi/src/symbolize.rs
- src/breakpad/parser.rs
- src/breakpad/resolver.rs
- src/breakpad/types.rs
- src/dwarf/resolver.rs
- src/elf/parser.rs
- src/gsym/resolver.rs
- src/kernel/bpf/prog.rs
- src/kernel/ksym.rs
- src/perf_map.rs
- src/symbolize/mod.rs
- src/symbolize/symbolizer.rs
- tests/suite/symbolize.rs
> Include "module" information in Sym type

- tests/suite/symbolize.rs
Improve the `error_on_non_existent_source` test by creating a proper temporary directory with a non-existent file in there, instead of just relying on a global path (which could conceivably exist).
> Improve `error_on_non_existent_source` test

- CHANGELOG.md
- src/insert_map.rs
Our InsertMap type is not working correctly in the presence of reallocations of the internally used hash map. Specifically, because our insertion does not require a mutable reference, users may hold references to entries across insertions. If the hash map were to reallocate as part of the insertion, the references would effectively be dangling, which is undefined behavior.
Fix the problem by heap allocating all values in the hash map.
> Fix unsoundness in `InsertMap`

- src/symbolize/cache.rs
- src/symbolize/symbolizer.rs
We introduced the `symbolize::cache::Cache` with a lifetime argument to mirror what we have for `symbolize::source::Source`. However, whereas it may make sense for a symbolization source to be in-memory, that (at least currently) does not for caching: caching only makes sense if the data can subsequently be passed to symbolization APIs. However, there is no way to name this data, as its just a blob of bytes. To that end, remove the lifetime parameter from the Cache enum.
> Remove lifetime from `symbolize::cache::Cache` enum

- capi/include/blazesym.h
- capi/src/symbolize.rs
Fix up the documentation for the `blaze_symbolize_cache_process()` function, which was woefully out of whack with reality.
> Fix documentation for blaze_symbolize_cache_process()

- tests/suite/symbolize.rs
The `symbolize_elf_cached` test fails on Windows, citing some denied access when removing the file. That being some platform peculiarity, remove this test from the suite run in operating systems other than Linux.
> Remove 'other_os' tag from `symbolize_elf_cached()` test

- .github/workflows/stale.yml
As of commit 18c053844049 ("Add GitHub workflow to close stale PRs") we automatically close stale PRs after a while. Some PRs, however, may not be actionable at the moment, in which case auto closing is not a desired action.
To cater to such cases, honor the 'blocked' label and exclude PRs with it from staleness detection.
> Exempt 'blocked' PRs from auto close

- Cargo.lock
- cli/Cargo.toml
- cli/src/trace.rs
Replace our custom `StackWriter` type with the Writer type from the `bufio` crate.
> cli: Replace `StackWriter` type with `bufio::Writer`

- CHANGELOG.md
- capi/CHANGELOG.md
- capi/include/blazesym.h
- capi/src/inspect.rs
- src/breakpad/resolver.rs
- src/dwarf/resolver.rs
- src/elf/parser.rs
- src/inspect/mod.rs
- src/kernel/bpf/prog.rs
- src/kernel/ksym.rs
- tests/suite/inspect.rs
Rename the `inspect::SymInfo::obj_file_name` attribute to `module`. In so doing we establish similarity with `symbolize::Sym::module`, which has been introduced earlier. The new name is shorter and arguably more telling.
> Rename `inspect::SymInfo::obj_file_name` to `module`

- src/dwarf/resolver.rs
- src/elf/parser.rs
- src/elf/resolver.rs
- src/kernel/ksym.rs
- src/kernel/resolver.rs
Rework `Debug` impls of a few resolvers/parsers in a way that allows us to remove the `KsymResolver::file_name()` as well as `ElfResolver::path()` methods. We want to minimize exposure of "paths" pertaining resolvers between individual modules of the crate.
> Rework various resolver Debug impls

- src/elf/resolver.rs
Use an explicit `Rc::clone()` call over the more ambiguous `.clone()` to make it more obvious what is going on as well as be more resilient to unintentional deep clones when refactoring the code.
> Use explicit Rc::clone() in FileCache::elf_resolver

- src/elf/parser.rs
- src/elf/resolver.rs
- src/kernel/kaslr.rs
- src/normalize/normalizer.rs
- src/zip.rs
Using the "open" terminology in some of the `ElfParser::open_*()` constructors doesn't really make sense. We are not opening a file, because an already opened file gets passed in. Rename the constructors to something using `from_file*()` instead.
> Rename ElfParser::open_*() constructors

- src/dwarf/resolver.rs
Declare the `DwarfResolver::open()` constructor private, to prevent usage from outside the module it is defined in.
> Make DwarfResolver::open() private

- capi/src/inspect.rs
- capi/src/symbolize.rs
- src/breakpad/parser.rs
- src/breakpad/types.rs
- src/dwarf/resolver.rs
- src/elf/parser.rs
- src/inspect/mod.rs
- src/symbolize/mod.rs
- src/symbolize/symbolizer.rs
- tests/suite/symbolize.rs
It is unlikely that the "module" attribute of the `Sym` and `SymInfo` types will always be a Path. For example, for VDSO data we may want to have a mere string in there. But even for APK contents we may end up with an Android style "virtual" path. Make this somewhat clearer by changing the type from `Path`/`PathBuf` to `OsStr`/`OsString`.
> Adjust `{Sym,SymInfo}::module` to be an `OsString`

- cli/CHANGELOG.md
- cli/src/trace.rs
Our tracing logic doesn't handle overly long lines properly: when a line is longer than 256 bytes it will be discarded in its entirety. What we really want is to truncate it silently. Adjust the logic accordingly.
> cli: Make sure to properly truncate trace messages

- src/dwarf/resolver.rs
- src/elf/parser.rs
- src/inspect/inspector.rs
- src/inspect/mod.rs
- src/kernel/ksym.rs
- src/test_helper.rs
Rename the `FindAddrOpts::offset_in_file` attribute to file_offset. The former just feels too cumbersome to spell out. There is admittedly some potential for confusion between `FindAddrOpts::file_offset` (a boolean) and `SymInfo::file_offset` (an integer), but really the context should make it obvious which one is which.
> Rename `FindAddrOpts::offset_in_file` attribute

- capi/CHANGELOG.md
- capi/include/blazesym.h
- capi/src/symbolize.rs
Rename the `blaze_symbolize_src_process::map_files` attribute to no_map_files and invert its meaning. By default it makes the most sense to use map_files for the sake of correctness. Given that we rely on zero initialization as the "default" representation, asking for explicit disabling makes the most sense.
> capi: Rename `blaze_symbolize_src_process::map_files` attribute

- capi/include/blazesym.h
- capi/src/symbolize.rs
Sync up the documentation of the `blaze_symbolize_src_process::pid` member with that of the main crate.
> capi: Sync up `blaze_symbolize_src_process::pid` documentation

- .cargo/config.toml
We have to use a custom test runner in order to run privileged tests. Currently we only do so for the `x86_64-unknown-linux-gnu` target, but that is unnecessarily restrictive.
Relax the constraint to use the test runner on any Linux target.
> Relax Cargo test runner constraint

- capi/include/blazesym.h
- capi/src/inspect.rs
- capi/src/normalize.rs
- capi/src/symbolize.rs
Add more reserved bytes to various types to facilitate future expansion. We want to make sure to have at least 16 bytes available on most types. Exceptions are `blaze_sym` as well as the code and info types, which are somewhat performance sensitive as well as less likely to see large extensions due to the nature of what they represent.
> capi: Add more reserved bytes for future expansion

- capi/include/blazesym.h
- capi/src/error.rs
- capi/src/trace.rs
Fixate the layout of the `blaze_err` and `blaze_trace_lvl` types to make it well defined and more future proof. It also seems like the right thing in terms of consistency of the code.
> capi: Fix layout of blaze_err and blaze_trace_lvl

- capi/CHANGELOG.md
- capi/include/blazesym.h
- capi/src/normalize.rs
Add reserved bytes for future expansion to the `blaze_normalized_output` and `blaze_user_meta` types. It is not considered particularly likely that we will ever extend them, but it also seems like a small price to pay.
> capi: Add reserved bytes to more normalize types

- capi/README.md
While it is possible that our forward/backward compatibility story is sufficient to cover incompatible versions, we won't officially endorse incompatible version combinations (e.g., using a blazesym 0.3 shared object from a program having linked against blazesym 0.2).
> capi: Add section about versioning guarantees to README

- Cargo.lock
- capi/CHANGELOG.md
- capi/Cargo.toml
- capi/include/blazesym.h
This change bumps the blazesym-c's version to 0.1.0. The following notable changes have been made since 0.1.0:
- Introduced blaze_trace function for tapping into the library's tracing functionality
- Added apk_to_elf attribute to blaze_normalize_opts
- Added size and module attributes to blaze_sym type
- Added additional reserved bytes to various types
- Adjusted various enum types to be mere typedefs
- Changed size attribute of blaze_sym_info to be signed
- Changed blaze_user_meta_kind to be represented as uint8_t
- Renamed kernel_image member of blaze_symbolize_src_kernel to vmlinux
- Renamed obj_file_name member of blaze_sym_info to module
- Renamed map_files member of blaze_symbolize_src_process to no_map_files and inverted its meaning
- Added support for disabling kallsyms and …
> capi: Bump version to `0.1.0`

- .github/workflows/test.yml
- capi/CHANGELOG.md
- capi/src/error.rs
- capi/src/normalize.rs
- capi/src/symbolize.rs
- capi/src/trace.rs
As it turns out only recent versions of Rust seem to support matches on constants of types not implementing Eq. As a result, the library actually does not build on Rust 1.70 as advertised. Add the necessary derive implementations and make sure to enforce MSRV checks even for blazesym-c.
> capi: Lower MSRV to 1.70

- Cargo.lock
- capi/CHANGELOG.md
- capi/Cargo.toml
- capi/include/blazesym.h
This change bumps the blazesym-c's version to 0.1.1. The following notable changes have been made since 0.1.0:
- Lowered minimum supported Rust version to 1.70
> capi: Bump version to 0.1.1

- .github/workflows/test.yml
Enable caching of Rust build artifacts for the test-32bit CI job. It seems one of the slower jobs now, given that most others already use caching.
> Enable Rust artifact caching for test-32bit CI job

- capi/include/blazesym.h
- capi/src/normalize.rs
Commit 3b47031f945d ("capi: Convert blaze_user_meta_kind to use associated constants") missed to rename the newly introduced associated constants, leading to unwieldy names.
Introduce the proper shorter named constants and deprecated to long ones.
> capi: Shorten blaze_user_meta_kind constants

- capi/CHANGELOG.md
Add a CHANGELOG entry for pull request #1084, which shortened the names of the `blaze_user_meta_kind` constants.
> capi: Add CHANGELOG entry for #1084

- CHANGELOG.md
- dev/build.rs
- src/dwarf/debug_link.rs
- tests/suite/symbolize.rs
It is possible to set a DWARF file's debug link to the file itself, i.e., creating a self-referential entity. One could come up with a rational for that, or it could just be a bug. Our debug link resolution logic currently follows the link, but given that the link's expected checksum seems to be written before adjustment of the link, the checksum would never check out, causing us to report an error. From a logical point of view, it makes no sense to even consider the case where we resolve the debug link to the linker itself. As such, with this change we check to make sure that we do not report the linker itself, just moving on if we would. In so doing we actually support the case where the linkee is a file of the same name as the linker, and that could actually be found in a different …
> Ignore self-referential debug links

- tests/suite/symbolize.rs
The test fails on Windows, presumably because of their weird path handling. It doesn't seem worth it to spent the time to look into that for this corner case until this becomes more than a hypothetical issue, so stop running the test on anything but Linux.
> Don't run self-referential debug link test on other OSs

- CHANGELOG.md
- src/symbolize/symbolizer.rs
- tests/suite/symbolize.rs
Commit 7e1d9455db20 ("Introduce PathLike trait") introduced the PathLike trait and adjusted the process symbolization for ELF files to use it in order to report more meaningful Sym::module values. What explicitly was left for later was to apply a similar logic to the APK path. This change addresses this remaining short coming.
> Report symbolic paths as module for APK process symbolization

- CHANGELOG.md
- src/symbolize/symbolizer.rs
- tests/suite/symbolize.rs
The change shouldn't have gone in in its current form, it wasn't finished.
This reverts commit 3e544840c8c5c6df8a0370269ee5bd40cc089b08.
> Revert "Report symbolic paths as module for APK process symbolization"

- src/elf/resolver.rs
- src/inspect/inspector.rs
- src/pathlike.rs
- src/symbolize/symbolizer.rs
With upcoming changes we are going to use the PathLike trait on the APK symbolization paths as well. These paths are arguably more involved than the ELF bits and monomorphizing everything there will lead to binary bloat.
As such, we have to switch over to using trait objects when working with PathLike objects in more places. Do so for the `elf_resolver()` method already to set proper precedent.
> Work more with PathLike trait objects

- capi/Cargo.toml
As explored in #1096 
We disable generating the header since it already exists, and more importantly because we cannot run the required custom cbindgen extension from cargo-c (at least not until the custom rename rule has been merged upstream into cbindgen).
The configuration bits alone should not disturb existing builds in any way, but are necessary for building with e.g. `cargo cbuild`. A sample configuration/invocation can be found in the prototypical [Gentoo ebuild](https://github.com/hhoffstaette/gentoo/tree/blazesym/dev-libs/blazesym_c). Basically a packager needs to pass e.g. `--prefix`, `--destdir` etc. depending on their target environment, and as documented by cargo-c.
> capi: add capi feature & configuration to enable building with cargo-c

- .github/workflows/test.yml
Another day another Ubuntu !@#&*()!@&*(!. Apparently we need to run `apt-get update` now just to install `libelf-dev`. Appease the gods by doing that.
> Fix Miri and Clippy CI jobs

- .github/workflows/build-linux.yml
Similar to what commit c30b1003d3d6 ("Fix Miri and Clippy CI jobs") did for the main test CI workflow, fix the build-linux workflow by running apt-get update before attempting to install packages.
> Fix build-linux workflow

- CHANGELOG.md
- dev/build.rs
- src/elf/parser.rs
The ELF compression header resides inside an ELF section's actual data. As such, it may not be aligned correctly. Switch over to reading it using read_pod() to make sure that we are able to read it even if unaligned.
This is a respin of commit 3e8ef1b54f45 ("Use read_pod() for reading compression header"), which somehow managed to get lost.
Closes: #1105
> Fix reading of unaligned compression headers

- tests/suite/symbolize.rs
Make sure to also test instruction/function offset querying when symbolizing addresses using kallsyms, to make sure that the data we report is kosher.
> Test instruction offset querying for kallsyms symbolization

- capi/tests/trace.rs
Instead of .len() > 0, use !.is_empty() check.
> capi/tests: fix clippy warning about not using is_empty()

- README-devel.md
When *only* running the capi test suite and never having run the overall blazesym one, we end up not generating test artifacts. The fix isn't trivial, unfortunately, and given that this is a very unlikely pattern, let's just fudge this case with documentation.
Refs: #1103
> Add note about test artifact generation for capi tests

- Cargo.toml
- capi/Cargo.toml
Relax the libc version requirement. Not sure why we'd need 0.2.172.
> Relax libc version requirement

- CHANGELOG.md
- capi/include/blazesym.h
- capi/src/symbolize.rs
- src/maps.rs
- src/symbolize/source.rs
- src/symbolize/symbolizer.rs
- tests/suite/symbolize.rs
Add support for symbolizing addresses residing in a vDSO (virtual dynamic shared object). vDSO calls are system calls that don't have to enter the kernel but just read memory shared with it (and mapped into the application). As such, they are much faster than regular system calls.
From a symbolization perspective, the vDSO is a memory region that is actually nothing more than a regular ELF object. For symbolization purposes, we grab that region (potentially reading it from another process), write it into a file, and then use the regular ELF symbolization logic. We could opt to do this completely in-memory and without file system involvement, however due to the way things are structured it gets a bit more involved, because a new ElfParser backend has to be introduced, alongside …
> Add support for symbolizing addresses in a vDSO

- .github/workflows/test.yml
Add a test that dry-runs the packaging procedure using cargo-c in CI. We could do more on this front (such as actually linking against the library using the package config), but this should be sufficient to have some confidence that we won't break the workflow.
> Add CI test for cargo-c packaging

- src/lib.rs
For running "unit benches", we rely on the nightly 'test' crate. In recent versions of Rust, we are now seeing a warning emitted for the corresponding extern declaration, for no obvious reason. Silence it.
> Allow extern 'test' crate for benchmarking purposes

- capi/include/blazesym.h
- capi/src/symbolize.rs
- src/symbolize/symbolizer.rs
The documentation surrounding the `code_info` and `inlined_fns` flags is somewhat lacking and partly incorrect. Both flags require `debug_syms` of the particular source to be enabled in order to have an effect. State that explicitly.
> Improve documentation surrounding `code_info` & `inlined_fns` flags

- CHANGELOG.md
- src/kernel/bpf/prog.rs
- src/kernel/ksym.rs
- tests/suite/symbolize.rs
Currently we report only the "core" name of the BPF program when symbolizing the corresponding address. However, to make them easier distinguishable from regular kernel functions, it can make sense for us to preserve the 'bpf_prog_' prefix. So do just that. Furthermore, keep the tag in there as well, which can be helpful when comparing potentially different versions of the program.
> Adjust BPF program symbols to preserve kernel name

- src/symbolize/symbolizer.rs
While there are no hard bounds on the size of a Symbolizer instance, right now it's basically a free for all without any checks. Given that objects may be copied around, we don't want it to balloon too much. Add a test asserting the size of such objects, to introduce a bit more intentionality to changes of said size.
> Add test checking Symbolizer size

- Cargo.lock
- capi/Cargo.toml
In the past we required a custom fork of the `cbindgen` crate in order to the `struct.rename_associated_constant` support that we require for authoring the header. This functionality is now included in version `0.29` of the crate, so switch over to using it.
> Switch back to using cbindgen main crate

- Cargo.toml
- cli/src/args.rs
- src/breakpad/parser.rs
- src/error.rs
- src/lib.rs
Enable the Clippy lint warning on the usage of wildcard imports. These are generally considered undesirable on many axis and should be avoided. The existing uses are probably fine, but given that rustfix is able to auto-correct them, there is very little harm in preventing such usage from the get go.
> Warn on wildcard imports

- src/elf/parser.rs
Our BackendImpl for memory slices unwraps and, hence, may panic in case the slice offset is out of range -- likely due to an oversight. Convert the potential panic to a regular runtime error instead.
> Convert panic to graceful runtime error

- capi/include/blazesym.h
- capi/src/symbolize.rs
- src/symbolize/symbolizer.rs
Improve the documentation surrounding the "code info" setting on the `Symbolizer` `Builder` by clarifying that the setting is a prerequisite for inlined function reporting.
> Improve documentation surrounding "code info" and inlined functions

- src/symbolize/symbolizer.rs
In `Symbolizer::symbolize_with_resolver()` we first collect uncached symbolized symbols into a Vec, just to transform that into a boxed slice. Collect into a boxed slice directly, in order to cut down on unnecessary allocations and/or copies.
> Collect uncached symbols into boxed slices directly

- capi/benches/normalize.rs
- capi/src/normalize.rs
Unify our naming a bit by renaming the "user_addrs" variable used in a couple of tests to "normalized".
> Use "normalized" instead of "user_addrs" variable in tests

- capi/src/symbolize.rs
Use simplified naming in `blaze_syms_free()` and eliminate some `as` casts. This will come in handy elsewhere, because we will copy/repurpose some of this logic in the future.
> capi: Some minor simplifications

- capi/CHANGELOG.md
- capi/build.rs
- capi/include/blazesym.h
- capi/src/normalize.rs
- capi/src/symbolize.rs
Add support for normalization of vDSO addresses. This is the C API counter part to #1158. We introduce a new user meta data variant for representing a fully symbolized entity.
Closes: #1134
> capi: Add support for vDSO address normalization

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- capi/CHANGELOG.md
- capi/Cargo.toml
- cli/CHANGELOG.md
- cli/Cargo.toml
- cli/README.md
- examples/gsym-in-apk/Cargo.toml
- examples/sym-debuginfod/Cargo.toml
This change bumps the version of the crate to `0.2.0-rc.4`.
> Bump version to `0.2.0-rc.4`

- Cargo.lock
- capi/CHANGELOG.md
- capi/Cargo.toml
- capi/include/blazesym.h
This change bumps the blazesym-c's version to 0.1.2. The following notable changes have been made since 0.1.1:
- Introduced blaze_user_meta_sym meta data variant
- Added support for normalization of vDSO addresses
- Added shorter blaze_user_meta_kind constants
- Deprecated BLAZE_USER_META_KIND_BLAZE_USER_META_* constants
- Bumped blazesym dependency to 0.2.0-rc.4
> capi: Bump version to 0.1.2

- Cargo.lock
- Cargo.toml
- src/error.rs
- src/symbolize/symbolizer.rs
- tests/suite/normalize.rs
- tests/suite/symbolize.rs
Update the `test-log` dev-dependency to 0.2.18, which now allows for proper stacking of `#[test]` attributes, making it compose more nicely with the `test-fork` crate.
> Update test-log dev-dependency to 0.2.18

- dev/Cargo.toml
- examples/gsym-in-apk/Cargo.toml
Dependabot, with its stupid and inflexible update logic, updates Cargo.toml and with that bumps the minimum required version of a dependency, which makes no sense. If past is any guidance, it won't do that if all that is specified is the major version. Do that, which should trigger updates only to Cargo.lock as long as only minor versions are changed.
> Allow greater zip dependency version flexibility

- capi/CHANGELOG.md
- capi/include/blazesym.h
- capi/src/normalize.rs
- capi/src/symbolize.rs
With commit 59942c900c54 ("Merged normalize::Reason and symbolize::Reason") we merged the two Reason enums employed by the main crate. As a result, it is now possible for the C API to receive symbolization reason variants, but currently it cannot handle converting them into a blaze_normalize_reason object.
Make these new reasons known and wire them up to the conversion routine. Note that ideally we'd be unifying blaze_symbolize_reason and blaze_normalize_reason as well, but we cannot for binary compatibility reasons: equally named variants have assigned to them different values.
> capi: Add missing `blaze_normalize_reason` variants

- Cargo.lock
- capi/CHANGELOG.md
- capi/Cargo.toml
- capi/include/blazesym.h
This change bumps the blazesym-c's version to `0.1.3`. The following notable changes have been made since `0.1.2`:
- Fixed potential panic when normalizing vDSO addresses
> capi: Bump version to `0.1.3`

- capi/src/normalize.rs
- src/lib.rs
- src/test_helper.rs
Add a test for the failed normalization of an address inside a vDSO. This effectively is a regression test for commit d4e1733e4369 ("capi: Add missing blaze_normalize_reason variants"), without which we would panic.
> capi: Add test for failed vDSO normalization

- src/elf/resolver.rs
- tests/suite/symbolize.rs
This PR addresses the [issue ](https://github.com/libbpf/blazesym/issues/1221).
Prevent `ElfResolver::open` from panicking when it cannot handle cases where the file cannot be opened or does not exist.
Added a new test
> ElfResolver creation must not crash with non-existing file

- dev/Cargo.toml
Relax the libbpf-sys version requirement. At this point we don't care about the patch level.
> Relax libbpf-sys version requirement

- src/dwarf/lines.rs
- src/dwarf/location.rs
- src/dwarf/range.rs
- src/dwarf/unit.rs
- src/dwarf/units.rs
Use the `gimli::Result` typedef more instead of the longer `Result<..., gimli::Error>` construct.
> Use gimli::Result typedef more

- src/dwarf/range.rs
Auto-derive the `Default` impl for the `RangeAttributes` type, instead of manually coding up the same thing.
> Auto-derive Default impl for RangeAttributes type

- src/dwarf/resolver.rs
We really should be maintaining a cache of debug link targets or, actually, just include them in our per-Symbolizer cache of ELF files. Right now if multiple files have the same debug target we would end up re-parsing each. Add a TODO to address this deficiency in the future.
> Add TODO for caching debug link targets

- src/dwarf/reader.rs
Simplify the `load_section()` function slightly, by reusing the module local `Endianess` type instead of duplicating the conditional logic.
> Simplify load_section() slightly

- src/dwarf/resolver.rs
Recognize the DWARF constants representing the C++ 17 & 20 languages and map them to our notion of C++. This way, demangling is expected to work correctly on symbols in DWARF data for these languages.
> Recognize C++ 17 & 20 DWARF languages

- src/dwarf/lines.rs
- src/dwarf/location.rs
- src/dwarf/unit.rs
Simplify the logic in `dwarf::Unit::find_location()`, by removing the entire concept of the `LocationRangeUnitIter` and inlining its core functionality there. We don't really need an iterator, because we are only interested in the location for a single address and not a range, where iteration would make actual sense.
> Simplify dwarf::Unit::find_location()

- src/dwarf/function.rs
- src/dwarf/lines.rs
- src/dwarf/unit.rs
It can be hard to printf-debug DWARF code because some of our types don't implement `Debug`. Fix that.
> Derive Debug impl for more DWARF types

- src/dwarf/unit.rs
- src/dwarf/units.rs
Passing a readily-formed `UnitRef` to `Unit::parse_lines()` is dangerous, because it can easily lead to shenanigans such as the contained DWARF unit not actually the same one as that referenced by the `Unit` object itself.
Prevent such scenarios from occurring by requiring a Units reference as input instead of a UnitRef.
> Provide Units reference to Unit::parse_lines()

- .github/workflows/test.yml
This cargo-c quark is failing randomly in CI, with some undebuggable rustup error (e.g. [0]). The chance of us breaking the cargo-c dance is relatively slim and we can't live with this flakiness. Back out the change.
This reverts commit 06c035bab910c020b90656b7f0dde2be1f2efb97.
[0] https://github.com/libbpf/blazesym/actions/runs/17268520303/job/49006562941#step:9:49
> Revert "Add CI test for cargo-c packaging"

- Cargo.lock
- capi/CHANGELOG.md
- capi/Cargo.toml
- capi/include/blazesym.h
This change bumps the crate's version to `0.1.4`. The following notable changes have been made since `0.1.3`:
- Bumped `blazesym` dependency to `0.2.0-rc.5`
> capi: Bump version to 0.1.4

- .github/dependabot.yml
Specify a saner time for Dependabot to perform its updates rather than "some time in middle of the day". That's particularly useful now that most (?) updates should go through without interaction, so that these runs don't clog up CI.
> Specify Dependabot update time

- data/test-block.c
When a system has the stack protector feature enabled, our test-block test program may fail to link, with the linker citing an undefined reference to the __stack_chk_fail() function. Define it to fix this error.
Closes: #1283
Reported-by: Arvid Norlander <VorpalBlade@users.noreply.github.com>
> Fix test-block link failure with stack protector

- Cargo.toml
- capi/Cargo.toml
Loosen the tempfile version requirement to keep Dependabot from bumping versions in our Cargo.toml manifest.
> Loosen tempfile version requirements

- src/elf/parser.rs
One of the doc comments inside our `ElfParser` type incorrectly references a `_mmap` member, which had been renamed to `_backend` in the past. Reword.
> Fix doc comment in ElfParser

- src/normalize/normalizer.rs
- src/symbolize/source.rs
Rustdoc doesn't require the usage of empty square brackets for links, so don't provide them.
> Don't use empty square brackets for rustdoc links

- Cargo.toml
- README.md
We don't explain all the crate's features inside the README and we really don't want to maintain another list of them outside of the manifest definition. To still provide increased visibility into the fact that there are features, add a section on the topic to the README and reference Cargo.toml from there.
> Reference features in README

- src/mmap.rs
Usage of memory mapped I/O is inherently problematic in Rust, because of its strong aliasing assumptions, which can break when data is modified behind its back. This is nothing that we expect users to do, but we cannot prevent it either (we could, conceivably, refuse to work on writable files, but there is no guarantee they will stay that way and the usability hit would in all likelihood be unacceptable). Add a SAFETY comment alluding to the situation at the usage site of the mmap APIs.
> Add "SAFETY" comment about mmap usage
