libbpf/blazesym

build.rs
examples/addr2ln.rs
examples/addr2ln_pid.rs
src/dwarf.rs
src/elf.rs
src/elf_cache.rs
src/ksym.rs
src/lib.rs
src/tools.rs

Trivial change :)
Signed-off-by: Yongkun Gui <ygui@google.com>

Fix format by `cargo fmt`

---

Cargo.toml

Provide correct package information to register on crates.io.

Add package information.

---

.github/workflows/ci.yml
examples/addr2ln.rs
examples/addr2ln_pid.rs
src/dwarf.rs
src/dwarf/debug_info.rs
src/elf.rs
src/ksym.rs
src/lib.rs
src/tools.rs

Please see individual commits for description.

Run CI on pull requests and pushes

---

Cargo.toml
src/ksym.rs
src/lib.rs

Return all symbols from a kallsym

---

src/ksym.rs

We don't use it anymore due the commit 4cf5100e.

Remove Ksym::c_name.

---

src/tools.rs

Fixes #31. We use CStr instead to fix these concerns.

Fix potential issue of extract_string().

---

src/elf.rs

The function suffers from similar issues as pointed out in 8308d84f18f0 ("Remove Box usage and some safety issues from parse_debug_line_cu"). Fix it by using a stack allocated intermediate buffer from which we read the desired object.

Fix read_elf_header()

---

.github/workflows/ci.yml
Cargo.toml
build.rs
data/test.c
src/dwarf.rs
src/dwarf/debug_info.rs
src/gsym/parser.rs
src/lib.rs

Please see individual commits for summary.

Enable code coverage collection

---

.github/workflows/ci.yml
build.rs
src/dwarf.rs
src/elf.rs
src/elf_cache.rs
src/gsym/parser.rs

Fix testing on release builds

---

src/dwarf/debug_info.rs
src/util.rs

Please see individual commits for description.

Start using new read functionality

---

src/dwarf.rs
src/elf/cache.rs
src/elf/parser.rs
src/ksym.rs
src/lib.rs

Implement Debug for user-facing types. See [0].
[0]: https://rust-lang.github.io/api-guidelines/debuggability.html#all-public-types-implement-debug-c-debug.

Implement Debug for user-facing types

---

.github/workflows/publish.yml
.github/workflows/test.yml
.gitignore
Cargo.toml

Add a workflow for publishing the crate. Please see individual commits for details.
Test run: https://github.com/danielocfb/blazesym/actions/runs/4379193615

Add a workflow for publishing the crate

---

.github/workflows/test.yml
Cargo.toml
README.md
build.rs
include/blazesym.h

Check in generated C header

---

src/gsym/parser.rs

Brought up as part of the review for the overhaul of the GSYM parsing [0], this change adjusts GsymContext::addr_at() to directly read addresses of the expected size, instead of assembling them from individually read bytes. I checked at it appears as if GSYM supports 1, 2, 4, and 8 byte long addresses.
[0]: https://github.com/libbpf/blazesym/pull/79#discussion_r1140829239

Read address data directly

---

src/lib.rs
src/maps.rs
src/util.rs

Rework `/proc/.../maps` parsing

---

src/dwarf/parser.rs
src/dwarf/resolver.rs
src/gsym/parser.rs
src/gsym/resolver.rs
src/lib.rs
src/util.rs

Eliminate some hand rolled binary searches

---

README.md
benches/dwarf.rs
benches/gsym.rs
examples/addr2ln.rs
examples/addr2ln_pid.rs
src/c_api.rs
src/lib.rs
tests/blazesym.rs

Fix some error handling

---

src/zip.rs

The current API of the zip `Archive` type, coming from a direct translation of the C API, does not lend itself to Rust usage patterns. For example, it's not possible to iterate over the entries in such an archive.
This change introduces an iterator type that allows for iteration over said entries. We will require this functionality once we start support symbolizing addresses pointing within an mmap'ed archive.

Make iteration over zip entries possible

---

src/ksym.rs

It makes no sense for KSymResolver to be default constructible as it does not have any logically meaningful default. Remove the Default trait implementation and fix up a bunch of things.

Remove Default impl for KSymResolver

---

Cargo.toml
src/c_api.rs
src/dwarf/debug_info.rs
src/dwarf/parser.rs
src/dwarf/resolver.rs
src/elf/cache.rs
src/elf/parser.rs
src/elf/resolver.rs
src/gsym/parser.rs
src/gsym/resolver.rs
src/kernel.rs
src/ksym.rs
src/lib.rs
src/maps.rs
src/mmap.rs
src/zip.rs

Introduce logging infrastructure + Misc changes

---

.gitignore
README.md
build.rs
cbindgen.toml
examples/addr2ln.rs
examples/addr2ln_pid.rs
include/blazesym.h
src/c_api.rs
src/dwarf/parser.rs
src/dwarf/resolver.rs
src/elf/parser.rs
src/lib.rs
src/resolver.rs
src/zip.rs
tests/blazesym.rs
tests/c_api.rs

Various improvements to the C API implementation

---

.github/workflows/test.yml
src/elf/mod.rs
src/elf/parser.rs
src/elf/types.rs

Make sure we build successfully on MacOS

---

src/dwarf/parser.rs
src/dwarf/resolver.rs
src/elf/resolver.rs
src/gsym/resolver.rs
src/symbolize.rs

Use `PathBuf` in some more places

---

src/elf/parser.rs
src/mmap.rs
src/normalize/normalize.rs
src/zip.rs

Introduce Mmap views"

---

src/elf/resolver.rs
src/gsym/parser.rs
src/gsym/resolver.rs
src/gsym/types.rs
src/kernel.rs
src/ksym.rs
src/resolver.rs
src/symbolize.rs

Rename Address -> Addr

---

Cargo.toml
benches/dwarf.rs
benches/gsym.rs
benches/main.rs
benches/normalize.rs

Add benchmarks for normalization functionality

---

src/symbolize.rs

This change factors out the `BlazeSymbolizer::symbolize_with_resolver()` method from the existing code.

Factor out BlazeSymbolizer::symbolize_with_resolver() method

---

src/dwarf/parser.rs

We have now repeatedly seen generated test binaries that panic caused by an underflow of the opcode calculation (e.g., here [0]). Use proper checked subtraction to catch such errors as expected, instead of doing the wrong thing on release builds or packing everywhere else.
[0]: https://github.com/libbpf/blazesym/actions/runs/4823128486/jobs/8591227135?pr=128#step:5:158

Error out on invalid opcodes

---

README.md
benches/main.rs
benches/normalize.rs
benches/symbolize.rs
build.rs
cbindgen.toml
examples/addr2ln_pid.rs
include/blazesym.h
src/c_api/mod.rs
src/c_api/normalize.rs
src/c_api/symbolize.rs
src/elf/resolver.rs
src/lib.rs
src/maps.rs
src/normalize/mod.rs
src/normalize/normalize.rs
src/resolver.rs
src/symbolize.rs
tests/blazesym.rs
tests/c_api.rs

Introduce Normalizer, make Pid public, start symbolization rework 

---

README.md

Make a few mechanical updates to the README. More to come.

Few mechanical updates to README

---

README.md
src/lib.rs

Overhaul the README. Remove API usage examples. They will be contained in the documentation, where they can be maintained more easily. Provide a rough status & roadmap. Elaborate more on usage.

Overhaul README

---

cbindgen.toml
examples/addr2ln.rs
examples/addr2ln_pid.rs
include/blazesym.h
src/c_api/symbolize.rs
src/elf/resolver.rs
src/gsym/resolver.rs
src/lib.rs
src/symbolize.rs
tests/c_api.rs

Rename a bunch more types, functions & fields in C API

---

benches/dwarf.rs
benches/gsym.rs
benches/symbolize.rs
cbindgen.toml
examples/addr2ln.rs
examples/addr2ln_pid.rs
include/blazesym.h
src/c_api/inspect.rs
src/c_api/symbolize.rs
src/lib.rs
src/resolver.rs
src/symbolize.rs
tests/blazesym.rs

Rename a bunch of things symbolize

---

src/maps.rs
src/normalize/meta.rs
src/normalize/normalizer.rs

Fix bug in normalization logic

---

include/blazesym.h
src/c_api/symbolize.rs
tests/c_api.rs

Rename two more types and a function

---

CHANGELOG.md
data/test-stable-addresses.c
src/elf/mod.rs
src/elf/parser.rs
src/elf/resolver.rs
src/gsym/resolver.rs
tests/blazesym.rs

Rework file offset lookup

---

src/normalize/normalizer.rs

This change factors out a new internal function in the normalizer module: `normalize_elf_offset_with_parser`. It can be used to normalize a file offset given an already constructed `ElfParser` object.

Factor out normalize_elf_offset_with_parser

---

src/dwarf/parser.rs

Use the io::Result typedef instead of Result<T, io::Error> throughout the dwarf::parser module.

Use io::Result in dwarf::parser module

---

tests/blazesym.rs

The majority of our test cases symbolizes addresses directly matching a symbol's address (i.e., without an offset into it). That's not particularly realistic. Add tests that also symbolize addresses at an offset from a function's start address.

Add test for symbolization of addresses inside functions

---

src/dwarf/resolver.rs
src/util.rs

This change reworks the `DwarfResolver` internals to use the newly introduced `Cache` type. This type mirrors what we already have in the `ElfParser` type.

Rework DwarfResolver internals to use Cache type

---

src/normalize/mod.rs

Make it a bit clearer what the normalization module does by improving the code example with a few more details.

Improve normalization example

---

CHANGELOG.md
build.rs
src/dwarf/parser.rs
src/dwarf/resolver.rs
src/elf/parser.rs
src/elf/resolver.rs
src/elf/types.rs
tests/blazesym.rs
tests/c_api.rs

Add support for using DWARF information when symbolizing

---

src/normalize/mod.rs

Reword the normalization example output as per suggestions here [0].
[0] https://github.com/libbpf/blazesym/pull/205#discussion_r1220459701

Reword normalization example output

---

src/symbolize/symbolizer.rs

Fix up yet another piece of logic that swallows errors by bubbling them up properly.

Stop swalling errors in Symbolizer::symbolize_with_resolver

---

src/dwarf/parser.rs

When we implemented the gimli based DWARF symbol parsing, we opted for an approach that makes section usage obvious, by loading all possibly required sections and providing contents to functions as necessary. However, we won't be able to keep this up. DWARF is just too intertwined, where everything can reference everything and in the end we will need a god-object as provided with gimli::Dwarf. We can already see that if we look at gimli::Attribute::string_value() [0] and the warning there, which recommends usage of Dwarf::attr_string instead:
> this function does not handle all possible string forms. Use
> Dwarf::attr_string instead.
So switch over to using a gimli::Dwarf object instead. Performance change seems to be within noise levels.
[0] …

Work with complete Dwarf object when parsing symbols

---

CHANGELOG.md
benches/symbolize.rs
include/blazesym.h
src/c_api/symbolize.rs
src/gsym/resolver.rs
src/symbolize/mod.rs
src/symbolize/source.rs
src/symbolize/symbolizer.rs
tests/blazesym.rs
tests/c_api.rs

Support "raw" Gsym data as symbolization source

---

src/dwarf/resolver.rs
src/elf/cache.rs
src/elf/resolver.rs
src/error.rs
src/gsym/resolver.rs
src/kernel.rs
src/ksym.rs
src/resolver.rs
src/zip.rs

This change switches the zip module over to using our own Error type.

Convert zip module over to using Error type

---

src/dwarf/parser.rs
src/elf/parser.rs
src/error.rs
src/gsym/parser.rs
src/mmap.rs

Convert more module to using `Error` type

---

src/dwarf/parser.rs

Currently our DWARF logic always assumes little endian format. Change that so that we always pick the target system's endianess instead, which is more future proof.

Determine byte order at compile time

---

src/elf/parser.rs

We never intend to resize the elf::parser::Cache::symtab or str2symtab entries. As such, we don't need them to be a Vec. A box of a slice is sufficient. Adjust the code accordingly.

Store `Box` objects instead of `Vec` in ELF cache

---

src/normalize/buildid.rs

We introduced the `BuildIdNote` type as a means to read the build ID. However, with a better understanding of the ELF note format, it seems cleaner to just read and evaluate the notes header directly instead of going through this more or less made up representation, which (at least in the way we currently uses it) silently ignores the "name size" field.

Remove `BuildIdNote` type usage

---

src/elf/cache.rs
src/error.rs
src/maps.rs
src/normalize/user.rs
src/symbolize/symbolizer.rs

Annotate a few error paths with additional information that can be useful in understanding failures.
Refs: #266

Provide more error context

---

CHANGELOG.md
benches/symbolize.rs
cli/src/main.rs
examples/addr2ln.rs
examples/addr2ln_pid.rs
examples/backtrace.rs
include/blazesym.h
src/c_api/symbolize.rs
src/dwarf/resolver.rs
src/gsym/resolver.rs
src/symbolize/mod.rs
src/symbolize/symbolizer.rs
tests/blazesym.rs
tests/c_api.rs

Rename `SymbolizeResult` type

---

src/error.rs

Our `Error` type is a tad sparsely documented. Add some more information to the documentation.

Improve documentation of Error type

---

src/gsym/resolver.rs

Shorten a few error paths inside of the `GsymResolver` implementation by using helper functions from our `IntoError` trait.

Use IntoError trait more in GsymResolver

---

tests/blazesym.rs
tests/c_api.rs

With an earlier change we already started combining ELF and DWARF symbolization tests into combined test cases, to minimize the possibility of divergence and also the duplication of setup code. This change takes things a step further and integrates GSYM tests as well.

Unify symbolize tests more

---

src/error.rs

This change fixes a few small issues in the documentation of the error module.

Improve error module documentation

---

cli/src/args.rs
cli/src/main.rs

Add `normalize` command to `blazecli`

---

src/error.rs

Add a few more lines of documentation to the Error functionality.

Add a few more lines of documentation to Error functionality

---

src/gsym/resolver.rs

Simplify the Gsym inline stack fixup work we have to do by merging the two loops.

Simplify Gsym inline stack fixup

---

CHANGELOG.md
src/normalize/buildid.rs
src/normalize/mod.rs
src/normalize/normalizer.rs
src/normalize/user.rs
tests/blazesym.rs

Make build ID reading optional

---

src/dwarf/resolver.rs

Refactor the body of DwarfResolver::find_code_info() slightly, making its structure a bit less complex.

Refactor DwarfResolver::find_code_info() slightly

---

CHANGELOG.md
benches/normalize.rs
benches/symbolize.rs
cli/src/main.rs
examples/addr2ln.rs
examples/addr2ln_pid.rs
examples/backtrace.rs
include/blazesym.h
src/c_api/normalize.rs
src/c_api/symbolize.rs
src/elf/cache.rs
src/elf/resolver.rs
src/normalize/buildid.rs
src/normalize/meta.rs
src/normalize/mod.rs
src/normalize/normalizer.rs
src/normalize/user.rs
src/symbolize/mod.rs
src/symbolize/source.rs
src/symbolize/symbolizer.rs
tests/blazesym.rs
tests/c_api.rs

Rework normalization to use file offsets

---

src/normalize/meta.rs
src/normalize/mod.rs
src/normalize/normalizer.rs
src/symbolize/source.rs

This patch improves the documentation a bit more.

Improve documentation some more

---

README-devel.md
README.md
src/dwarf/units.rs

This change adds a new README file, README-devel.md, that contains a few development related resources.

Add some development resources in the form of README-devel.md

---

CHANGELOG.md
src/elf/backend.rs
src/elf/cache.rs
src/elf/mod.rs
src/elf/parser.rs
src/elf/resolver.rs
src/file_cache.rs
src/kernel.rs
src/ksym.rs
src/lib.rs
src/normalize/buildid.rs
src/symbolize/symbolizer.rs
src/zip.rs
tests/blazesym.rs

Rework ELF caching logic

---

src/gsym/linetab.rs

This change renames the ctx argument of the run_op() function to row, more accurately reflecting what it is.

Rename ctx argument of run_op() to row

---

src/error.rs

Use struct syntax for variants of the ErrorImpl enum type to allow for easier future expansion.

Use struct syntax for ErrorImpl variants

---

CHANGELOG.md
README-devel.md
src/c_api/inspect.rs
src/dwarf/resolver.rs
src/elf/parser.rs
src/elf/resolver.rs
src/gsym/resolver.rs
src/inspect/inspector.rs
src/inspect/mod.rs
src/kernel.rs
src/ksym.rs
src/normalize/normalizer.rs
src/resolver.rs
tests/blazesym.rs

Various improvements to inspect APIs

---

src/symbolize/symbolizer.rs

Use Cow type in the symbol name demangling logic to minimize the need for allocations at lower levels. We still end up allocating unconditionally higher up the stack currently, but that may change eventually.

Make demangling bits use `Cow`

---

src/symbolize/source.rs

This change comprises a set of minor random improvements to symbolize/source.rs:
- add #[inline] annotations to some small functions
- improve Debug representation of a few types
- add more Debug representation coverage

Random improvements to symbolize/source.rs

---

src/elf/resolver.rs

The ELF resolver uses the bare-bones ELF backend by default, even if asked to incorporate debug symbols. Only if this backend does not yield any symbols will it "fall back" to using DWARF data. This is a questionable practice and causing confusion all over the place. Switch to using DWARF data if enabled by default, but fall back to ELF if it does not yield anything.

Use DWARF backend by default

---

src/elf/parser.rs

Convert `ElfParser` to use `OnceCell`

---

src/ksym.rs

As it turns out `KSymResolver`'s `find_addr()` method does not currently return multiple results even if multiple symbols with the same name exist. That's obviously wrong.
Switch from using a `HashMap` to a `Vec` as the by-name index and adjust `find_addr()` to return all matching symbols.

Fix `KSymResolver::find_addr` to return multiple results

---

src/symbolize/symbolizer.rs

This change fixes a couple of issues that a newer version of clippy reported.

Fix clippy reported issues

---

capi/src/symbolize.rs

This change adds a proper unit test for the Rust to C symbol conversion, represented by the `convert_symbolizedresults_to_c()` function.

Add test for Rust to C symbol conversion

---

capi/src/inspect.rs

It's dangerous to have a From impl from blaze_inspect_elf_src that assumes that the data in there came from Rust created objects -- users are free to allocate paths or similar in however way they like. Switch to using private functions for accomplishing the same goals, but without potential unsoundness issues for users.

capi: Stop implementing From<blaze_inspect_elf_src> for Elf

---

capi/src/normalize.rs

Similar to what we did earlier for the inspect module, switch to using private functions instead of trait implementations when it comes to the consuming conversion of C objects containing pointers into the corresponding Rust objects.

capi: Remove consuming From conversions of normalization types

---

CHANGELOG.md
capi/CHANGELOG.md
capi/include/blazesym.h
capi/src/symbolize.rs
src/file_cache.rs
src/inspect/inspector.rs
src/symbolize/symbolizer.rs

Make auto reloading of source data configurable

---

CHANGELOG.md
build.rs
capi/CHANGELOG.md
capi/include/blazesym.h
capi/src/symbolize.rs
cli/src/args.rs
cli/src/main.rs
data/test-wait.c
src/symbolize/source.rs
src/symbolize/symbolizer.rs
tests/common.rs
tests/permission.rs
tests/permissionless.rs

Please see individual commits for description.

Add support for "permissionless" symbolization

---

src/inspect/inspector.rs

This change refactors the internals of the Inspector::lookup() method a bit. We separate the look up of the resolver to use from the rest of the logic, which will make it easier to added additional sources using similar logic in the future.

Refactor Inspector::lookup() internals

---

CHANGELOG.md
capi/CHANGELOG.md
capi/include/blazesym.h
capi/src/normalize.rs
src/normalize/meta.rs
src/normalize/mod.rs
src/normalize/normalizer.rs
src/normalize/user.rs
src/symbolize/mod.rs
src/symbolize/symbolizer.rs

Introduce Reason to normalization APIs

---

capi/src/symbolize.rs

This change adds a test for the ELF file offset symbolization, as added by #569.

capi: Add test for blaze_symbolize_elf_file_offsets()

---

CHANGELOG.md
capi/src/normalize.rs
src/lib.rs
src/normalize/buildid.rs
src/normalize/meta.rs
src/normalize/normalizer.rs
src/normalize/user.rs
tests/blazesym.rs

Return references to cached build IDs as part of normalization

---

README.md

Add a few more tidbits of information to the README.

Add a few more details to the README

---

src/inspect/inspector.rs

Invoking `Inspector::for_each()` with a few functions will monomorphize all the code backing it for each individual function, which can result in binary bloat.
Let's just use dynamic dispatch at the public API level to curb any potential bloat issues.

Don't monomorphize every Inspector::for_each() variant

---

capi/src/normalize.rs

Increase code coverage slightly by adding a test causing a normalization failure, because input addresses are not sorted properly when they should be.

capi: Add test for normalization failure

---

src/gsym/resolver.rs

Rename a few variables inside the GsymResolver::find_code_info() function, to make it more obvious which parts are shared with GsymResolver::find_sym().

Rename a few variables in GsymResolver::find_code_info()

---

src/dwarf/resolver.rs

Flatten the internals of the DwarfResolver::find_code_info() method to make it easier to understand.

Flatten DwarfResolver::find_code_info() internals

---

src/gsym/resolver.rs

Flatten the internals of the GsymResolver::find_code_info() method to make it easier to be understood.

Flatten GsymResolver::find_code_info() internals

---

src/breakpad/resolver.rs

Flatten the internals of the BreakpadResolver::find_code_info() method to make it easier to understand.

Flatten BreakpadResolver::find_code_info() internals

---

src/breakpad/resolver.rs
src/dwarf/resolver.rs
src/gsym/resolver.rs

Change all our find_code_info() methods to fill_code_info() ones, which no longer return an AddrCodeInfo object but just modify the IntSym object passed to it on the fly.

Change *::find_code_info() to *::fill_code_info()

---

src/dwarf/resolver.rs

Implement the Symbolize and Inspect traits for the DwarfResolver type, effectively making it a first-class "resolver".

Make DwarfResolver implement Symbolize and Inspect traits

---

src/ksym.rs

The way that the Inspect trait is implemented for KsymResolver is rather clumsy and wasteful. Instead of storing a vector of 'static strings and their associated addresses, it is easier and more space efficient to create an on top of the underlying syms array that is sorted by name.

Simplify KsymResolver Inspect impl

---

src/elf/resolver.rs

Remove the ElfResolver::with_backend() constructor. It's not really useful at all and causes more confusion than it is worth.

Remove ElfResolver::with_backend() constructor

---

src/symbolize/mod.rs

The documentation of the symbolize module has this long-winded example showing how to capture and symbolize a backtrace. But because there is so much additional setup necessary, there is arguably too little focus on the working of the "core" APIs.
This change simplifies the example, symbolizing the addresses of two known libc functions instead. The backtrace example is only linked to.

Use simpler example in documentation of symbolize module

---

build.rs

Use `strip` with the `-o` argument to strip a binary and write it to a destination in one go, instead of "manually" creating a copy of the file to work on first. Let's just hope that this option is supported as widely as the implicit output logic.

Use `strip -o` instead of manually copying the source file first

---

build.rs

This change introduces the ArgSpec enum, which helps define how the toolize_impl() function specifies source and destination file to the tool being invoked.

Introduce ArgSpec enum

---

build.rs

Introduce a function for retrieving the path to the data/ directory, which frees us up from having to pass said path around everywhere.

Introduce function for retrieving data/ directory path

---

build.rs

Introduce the cc_stable_addrs() helper function in order to get rid of all the arguments necessary for compiling this test binary.

Factor out cc_stable_addrs() helper function

---

tests/allocs.rs

Because we install a *global* allocator, all allocations in the allocs
test end up being "traced". When backtrace capture is enabled, that will
cause a bunch of backtraces to be printed, even if the test is not even
run, because allocations may be happening by the start up and tear down
code. To silence the noise, make sure to enable this tracing only for
the test in question.

Only enable alloc tracing when running test

---

benches/main.rs
capi/benches/normalize.rs
src/elf/parser.rs
src/gsym/resolver.rs
src/normalize/normalizer.rs
src/symbolize/symbolizer.rs
tests/allocs.rs

Address some "issues" that clippy reports in most recent versions of Rust.

Address clippy reported issues

---

src/breakpad/parser.rs

The convert_nom_err() function is unnecessary: it is basically just a thin wrapper around convert_verbose_nom_error() that deals with the Err wrapper, but this wrapper can be foregone entirely if we just move the conversion further down into the corresponding match arm.

Remove unnecessary convert_nom_err() function

---

.gitignore
CHANGELOG.md
build.rs
src/dwarf/debug_link.rs
src/dwarf/mod.rs
src/dwarf/resolver.rs
src/elf/resolver.rs
src/file_cache.rs
tests/blazesym.rs

Add support for following debug links

---

src/dwarf/debug_link.rs
src/dwarf/resolver.rs

The logic for finding suitable debug file candidates is somewhat ad-hoc and most certainly not easily testable.
This change converts it to a general iterator based approach. In so doing we make it much easier extensible, which will help with making the directories to search more configurable.

Make debug file discovery iterator based

---

src/inspect/source.rs

Improve the Debug representations of various inspection source types to make them more concise and in-line with symbolization source behavior.
Refs: #223

Improve Debug representation of inspection sources

---

CHANGELOG.md
benches/normalize.rs
capi/CHANGELOG.md
capi/benches/normalize.rs
capi/include/blazesym.h
capi/src/normalize.rs
capi/src/symbolize.rs
src/normalize/meta.rs
src/normalize/mod.rs
src/normalize/normalizer.rs
src/normalize/user.rs
src/symbolize/source.rs
tests/allocs.rs
tests/blazesym.rs

Allow for reporting of "map_files" paths from normalization APIs

---

capi/src/symbolize.rs

Add a test checking that we correctly return the `BLAZE_ERR_NOT_FOUND` error when a symbolization source was not found.

capi: Add test checking BLAZE_ERR_NOT_FOUND last error

---

README-devel.md

Add a section about how to invoke/use Miri to README-devel.

Add section about Miri invocation to README-devel

---

capi/src/normalize.rs

We missed checking the normalization test suite for Miri eligible candidates. There are a few. Tag them accordingly.

capi: Onboard yet more tests to Miri

---

src/normalize/normalizer.rs

Add a test checking that we can successfully normalize addresses even if the still mapped shared object has been deleted. Do in in various normalization configurations and ensure that the build ID is always found as expected.

Add test for address normalization in deleted shared object

---

build.rs

Adjust the toolize_impl() function to support multiple source files. This functionality will be necessary in the future.

Adjust toolize_impl() to support multiple source files

---

capi/src/inspect.rs

The convert_syms_list_to_c() may fail to allocate memory for the result. Make sure to check the result of the allocation and bail out on error, setting the corresponding last error accordingly.

capi: Check for allocation failures in convert_syms_list_to_c()

---

src/normalize/user.rs
src/symbolize/symbolizer.rs

There no longer (?) is a reason to report any errors from the normalize::Handler::handle_unknown_addr() method. In fact, none of the implementations does report an error.
Make the method infallible to make that fact more obvious and because we do not intend to introduce fallible code paths in the future.

Make normalize::Handler::handle_unknown_addr() infallible

---

src/symbolize/symbolizer.rs

Make the SymbolizeHandler free-standing to make it easier to unit test its logic.

Make SymbolizeHandler free-standing

---

src/normalize/user.rs

Add a test covering the normalization of maps "entries" without a path as well as with a "component" (as opposed to a file).

Add test for normalization of additional "entry" types

---

.github/workflows/test.yml
Cargo.toml
build.rs
src/dwarf/debug_link.rs
src/dwarf/lines.rs
src/file_cache.rs
src/gsym/parser.rs
src/maps.rs
src/mmap.rs
src/symbolize/symbolizer.rs
src/util.rs
src/zip.rs

Add minimal Windows target support

---

src/breakpad/parser.rs

Remove duplicate tracking if source code line and inlinee information from the breakpad parser's logic. It's unclear why it ever was introduced. Aside from simplifying the code, this change provides a minimal but consistently visible improvement in performance of our symbolize_breakpad benchmark:
```
$ cargo bench  --bench=main --features=nightly -- symbolize_breakpad
> Benchmarking main/symbolize_breakpad   : Warming up for 1.0000 s
> main/symbolize_breakpad
>   time:   [276.88 ms 277.46 ms 278.12 ms]
>   change: [−2.0408% −1.7631% −1.4814%] (p = 0.00 < 0.02)
>   Performance has improved.
```

Remove duplicate line & inlinee info from breakpad parser logic

---

src/util.rs

Simplify the pod_ref_reading() test case, removing a bunch of unnecessary unsafe code in the process.

Simplify pod_ref_reading() test

---

src/maps.rs

Factor out the parse_path_name() helper function from the existing parse_maps_line(), to make the logic reusable by other parts of the library in the future.

Factor out parse_path_name() helper function

---

capi/CHANGELOG.md
capi/Cargo.toml
capi/include/blazesym.h
capi/src/helper.rs
capi/src/lib.rs
src/lib.rs
src/normalize/buildid.rs
src/util.rs

capi: Introduce `blaze_read_elf_build_id()` helper

---

CHANGELOG.md
cli/src/main.rs
examples/inspect-mangled.rs
src/breakpad/resolver.rs
src/dwarf/resolver.rs
src/dwarf/unit.rs
src/dwarf/units.rs
src/elf/parser.rs
src/elf/resolver.rs
src/inspect/inspector.rs
src/inspect/mod.rs
src/ksym.rs
tests/blazesym.rs

Add support for iterating over DWARF symbols

---

src/ksym.rs

Add a benchmark for the parsing of a kallsyms-style file. Currently it also includes the freeing of a bunch of heap allocated data, but hopefully that won't perturb the measurement too much.
```
$ cargo bench --features=nightly -- bench_parse_kallsyms
> test ksym::tests::bench_parse_kallsyms   ... bench:   6,399,546.45 ns/iter (+/- 199,050.35)
```

Add benchmark for kallsyms parsing

---

src/file_cache.rs

Add a test checking that our FileCache does not represent paths with symlinks to the same file with equal entries. Doing so would be wrong, unless changes to the symbolic link itself would be tracked correctly.

Add symlink test for FileCache logic

---

.github/workflows/test.yml
README.md
dev/build.rs
src/file_cache.rs
src/lib.rs
src/normalize/ioctl.rs
src/normalize/normalizer.rs
src/symbolize/perf_map.rs
src/symbolize/symbolizer.rs
src/util.rs
tests/allocs.rs
tests/blazesym.rs
tests/common/mod.rs
tests/permission.rs
tests/permissionless.rs

Promote Mac OS to partially supported platform

---

src/kernel/bpf/prog.rs

The current BPF program iteration code basically just treats all iteration errors as terminating condition, but does not actually bubble them up. The better way is to actually check for the error that the kernel uses to indicate end of iteration (ENOENT [0]) and treat that as terminating on our end. Everything else is now bubbled up properly (including, say, permission denied issues).
[0] https://www.kernel.org/doc/html/latest/userspace-api/ebpf/syscall.html

Properly handle errors when iterating over BPF programs

---

src/elf/parser.rs

Currently it is the SymbolTableCache type's job to convert a Vec of symbols into a boxed slice. Let's move this task earlier, which will pave the way for upcoming changes but it also means one less potential copy of a Vec while we convert it down into a boxed slice.

Start working with boxed slices earlier

---

src/elf/parser.rs

Some of the ELF parser error messages are fairly generic and not exactly hinting at the fact that they are pertaining ELF. Let's be more explicit here by mentioning this fact.

Make ELF related error messages more explicit

---

CHANGELOG.md
data/test-stable-addrs.ld
dev/build.rs
src/elf/parser.rs
src/elf/types.rs
src/normalize/buildid.rs
src/util.rs
tests/suite/symbolize.rs

Add support for ELF32 class

---

src/elf/parser.rs

Introduce the Cache::section_hdr() helper, which shortens some of the code.

Introduce Cache::section_hdr() helper

---

src/dwarf/debug_link.rs
src/util.rs

Introduce a helper function that can be used for aligning values to the next power of two.

Introduce `align_up()` helper function

---

src/symbolize/symbolizer.rs

There is no reason to convert the "uname" release string into a proper UTF-8 string: all we want to do with it is append it to a path. Skip the conversion.

Eliminate unnecessary "unwrap"

---

src/kernel/kaslr.rs

Slightly rework the KASLR reading logic by moving some of the necessary setup code into a new top level function. In the future this will make it easier to hook up additional alternative methods for querying the system's KASLR offset, all of which basically may not be available on any given system.

Slightly rework KASLR reading logic

---

src/maps.rs

Add two more malformed proc maps lines to our
malformed_proc_maps_lines() test.

Test additional malformed proc maps lines

---

src/symbolize/source.rs
tests/suite/common/mod.rs

Land a couple of improvements, shortening the code and eliminating confusing naming.

Miscellaneous improvements

---

tests/suite/inspect.rs

Part of the reason for having a split between tests for inspection, normalization, and symbolization is because the corresponding functionality is contained in different modules and so by splitting at module boundaries we can bring more items into scope without fear of name clashes.
Somehow we ended up not doing that properly inside the "inspect" integration test suite. Do that now.

Import full inspect:: paths into scope in suite/inspect.rs

---

tests/suite/common/mod.rs
tests/suite/symbolize.rs

Introduce the `RemoteProcess` helper type, which de-duplicates some of the logic that we have for the pattern of starting a process, reading an address it emits, invoking a test callback, and then tearing down said process gracefully.

Introduce `RemoteProcess` helper

---

tests/suite/symbolize.rs

The symbolize_kernel_system_vmlinux test was found to produce the occasional test failure. The reason seems to be that kallsyms includes aliased symbols and in such a case symbolization is ambiguous:
```
> thread 'suite::symbolize::symbolize_kernel_system_vmlinux' panicked at tests/suite/symbolize.rs:1328:9:
> assertion `left == right` failed: Sym { name: "memcpy", addr: 18446744071584231392, offset: 421527552, ...} | (18446744072005758944, "__memcpy")
>   left: "memcpy"
>  right: "__memcpy"
```
To fix this issue, make sure that we only use unique addresses as part of the symbolization test.

Fix symbolize_kernel_system_vmlinux test flakiness

---

src/elf/parser.rs

The `ElfParser::file_offset()` method doesn't really have to be a method -- it does not use the `&self` argument at all. Make it a free-standing function to make it more easily reusable.

Make file_offset() a free-standing function

---

src/elf/parser.rs

We can hit a potential underflow during file offset calculation, with specifically crafted symbol/section header values. Fix that by using explicitly wrapping arithmetic.

Fix potential underflow in file offset calculation

---

src/normalize/normalizer.rs
src/normalize/user.rs

Instead of plumbing through individual flags to our internally used `NormalizationHandler`, just pass in and store the complete `NormalizeOpts` object. Doing so has the nice side-effect of making call sites perhaps a tad more understandable, because we stop dealing with boolean flags there.

Store NormalizeOpts inside NormalizationHandler

---

src/symbolize/symbolizer.rs

Improve some of the error messages potentially emitted on the APK symbolization, by including additional context in them.

Improve some APK symbolization error messages

---

src/normalize/normalizer.rs

Rename the caching related members of the Normalizer type. In so doing we align more with the nomenclature used in the Symbolizer type.

Rename Normalizer cache members

---

CHANGELOG.md
capi/CHANGELOG.md
capi/Cargo.toml
capi/include/blazesym.h
capi/src/normalize.rs
src/normalize/buildid.rs
src/normalize/meta.rs
src/normalize/mod.rs
src/normalize/normalizer.rs
src/normalize/user.rs
tests/suite/normalize.rs

Add support for normalizing APK addresses to contained ELF file

---

src/file_cache.rs
src/insert_map.rs

Add support for inserting "cached" entries to FileCache 

---

CHANGELOG.md
capi/CHANGELOG.md
capi/include/blazesym.h
capi/src/symbolize.rs
src/elf/parser.rs
src/elf/resolver.rs
src/file_cache.rs
src/symbolize/cache.rs
src/symbolize/symbolizer.rs
tests/suite/symbolize.rs

Add support for caching of ELF data 

---

src/file_cache.rs

Add benchmarks for FileCache entry accesses

---

.github/workflows/test.yml
src/dwarf/debug_link.rs
src/dwarf/resolver.rs
src/dwarf/units.rs
src/elf/parser.rs
src/elf/resolver.rs
src/inspect/inspector.rs
src/kernel/kaslr.rs
src/lib.rs
src/maps.rs
src/normalize/buildid.rs
src/normalize/normalizer.rs
src/pathlike.rs
src/symbolize/symbolizer.rs
src/test_helper.rs
src/zip.rs
tests/suite/symbolize.rs

Introduce PathLike trait

---

.github/workflows/test.yml
Cargo.lock
capi/CHANGELOG.md
capi/Cargo.toml
capi/include/blazesym.h
capi/src/lib.rs
capi/src/normalize.rs
capi/src/symbolize.rs

capi: Ensure there are no padding bytes in types

---

src/elf/parser.rs

Playing around with Miri in an attempt to investigate two TODOs in our `BackendImpl::{read_pod_obj,read_pod_slice}` methods for the `File` type, I confirmed that there is no issue with mutable reference usage. However, it turned out that there can be unsoundness if a type contains padding bytes. The `mem::zeroed` initialization that we used when resizing the vector we allocate does not guarantee padding bytes are initialized and so, a hypothetically compliant `io::Read` implementation could read truly uninitialized memory.
I don't believe any of the types we use have padding bytes and this code is only used for the KASLR reading anyway (which is file I/O based), but with this change we factor out the logic into separate functions, fix the problems, and add Miri based tests for it to have …

Fix potential unsoundness in Pod reading code

---

src/error.rs

As it turns out, due to a typo we were not actually using the `test_fork` crate when running the `Error` tests as we intended to. Adjust the code to make sure that we use the correct functionality.
Furthermore, it now appears as if the standard library's environment variable caching no longer causes trouble, so remove the test-only `MaybeCapture` trait.

Actually use `test_fork` for `Error` tests

---

capi/include/blazesym.h
capi/src/symbolize.rs
src/elf/mod.rs
src/elf/parser.rs
src/lib.rs
src/symbolize/source.rs
src/symbolize/symbolizer.rs
src/test_helper.rs
src/vdso.rs
tests/suite/symbolize.rs

Assume system-wide vDSO image

---

src/symbolize/symbolizer.rs
src/vdso.rs

Move the `Symbolizer::create_vdso_parser()` method as a freestanding function into the `vdso` module. This way, it can be repurposed more easily.

Move more vDSO functionality into vdso module

---

CHANGELOG.md
src/dwarf/debug_link.rs
src/maps.rs
src/normalize/meta.rs
src/normalize/normalizer.rs
src/normalize/user.rs
src/symbolize/mod.rs
src/symbolize/symbolizer.rs
tests/suite/normalize.rs

Add support for normalizing vDSO addresses

---

src/dwarf/units.rs

These don't normally have ranges anyway, but it is possible for them to have a DW_AT_stmt_list that points to the same program that contains ranges for a compilation unit, and loading the ranges from that is wrong.
This is a cross port of commit 4289882456d2 ("Don't parse ranges for partial units (#313)") from addr2line.

Don't parse ranges for partial units

---

src/dwarf/function.rs

Co-locate the impl of the Function type with the definition of the type, so that it's easier to reason about the two.

Co-locate Function impl with type definition

---

src/dwarf/function.rs

Introduce the InlinedState helper type to "simplify" some of the logic dealing with the parsing of inlined functions.

Introduce InlinedState helper type
